### ISSUE TITLE
[Permission denied Error message is not displayed in kibana, stacktrace is displayed]

### ISSUE THREAD

**Issue by archupriya3** [opensearch-project/security-dashboards-plugin#1000]
**What is the bug?**
The user without index-pattern permission clicks on the index-pattern (data present) then it is displaying "Search Error" 
![image](https://user-images.githubusercontent.com/42887698/170181257-3ae3e89f-9e56-464e-9b72-5d13f0c90aca.png)

**How can one reproduce the bug?**
1. Create a user with limited permissions to access just few index patterns
2. login with the limited permission user and try to access the index pattern fow which user has no permission

**What is the expected behavior?**
A clear error message that says " user does not have permission to access the index must be displayed"
Instead we get a "Search Error" which on expansion gives stack trace of the message.
In ES client pod logs we are able to see the permission error logs but the same not displayed on Kibana UI.
![image](https://user-images.githubusercontent.com/42887698/170182458-d9119ea9-287d-4e51-847d-3f3bb2fd12a8.png)
![image](https://user-images.githubusercontent.com/42887698/170182522-d878960a-1de2-4a6f-8986-638ed2bffdb3.png)

**What is your host/environment?**
 - OS:Centos
 - Version  7.10.2
 - Plugins opendistroSecurityKibana-1.13.0.1

**Do you have any screenshots?**
Attached screenshots

**Do you have any additional context?**

**Comment by DarshitChanpura** [comment]
[Triage] Can you please open this as a support request on [the forum](https://forum.opensearch.org/)

**Comment by DarshitChanpura** [comment]
[Triage] We no longer support ODFE. Please migrate to OpenSearch 2.0 and re-open if you still see the same issue.

**Comment by archupriya3** [comment]
Issue is observed with 2.11 Opensearch version as well. Could you please re-open this issue?
