### ISSUE TITLE
[Feature] Hide index patterns in the Discovery page for the users that does not have access.

### ISSUE THREAD

**Issue by sdwerwed** [opensearch-project/security-dashboards-plugin#1021]
**Is your feature request related to a problem? Please describe.**

Some users have limited access to indexes but they can see all index patterns on the discover page in the dropdown section where you select index pattern. That creates confusion because the user gets an error if he does not have access to the indexes under the (default selected) index pattern and also sees index names that he should not see. This raised questions inside the company, that his access does not work, etc.

**Describe the solution you'd like**

List the index pattern in the Discovery page only if the role has access to at least one index under that pattern. 

**Describe alternatives you've considered**

See the discussion here: https://forum.opensearch.org/t/hide-some-index-patterns-from-the-discover-section/10199

**Comment by sdwerwed** [comment]
Also not sure if this is a feature or a bug, feel free to update it

**Comment by cliu123** [comment]
This is an expected behavior. The permissions to index patterns are managed separately from the index level access control. So a user can see all index patterns in a tenant that the user has permission to regardless of what index permissions that user has.

**Comment by cliu123** [comment]
@sdwerwed Security plugin does not support granular access control on index patterns yet, but you can manage the access with tenant permission. All users with the access to a tenant, they can see all the index patterns in the tenant.

**Comment by sdwerwed** [comment]
@cliu123 should we really close this issue because it exist a workaround or to keep it open till will be fixed with the granual access control on index pattern. This issue is when all users using global tenant. Maybe should we documents it at least the access control setup because it affects the user experience. For example when a user open the dashboard, he gets error message that they do not have access to the idexes under that index pattern. What do you think?
