### ISSUE TITLE
[Test Coverage Improvement] Add Tests for Saved Object Sharing

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/security-dashboards-plugin#1023]
There's no existing tests for the saved object sharing functionality to capture bugs like the one reported on [the issue](https://github.com/opensearch-project/security-dashboards-plugin/issues/1012).

**Comment by peternied** [comment]
[Triage] Could you provide what these test(s) should exercise in the product?

**Comment by cliu123** [comment]
The sharing saved object with url feature does not have test coverage, so [the issue](https://github.com/opensearch-project/security-dashboards-plugin/issues/1012) was not caught by automation tests.

**Comment by davidlago** [comment]
Closing this issue as work is shifting towards the [workspaces](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4615) initiative, where sharing saved objects will be improved.
