### ISSUE TITLE
Javascript/HTML code displayed on the Tenant Selection screen

### ISSUE THREAD

**Issue by ash74268** [opensearch-project/security-dashboards-plugin#105]
Hi Team,
I am running Kibana 7.1.1 behind a Proxy with Opendistro 1.1.0 plugin for Security. The kibana is configured to use server.basePath=/xyz . Everything else seems to be working fine except that the Tenant selection page is showing text as below:

`Active tenant: PCI_RSI<SCRIPT type="text/javascript"> /*<![CDATA[*/ document.cookie = "IV_JCT=%2Fcldash_xy; path=/; secure"; /*]]>*/ </SCRIPT>`

![image](https://user-images.githubusercontent.com/25277439/66334694-26657a80-e8ff-11e9-8c23-8c7f25d1b759.png)

Please let me know if there is anything that can be fixed with kibana configuration or it would be a code change for Kibana security plugin?

Thanks in advance!!

**Comment by davidlago** [comment]
I'm not able to reproduce in the current version (2.1.0). Please feel free to re-open if I'm missing somethign and we can take a look. Thank you!
