### ISSUE TITLE
Login Selector for Kibana when multiple authentication providers are enabled

### ISSUE THREAD

**Issue by Whizzzer** [opensearch-project/security-dashboards-plugin#1055]
I'm trying to create a setup with local users (basicauth) and Oauth against Azure AD (openid). The configuration is working, yet when configuring/accessing the Kibana web interface it seems it is a "either one or the other" approach. Is that correct, or am I missing something?

It seems that with xpack this is possible by setting the value ```xpack.security.authc.selector.enabled: true``` according to [this issue](https://github.com/elastic/kibana/issues/39313).

Is there a similar option within the opendistro_security plugin? Or will this option be available in the near future, or do you suggest another approach?

**Comment by davidlago** [comment]
It seems like this is now [fixed as of 2.4.0](https://github.com/opensearch-project/security-dashboards-plugin/issues/1059#issuecomment-1301720580), but please re-open with more details if that is not the case.
