### ISSUE TITLE
Tenancy information is lost when SAML Authentication is enabled 

### ISSUE THREAD

**Issue by anijain-Amazon** [opensearch-project/security-dashboards-plugin#1057]
The last saved tenant of a user is not read from local storage when they re-login to OpenSearch Dashboards with SAML Authentication enabled. This only happens for SP Initiated login flow. 

Steps to reproduce the behaviour:
1. Create a OpenSearch domain and enable SAML Authentication.
2. Create a custom tenant ( say test123 )  
3. Switch to the new custom tenant. 
4. Logout of OS Dashboard and re-login.
5. You will be logged in to the private tenant. 

https://user-images.githubusercontent.com/110471048/183603329-08b81246-7b75-42f6-87fb-ae18760507bf.mp4

Expected Behaviour : 
On logging in again, the user should be logged into the last selected tenant ( test123 ) in the above case. This expected behaviour happens when Basic Authentication is enabled on the domain. 

Environment details : 
 - OS: Amazon Linux 
 - Version : 1.3 ( This is not fixed in 2.2 as well ) 
 - Plugins : Security-Dashboards-Plugin

Additional Context on the problem :
- The file [account-app.tsx](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/account/account-app.tsx) reads the last saved tenant from local storage if the variable `opendistro::security::tenant::show_popup` in session storage is not set to false. 
- When a user logs out with Basic Auth enabled, this variable is set to null in logout function in the file [utils.tsx] (https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/account/utils.tsx) 
- The same doesn't happen for SAML Logout flow where the `/auth/saml/logout` API is called when a user logs out. 

To fix this problem, we need to set the variable `opendistro::security::tenant::show_popup` to null when a user logs out in SAML flow.

**Comment by anijain-Amazon** [comment]
PR raised for fixing this [bug](https://github.com/opensearch-project/security-dashboards-plugin/pull/1058)

**Comment by cwperks** [comment]
Thank you @anijain-Amazon for filing this bug and submitting a PR!

**Comment by jimishs** [comment]
Is there a workaround to avoid this issue, while users wait for a fix? @anijain-Amazon @devardee

**Comment by anijain-Amazon** [comment]
This has been fixed and back-ported to all versions from `1.0` to `1.3` 
It is also available in `2.x` and `2.3` branches.
