### ISSUE TITLE
[FEATURE] Support additional request parameters for OpenID Connect

### ISSUE THREAD

**Issue by HarshadRanganathan** [opensearch-project/security-dashboards-plugin#1066]
**Is your feature request related to a problem?**
OpenSearch dashboard currently supports configuration parameters stated here - https://opensearch.org/docs/1.2/security-plugin/configuration/openid-connect/#configuration-parameters

We also require a new configuration parameter that supports setting additional request parameters to the OpenID request.

For example, our internal OpenID provider expects us to pass additional request parameter "acr_values" with a particular value.

**Do you have any additional context?**
This is currently supported in AWS ALB OpenID connect feature as shown in below screenshot

<img width="418" alt="image" src="https://user-images.githubusercontent.com/32612787/184025684-a41c72ef-6a5c-4c05-b4d6-f8d37e55f13f.png">

**Comment by cwperks** [comment]
@HarshadRanganathan Thank you for filing this feature request. We would gladly accept a PR.

**Comment by samuelcostae** [comment]
I will start looking into this as it is the first on the TODO list

**Comment by samuelcostae** [comment]
@HarshadRanganathan  Can you please clarify if these additional parameters would be: 

1 - Fixed and shared for all users, specified  and configured by the admin in the Dashboards's configuration file. 
or
2-  If it is something that the each user would specify/type in the UI before logging in?

I believe it is the scenario 1, but would like to be confirm

**Comment by HarshadRanganathan** [comment]
> Fixed and shared for all users, specified and configured by the admin in the Dashboards's configuration file.

Yes - it will be scenario 1 stated above

**Comment by samuelcostae** [comment]
Hi @HarshadRanganathan  I'm working on these changes would like to check if my current solution does attend requirements

The opensearch_dashboards.yml config file will accept any number of parameters added under "opensearch_security.openid.additional_parameter"  for instance:

`
opensearch_security.auth.type: "openid"

opensearch_security.openid.connect_url: "http://localhost:8080/auth/realms/master/.well-known/openid-configuration"
opensearch_security.openid.client_id: "clientid"
opensearch_security.openid.client_secret: "secret"

opensearch_security.openid.additional_parameters.ping: "pong"
opensearch_security.openid.additional_parameters.fruit: "strawberry"
`

These parameters are added to the **get request** that is sent to the identity provider so the request would look like this

I believe  the identity provider expects the additional parameters to be sent on the get request, but was not able to confirm this (In case it expects it somewhere else like in the headers)

**Comment by peternied** [comment]
That looks like a solid design @samuelcostae I think the documentation should be updated so users can discovery this feature - can you create a documentation issue and PR for the documentation website?

**Comment by samuelcostae** [comment]
> That looks like a solid design @samuelcostae I think the documentation should be updated so users can discovery this feature - can you create a documentation issue and PR for the documentation website?

Issue for doc update https://github.com/opensearch-project/documentation-website/issues/5598 and PR pushed
