### ISSUE TITLE
[BUG] Tenant keeps switching to Global

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/security-dashboards-plugin#1084]
@sshock commented on [Wed Aug 24 2022](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2200)

**Describe the bug**

Throughout the day, maybe once an hour, while using OpenSearch Dashboards it will randomly switch me from the custom tenant I am on to the Global tenant.

**To Reproduce**
1. Switch to a custom tenant.
2. Click around to view different dashboards, maybe do refresh, or simply leave your browser open to a dashboard with auto-refresh enabled.

**Expected behavior**
It should stay on the tenant I have selected.

**Actual behavior**
It switches back to the Global tenant after a while.

**OpenSearch Version**
1.3.2

**Dashboards Version**
1.3.2

**Host/Environment:**
 - OS: macOS
 - Browser and version: Chrome 104.0.5112.101

**Additional context**

My suspicion is that the session is expiring and I am getting logged out.  I am told that sessions last 1 hour and I am being auto logged out and back in.

Even if that is what is happening, I expect it to be able to remember which tenant I am on.

---

@joshuarrrr commented on [Wed Aug 24 2022](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2200#issuecomment-1226407624)

@sshock Thanks for filing the bug - re-routing to the security plugin repo.

**Comment by mhoydis13** [comment]
I can confirm this behavior also happens in version 2.2.0 (oidc to Okta)

**Comment by sshock** [comment]
> I can confirm this behavior also happens in version 2.2.0 (oidc to Okta)

Interesting; I was just about to say that I tried this out in another environment that is upgraded to 2.2.0 and I haven't been able to reproduce the problem yet.

**Comment by mhoydis13** [comment]
> > I can confirm this behavior also happens in version 2.2.0 (oidc to Okta)
> 
> Interesting; I was just about to say that I tried this out in another environment that is upgraded to 2.2.0 and I haven't been able to reproduce the problem yet.

My understanding of what's going on here is that it's specific to certain oidc providers.  The session is expiring - within opensearch-dashboards and/or the security plugin, and after reauthentication, the user is landing in a different tenant and page.  My understanding is that it works with Keycloak, but try it with Okta and I think you'll be able to reproduce the session expiring at 60min no matter what you do.

**Comment by sshock** [comment]
Update: we are using Okta and strangely the problem is not showing up in one environment, but in another environment the problem is still happening, even after upgrading from 1.3.2 to 2.2.0.
