### ISSUE TITLE
[BUG] REST API not returning user password hash

### ISSUE THREAD

**Issue by ryouthere** [opensearch-project/security-dashboards-plugin#1086]
API not returning user password hash. After creating a new user (either via REST api or from the graphical interface), i was expecting the REST api endpoint `/_plugins/_security/api/internalusers/<username>`  to be returning the hash of the password, instead it always returns an empty string, see screenshots below: 
]
![image](https://user-images.githubusercontent.com/29649428/186673620-a123edad-dc0b-451a-8ad5-e2545bb912e0.png)
![image](https://user-images.githubusercontent.com/29649428/186673686-effe30c7-9624-4ed4-88f2-75f0b9866ba8.png)

I don't know if this is a feature or a bug to be honest.

I have a React app using opensearch + a flask backend. I wanted to use the internal database of opensearch security plugin (to take advantage of the user administration interface) to pull the user credentials from flask but since i cannot get the stored password or hash... is there another way/endpoint meant for this feature?

**Comment by peternied** [comment]
The response for the created user looks correct, as per the documented [[link](https://opensearch.org/docs/latest/security-plugin/access-control/api/#create-user)] .

It is not good practice to transmit security information like password hashes on a response of a user creation.  This can create security vulnerabilities that are best avoided completely. 

If you have a scenario that needs this kind of information please use our support forum to ask questions about a recommended pattern.  https://forum.opensearch.org/c/security/3
