### ISSUE TITLE
[BUG] 'admin' can't see Security tab in GUI

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/security-dashboards-plugin#1092]
@pragmatic3 commented on [Tue Sep 06 2022](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2275)

**Describe the bug**

The 'admin' user cannot see the security plugin listed under the 'OpenSearch Plugins' list in the GUI.

**To Reproduce**
1. Go to 'triple bar drop down menu'
2. Look under 'OpenSearch Plugins'
3. Note that Security is not listed

**Expected behavior**
Expected to see Security listed to be able to manage user, roles, etc.

**OpenSearch Version**
Please list the version of OpenSearch being used.
opensearch-2.2.1-1.x86_64

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
opensearch-dashboards-2.2.1-1.x86_64

**Plugins**
Please list all plugins currently enabled.
alertingDashboards@2.2.1.0
anomalyDetectionDashboards@2.2.1.0
customImportMapDashboards@2.2.1.0
ganttChartDashboards@2.2.1.0
indexManagementDashboards@2.2.1.0
notificationsDashboards@2.2.1.0
observabilityDashboards@2.2.1.0
queryWorkbenchDashboards@2.2.1.0
reportsDashboards@2.2.1.0
securityDashboards@2.2.1.0

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: RHEL 8.6
 - Browser and version [e.g. 22]  Chrome 105.0.5195.102 on Win 10

**Additional context**

**Comment by joshuarrrr** [comment]
Moved to security plugin repo for further investigation

**Comment by peternied** [comment]
@joshuarrrr I'm closing this issue out, the original filer won't be able to get notifications on this issue.  We can avoid this by doing a `transfer issue` in the bottom left, if you don't have the permissions to do this, please mention @.opensearch-project/transfer-request [[team](https://github.com/orgs/opensearch-project/teams/transfer-request)] so they can move the issue for you.
