### ISSUE TITLE
[BUG] nextUrl is not using basePath or base_redirect_url in OpenID authentication

### ISSUE THREAD

**Issue by guillaumeldc** [opensearch-project/security-dashboards-plugin#1098]
**What is the bug?**
When logging in using base_redirect_url (e.g https://my-domain/basePath/), the redirection after successful login is done to "/" instead of base_redirect_url. When adding /app/home/ to initial login request  (e.g. https://my-domain/basePath/app/home), the redirect is done properly.

**version**
Opensearch 2.2.1

**How can one reproduce the bug?**
Configure opensearch and opensearch dashboards instance to use openid and use a proxy such as nginx to add the params:
server.basePath: "/yourbasepath"
server.rewriteBasePath: true

Try logging in using the base url (e.g https://mydomain/yourbasepath). 

**What is the expected behavior?**
If not request.query.nextUrl then we should redirect to base_redirect_url and if base_redirect_url is None then we redirect to "/".

Potential correction:
[/server/auth/types/openid/routes.ts
line](https://github.com/opensearch-project/security-dashboards-plugin/blob/7e4b6c3e33b25300d7693fd1a1fbae8227710772/server/auth/types/openid/routes.ts#L107)

should be:
`nextUrl: request.query.nextUrl || getBaseRedirectUrl(this.config, this.core, request) || '/'`

**Comment by peternied** [comment]
[Triage] Thanks for filing

**Comment by RyanL1997** [comment]
linking issues #1099 and https://github.com/opensearch-project/security/issues/2095

**Comment by prathaptce** [comment]
when can we expect a fix for this issue?

**Comment by cwperks** [comment]
@prathaptce A fix for this issue is included in the 2.5.0 release.

**Comment by cwperks** [comment]
Closing this issue as https://github.com/opensearch-project/security-dashboards-plugin/issues/926 was merged.
