### ISSUE TITLE
Issue in Opensearch dashboards redirection as it is not considering basePath or base_redirect_url after OpenID authentication

### ISSUE THREAD

**Issue by pratikshavyas** [opensearch-project/security-dashboards-plugin#1099]
**What is the bug?**
On access of opensearch dashboards v2.2.1, Redirection is not considering value set for basePath and opensearch_security.openid.base_redirect_url as it is redirecting to "/" after authentication with openid.

**How can one reproduce the bug?**
Configure opensearch dashboard v2.2.1 to use openid authentication and also server.basePath: "/yourbasepath" 
Try to access the GUI

**What is the expected behavior?**
After successful openid authentication, redirection url should include basePath in it.

**What is your host/environment?**
 - Opensearch Dashboards Version : v2.2.1
 - Security Plugins: v2.2.1.0

**Comment by RyanL1997** [comment]
Tracking related issue: #1098 and closing this.
