### ISSUE TITLE
Kibana enable to login with wrong credentials

### ISSUE THREAD

**Issue by cde0** [opensearch-project/security-dashboards-plugin#110]
I Upgrade from 7.1.0 to 7.2.1 and i can login with wrong credentials, also correct and wrong credentials is the same permission. I tried with ldap and local credentials same behaviour.

Elasticsearch is authenticate correct.

When i run this on elastic
:9200/_opendistro/_security/kibanainfo  it return the correct info from ldap.

Linux: Ubuntu 18.04.2 LTS
Elastic version:
elasticsearch-oss  7.2.1             
opendistro-security                         1.2.1.0-0      
opendistroforelasticsearch                  1.2.1-1 

kibana.yml:

`elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opendistro_security.allow_client_certificates: true
opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]
opendistro_security.multitenancy.enable_filter: true
`

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
