### ISSUE TITLE
[FEATURE] Make Clickable "Switch tenants" and "Log out" links full width to make them more consistent and easier to click

### ISSUE THREAD

**Issue by jgough** [opensearch-project/security-dashboards-plugin#1111]
I'm always frustrated when switching tenants with the _Switch tenants_ or clicking the _Log out_ link.  The clickable area is fairly small and usability could be improved by making the link full width.  This would bring it into line with most other UI elements in Dashboards which have full-width links.

Note the link does not extend to the mouse location here:
![image](https://user-images.githubusercontent.com/968442/192234742-95d19f27-c92c-4495-9d8f-a84659c672be.png)

Usability could be improved by making the button width:100%:
![image](https://user-images.githubusercontent.com/968442/192235250-398cf07a-d123-4676-91fd-2eb10c3f90e6.png)

Compare to the links in the side-bar which have a full width link:
![image](https://user-images.githubusercontent.com/968442/192236033-a9ad513c-4eb7-49a7-8d19-4633d95c8d5c.png)

**Comment by RyanL1997** [comment]
Thank you for filling this. We will take a look at this.

**Comment by shanilpa** [comment]
Thanks for submitting this issue @jgough.
Issue #1133 seems to point to the problem. The @.opensearch-project/security-team will look into this.

**Comment by davidlago** [comment]
Closing in favor of #1133
