### ISSUE TITLE
Build 7.4.2 success, but kibana-plugin install failure

### ISSUE THREAD

**Issue by wuyunfeng** [opensearch-project/security-dashboards-plugin#113]
I build 7.4.2 successfully with command:  ./build.sh 7.4.2 7.4.2 install, unfortunately when I install the target with `kibana-plugin install`, it fails with the below error message.

Attempting to transfer from file:///home/work/opendistro_security_kibana_plugin-1.2.0.0.zip
Transferring 57237270 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin opendistro_security [7.2.0] is incompatible with Kibana [7.4.2]"

Can someone help resolve this problem? it seems can not compile version higher than 7.2.0. very thanks.

**Comment by sheldonrong** [comment]
I think the error message explain itself. opendistro_security support UP TO 7.2.0 which is lower than the version you are installing.

**Comment by sujithvm** [comment]
@wuyunfeng The second param is the security plugin version (https://github.com/opendistro-for-elasticsearch/security).

You would have to do something like this 
`./build.sh 7.4.2 1.4.0.0 install`

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
