### ISSUE TITLE
Incorrect Element Types for Menu Container & Menu items 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security-dashboards-plugin#1133]
@shanilpa pointed out several potentially incorrect element types we are using:

Currently we are using EUIContextMenu and then EUIFlexItems for numerous menus i.e. the account navigation dropdown. The combination of these two elements is incorrect and leads to faulty UX.

Proposed: In situations where we require a contextual menu we should make use of [OUIContextMenu / EUIContextMenu](https://eui.elastic.co/v34.6.0/#/navigation/context-menu) as the container type and [OUIContextMenuItem / EUIContextMenuItem](https://eui.elastic.co/v34.6.0/#/navigation/context-menu) for nested list items. This combination preserves interaction and UX functionality for the component.

**Comment by scrawfor99** [comment]
@shanilpa, we are going to wait until you get a draft of the rest of the related design and then someone will tackle this along with your changes.

**Comment by davidlago** [comment]
Closing until more details are provided. Given the OUI ongoing efforts, this most likely will be tracked elsewhere.
