### ISSUE TITLE
[BUG] apache proxy based authentication

### ISSUE THREAD

**Issue by zakirpcs** [opensearch-project/security-dashboards-plugin#1153]
**Describe the bug**

I want to login into opensearch-dashboards through apache proxy. Is there any official documents for that? By the way i have been following https://opensearch.org/docs/latest/security-plugin/configuration/proxy/ this documents but its did not work for me. Also note that my opensearch-dashboards version is 2.2.0.

**Comment by scrawfor99** [comment]
[Triage] Hi @zakirpcs, thank you for filing this issue, I would encourage you to take a look at the forums over at https://forum.opensearch.org/c/security/3. You issue may already be addressed over there. 

If you still find yourself encountering an issue, please create another issue linking to this issue and specifying the specific error/logs you are encountering. Thank you.
