### ISSUE TITLE
[Maintenance] Enable CI Workflows to Re-use Setup Steps

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/security-dashboards-plugin#1156]
**Is your request related to a problem?**

The request comes from [a PR review comment](https://github.com/opensearch-project/security-dashboards-plugin/pull/1146#discussion_r1001149910). 

**What solution would you like?**

The request is about enabling different CI workflows to re-use [the setup steps](https://github.com/opensearch-project/security-dashboards-plugin/pull/1146#discussion_r1001149910). 

**What alternatives have you considered?**
No alternatives for now.

**Do you have any additional context?**
Github does not have reusable jobs at all. It has reusable workflow instead. But in order to re-use those setup steps, the steps need to be reusable.

**Comment by cwperks** [comment]
[Triage] @RyanL1997 Can you please update the issue with your findings?

**Comment by scrawfor99** [comment]
Is this info helpful? https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

**Comment by RyanL1997** [comment]
I have tried to build a reusable workflow for core setup (https://github.com/RyanL1997/security-dashboards-plugin/actions/runs/3330166123). Even the workflow can be reused, we cannot pass the up running server through the workflow.

**Comment by peternied** [comment]
Ryan you are write dependent workflows won't work, however, I think `action` will provide this functionality, checkout https://github.com/opensearch-project/security-dashboards-plugin/pull/1164 to see an example.
