### ISSUE TITLE
[Refactor] User Visible Texts Need to Support Internationalization/Translation(i18n)

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/security-dashboards-plugin#1161]
**What is the request?**
The title tells what this issue asks for. The request comes from a PR review comment that requires repo-wide refactoring: https://github.com/opensearch-project/security-dashboards-plugin/pull/1110#discussion_r1006998786

**Comment by cwperks** [comment]
[Triage] @cliu123 Please provide more information and an example for how to do i18n?

**Comment by cliu123** [comment]
The guidline is that all the user visible text on UI needs to support i18n, for [example](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/configuration/utils/tenant-utils.tsx#L225).

**Comment by peternied** [comment]
@cliu123 Could you please rewrite the description of this issue following the Bug Report or Feature Request template?  It is not clear to me how we know if this issue has been fixed or not.

**Comment by peternied** [comment]
[Triage] @cliu123 Could you please include details on how to accomplish this internationalization?  Is there documentation that describes how this is done or how it can be verified?

**Comment by RyanL1997** [comment]
Closing this one for lack of informations.
