### ISSUE TITLE
[BUG] Failed to register OIDC Routers with OpenSearch Dashboards Client

### ISSUE THREAD

**Issue by aoguan1990** [opensearch-project/security-dashboards-plugin#1163]
**What is the bug?**
OIDC authentication handlers failed to register with OpenSearch Dashboards (OSD) client randomly after OSD reboots. Due to this reason, OSD users will encounter  `Unauthenticated Exception`.

Issues is addressed along with [PR #1110](https://github.com/opensearch-project/security-dashboards-plugin/pull/1110)

**Comment by cwperks** [comment]
@aoguan1990 Can this ticket be closed?

**Comment by aoguan1990** [comment]
> @aoguan1990 Can this issue be closed?
@cwperks Thank you so much for following up on this issue. Issue is addressed by the PR #1110. So close it.
