### ISSUE TITLE
Access opensearch-security API in custom plugins?

### ISSUE THREAD

**Issue by j10ra** [opensearch-project/security-dashboards-plugin#1166]
Hello Team,

I’m trying to create a custom plugin in opensearch-dashboard. Is there away I call opensearch-security api within my custom plugin?

eg: fetch('_plugins/_security/api/account)

I need to check if current loggedin user has an “all_access” role and perform some operations (ui or serverside) or if there is a way I can tap into opensearch-security within my custom plugin?

opensearch-dashboard: 2.3.1

I tried dong this
![image](https://user-images.githubusercontent.com/3077983/198684772-b7242d5b-3117-4ea8-9cea-e2af8c6efad6.png)
Pretty much the same with what [security plugin](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/account/role-info-panel.tsx) is doing but I get 404

this one seems to work but I'm not sure if this should be the right way to to it?
![image](https://user-images.githubusercontent.com/3077983/198684890-ac19c1de-2cb2-420a-8f1e-6db9c2cfe2ee.png)

Thank you very much!

**Comment by peternied** [comment]
@j10ra When running OpenSearch Dashboards you'll have 2 servers running, one that is the 'backend' OpenSearch, the other that is the 'frontend' OpenSearch Dashboards.  Within your Dashboards plugin that first call hits the Dashboards endpoint and its associated APIs.

For the first version of the call, its being sent to the Dashboards APIs, and there is a registered route (no documentation) `/api/v1/auth/authinfo` that should give you what you need for your plugin.

```
GET http://localhost:5601/api/v1/auth/authinfo
{
    "user": "User [name=admin, backend_roles=[admin], requestedTenant=admin_tenant]",
    "user_name": "admin",
    "user_requested_tenant": "admin_tenant",
    "remote_address": "172.23.0.2:42616",
    "backend_roles": [
        "admin"
    ],
    "custom_attribute_names": [],
    "roles": [
        "own_index",
        "all_access"
    ],
    "tenants": {
        "global_tenant": true,
        "admin_tenant": true,
        "admin": true
    },
    "principal": null,
    "peer_certificates": "0",
    "sso_logout_url": null
}
```

That second call is relaying the request to the OpenSearch 'backend' instance via that console proxy, that works, but I'm not sure if that is the best practice, but it can be leverage for any of the documented API calls for security features. [1]


[1] https://opensearch.org/docs/latest/security-plugin/access-control/api/#account

**Comment by j10ra** [comment]
I tried calling "/api/v1/auth/authinfo" 
![image](https://user-images.githubusercontent.com/3077983/198692932-b46404dc-014b-4691-a225-3cdb048d5ac9.png)

Both a and b are 404

while c returns 200 it. it tags it as unsafe
```
Since this is an unsafe inline script, this code will not run
in browsers that support content security policy(CSP). This is
intentional as we check for the existence of __osdCspNotEnforced__ in
bootstrap.
```


I think I will just go ahead and use the console proxy for now.
Thank you @peternied!
