### ISSUE TITLE
Passing Integration tests CI on Windows

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security-dashboards-plugin#1171]
Cypress and Jests tests only run on ubuntu linux distribution, we should update these workflows to work on Windows too.  There its alot of shared setup via https://github.com/opensearch-project/security-dashboards-plugin/issues/1156 that can be centralized while this work is underway.

**Comment by peternied** [comment]
@scrawfor99 This work would greatly benefit from https://github.com/opensearch-project/security/issues/2207 being available

**Comment by scrawfor99** [comment]
@peternied The actions should be all set!

**Comment by peternied** [comment]
@scrawfor99 Thanks for your work making those actions generic, this work should be much easier since that has been done.

**Comment by peternied** [comment]
@ryanbogan Can you look into getting these tests running on Windows CI, should be much easier with the new job - I think you might already be tracking getting this done.

**Comment by peternied** [comment]
🥳
