### ISSUE TITLE
[Enhancement]SAML Authentication can not be enabled with Anonymous 

### ISSUE THREAD

**Issue by aoguan1990** [opensearch-project/security-dashboards-plugin#1173]
**What is the bug?**
A clear and concise description of the bug.

**How can one reproduce the bug?**
1. Enable the following feature flag in opensearch_dashboards.yml
`opensearch_security.auth.type: 'saml'`
`opensearch_security.auth.anonymous_auth_enabled: true`
2. Go to OpenSearch Dashboards: http://localhost:5601/
3. Got Internal Exception:
![image](https://user-images.githubusercontent.com/92183424/198406050-a5334b91-0ba5-4390-938d-aef07927e58d.png)

**What is the expected behavior?**
User is able to login as Anonymous and by SAML based external IDP.

**Comment by DarshitChanpura** [comment]
@aoguan1990 Would you need any help answering the question above?

**Comment by aoguan1990** [comment]
@peternied @DarshitChanpura Thank you so much for following up on this issue. Do you by any chance can reproduce this issue?

**Comment by peternied** [comment]
@aoguan1990 this issue has not been worked on AFAIK so we haven't attempted to reproduce - is there a pull request that allows SAML + anonymous auth over the break?

**Comment by scrawfor99** [comment]
[Triage] @davidlago could you follow up with @aoguan1990. Thank you!

**Comment by scrawfor99** [comment]
[Triage 2/6] Moving from "sprint backlog" to backlog.

**Comment by davidlago** [comment]
Closed by mistake, reopening.
