### ISSUE TITLE
[BUG] Documentation links in Dashboards security plugin don't deep link to the appropriate places

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/security-dashboards-plugin#1174]
**What is the bug?**
Throughout the security plugin in OpenSearch Dashboards external links to the OpenSearch documentation site only link to the homepage and do not deep link to the appropriate sections. This is a poor experience for users and asks them to navigate the docs site to find the appropriate section that will help them out.

**How can one reproduce the bug?**
1. Go to the Security Plugin in Dashboards and navigate to the Get Started section.
2. Click on the "Create config.yml" CTA
3. You are directed to the homepage of the docs site instead of the appropriate section under the security plugin

**What is the expected behavior?**
When a user clicks an external CTA in the security plugin meant to point them to the doc site it should deep link them to the appropriate documentation page not the homepage.

**What is your host/environment?**
 - OS: MacOS (Chrome)
 - Version: 2.3.0
 - Plugins: Security

**Do you have any screenshots?**

**Do you have any additional context?**
This seems to be an issue with all the links to documentation within the security plugin. It looks like they are being redirected to the homepage because we changed the structure of the docs site but I could be wrong.

**Comment by cwperks** [comment]
[Triage] Thanks for filing the issue @shanilpa ! This would make for a great first contribution.

**Comment by gaiksaya** [comment]
Hi,
This issue was tagged for 2.6.0.
Can you close it if it was resolved or tag is to be tracked for next iteration?
Thanks!

**Comment by cwperks** [comment]
Closing this issue. This was released in 2.6.0.
