### ISSUE TITLE
[BUG] can not run a release build of this plugin

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/security-dashboards-plugin#1175]
When running a release build of the security dashboards plugin on `main` I get the following:

`Error: Cannot find module '../../public/apps/configuration/utils/tenant-utils'`

**Comment by peternied** [comment]
@kavilla Can you revert the responsible change to get unblocked and then tag who made the change to get it reintroduced?

**Comment by kavilla** [comment]
@peternied i built it on 2.x but that doesnt have the most recent commit. @aoguan1990 @cliu123

**Comment by cliu123** [comment]
[The latest integration test](https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/3348609281/jobs/5547850215) passed. 
@kavilla Would you lease provide the pointer to the build/logs?

**Comment by cliu123** [comment]
The release build fails because some files in `/server` folder reference constants and functions that are declared in `/public` folder. Those constants and functions need to be moved to `/common` folder.

I'm working on a fix.

**Comment by cliu123** [comment]
@kavilla confirmed that PR https://github.com/opensearch-project/security-dashboards-plugin/pull/1184 unblocks the release build.

**Comment by cliu123** [comment]
created an issue to track the follow-up action items: https://github.com/opensearch-project/security-dashboards-plugin/pull/1169
