### ISSUE TITLE
[Proposal/Discussion] Regularly scheduled (bi-monthly? monthly?) open-to-the-public UX/UI input sessions

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security-dashboards-plugin#1176]
**Proposal**
In light of the success of the security & security-dashboards open-invitation weekly triage meetings, the security-dashboards repository contributors would like to start having open-to-the-public feature review meetings. 

Previously, the great designs of @shanilpa were commented on by some contributors but UX/UI seems an obvious area where greater attendance leads to an even better product. 

Please use this issue as a discussion for input and comments on the topic. 

I am tagging @RyanL1997 and @cliu123 who are the two most prominent security-dashboards contributors because their input is invaluable. Likewise, I am tagging @shanilpa again because he did a great job running the previous input meetings and hopefully would be willing to consider taking on the responsibility of helping to lead these meetings. 

**Do you have any additional context?**
For information about the weekly triage meetings and how they operate please visit: https://github.com/opensearch-project/security/pull/2164 (soon to be merged into the main repo code once the wording is right). While these UX/UI meetings will surely be different I think that we can use some of the same participation guidelines and mindset for these sessions.

**Comment by shanilpa** [comment]
Love this thanks for creating it @scrawfor99. I'd love to run these sessions! Totally agree there will be differences between the triage meeting, but we should be able to re-use some things from there. I'll keep this thread updated with my thoughts on how we can build this function out with UX and Research.

**Comment by scrawfor99** [comment]
Perfect, I look forward to hearing your ideas and please let me know how I can help and what you need to best be able to facilitate meetings that will ease your design load.

**Comment by krisfreedain** [comment]
Community team is up for supporting these efforts @cwperks @scrawfor99 - let's figure this out 😃

**Comment by scrawfor99** [comment]
Hi @krisfreedain, thank you for your support. Right now, we are waiting to hear from @shanilpa about what he would like out of these meetings since they are intended as a catalyst for his UX/UI planning. I am happy to help moderate and run the meetings once we know more about what Shanil would like to do, but do not want to sign him up for anything which would be unhelpful or not what he wants.

**Comment by peternied** [comment]
[Triage] Thanks for using this issue to discussion how / if we run these UX/UI meetings.  Lets keep this open until A) we decide to move in another direction or B) when we document the meeting(s)

**Comment by davidlago** [comment]
Closing as lack of action signals lack of interest. We can re-open if the desire to have these picks up again.
