### ISSUE TITLE
Kibana looses the dev console content after session expires

### ISSUE THREAD

**Issue by mariuszpala** [opensearch-project/security-dashboards-plugin#118]
Hi, we are using Open Distro with Kibana 7.2.1 (latest) with the security turned on. We noticed that once the timeout occurs and we need to login again, the whole dev console content (history) is lost . It used to work fine with version 6.8 and it works fine in standard ES Kibana, so it looks like something related with the security plugin. Any idea how to solve this issue?
Additionally when session expired the console shows some HTML content instead of a user friendly message.

![Dec-05-2019 10-39-10](https://user-images.githubusercontent.com/12190923/70263598-9780ad00-174b-11ea-8f72-767a80fc61d0.gif)

**Comment by mariuszpala** [comment]
It works fine when we just refresh the page with session still being active, when it expires, then the content is lost.

**Comment by karolbe** [comment]
I have the same problem, Kibana from ElasticSearch saves and restores the queries correctly, so seems like this is OpenDistro related issue.

**Comment by krzwalko** [comment]
I am using Kibana 7.3.2 with plugins from ODFE and have the same issue. Requests history in Dev tab is not stored when logged out and logged in again.

**Comment by ycyr** [comment]
The content of the console is stored in the local storage of your browser  (key  sense:editor_state) and  
it seems that the ODFE security plugin is clearing the local storage each time you logoff from kibana,

The function localStorage.clear() is called in the following files:

-[public/apps/login/login_controller.js]( https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/public/apps/login/login_controller.js)

-[public/apps/customerror/page_controller.js](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/public/apps/customerror/page_controller.js)

-[public/apps/multitenancy/multitenancy.js](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/public/apps/multitenancy/multitenancy.js)

-[public/services/access_control.js](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/public/services/access_control.js)

I've fixed this behavior with this dirty fix: 

- Remove localStorage.clear() from those files
- Run kibana --optimize.
- Restart kibana

**Comment by hardik-k-shah** [comment]
@zengyan-amazon / @sean-zheng-amazon  Can you please look into this issue? 

Related duplicate in Security repo: https://github.com/opendistro-for-elasticsearch/security/issues/385

**Comment by cr-solutions** [comment]
it is really annoying, if the dev tools are only per session and cannot be saved via the Kibana interface :-(

**Comment by JathinSanghvi** [comment]
+1

**Comment by jetpack93** [comment]
Is there a new solution for this? we have tried the steps below but our dev tool commands are still not saved after we leave the session.

**Comment by Tonysykes** [comment]
We are moving from ES licensed to OD 7. This is a major issue for me and my team members as we have got used to keeping our history of what we are doing in dev tools. This is causing us no end of frustration. Is this planned to be fixed any time soon as we go live with OD 7 more users will no doubt complain about this issue.

**Comment by thenom** [comment]
Could this issue be connected to this:

https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/214

If each session/kibana had a dedicated cookie then potentially this clean out would not be needed.

**Comment by BlackMetalz** [comment]
Up :(

**Comment by BlackMetalz** [comment]
> The content of the console is stored in the local storage of your browser (key sense:editor_state) and
> it seems that the ODFE security plugin is clearing the local storage each time you logoff from kibana,
> 
> The function localStorage.clear() is called in the following files:
> 
> -[public/apps/login/login_controller.js](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/public/apps/login/login_controller.js)
> 
> -[public/apps/customerror/page_controller.js](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/public/apps/customerror/page_controller.js)
> 
> -[public/apps/multitenancy/multitenancy.js](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/public/apps/multitenancy/multitenancy.js)
> 
> -[public/services/access_control.js](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/public/services/access_control.js)
> 
> I've fixed this behavior with this dirty fix:
> 
> * Remove localStorage.clear() from those files
> * Run kibana --optimize.
> * Restart kibana

Work for me. Thanks for this workaround :D

**Comment by abdalians** [comment]
+1

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
