### ISSUE TITLE
[FEATURE] Add new ml-commons transport actions

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/security-dashboards-plugin#1181]
**Is your feature request related to a problem?**
We build several new transport actions in ml-commons for 2.4 release. So we need to add them to constants list.

**What solution would you like?**
Add to constants file.

**What alternatives have you considered?**
like this PR https://github.com/opensearch-project/security-dashboards-plugin/pull/912

**Do you have any additional context?**
N/A

**Comment by peternied** [comment]
@ylwu-amzn It seems like this issue is for a pending pull request - we are happy to accept pull requests without issues associated with them so long as they capture the 'why' in their description.

**Comment by ylwu-amzn** [comment]
Oh, got it, I will publish a PR soon and explain why in PR description.
