### ISSUE TITLE
[BUG] Unstable performance of SAML integration test case in CI

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security-dashboards-plugin#1194]
**What is the bug?**
SAML integration test case is unstable during the CI run

**How can one reproduce the bug?**
By running the integration test in CI.

**What is the expected behavior?**
The performance of SAML integration test case should be more stable.

**What is your host/environment?**
Github Actions

**Do you have any screenshots?**
![Screen Shot 2022-11-03 at 12 48 35 PM](https://user-images.githubusercontent.com/109499885/199783398-d86551bc-96e2-4f51-aa7c-070f968ed890.png)

**Comment by peternied** [comment]
@RyanL1997 This looks like a duplicate of an issue I just opened - would you like to pick one that we use to track this issue and close the other one as a duplicate? https://github.com/opensearch-project/security-dashboards-plugin/issues/1193

**Comment by peternied** [comment]
Aside - I love that you immediately filed an issue on this test failure!

**Comment by RyanL1997** [comment]
Closing this now. Linking it to #1193 for tracking the same issue.
