### ISSUE TITLE
[Flaky Tests] Windows UTs Are Flaky

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/security-dashboards-plugin#1195]
**What is the issue?**
Windows UTs fail intermittently. It has to be re-run when fails to unblock PR merge. For example:
https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/3382915584/jobs/5618317617
https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/3387653176/jobs/5628673899

@peternied Would you please take a look?

**Comment by peternied** [comment]
> info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.7.tgz: ESOCKETTIMEDOUT".

This was a network blip, not much action we can take. 

There are some packages for NodeJS [1] that change the default behavior of `fetch`, we might be able to use on of these to augment the build into network infra in yarn - but this is out of my depth.  


[1] https://github.com/vercel/fetch

**Comment by peternied** [comment]
Note; registry.yarnpkg.com could be experiencing issues - so there might have been no way those builds could succeed

The timeout can be increased with `yarn install --network-timeout 600000` if you want to make an update [1] 

[1] https://stackoverflow.com/a/70857301/533057

**Comment by cliu123** [comment]
The Windows checks should be disabled until it gets stablized.

**Comment by cliu123** [comment]
The Windows checks should be disabled while we're exploring a way to stablize them.
