### ISSUE TITLE
[BUG] Unable to switch tenants when visiting copied links

### ISSUE THREAD

**Issue by jgough** [opensearch-project/security-dashboards-plugin#1204]
**What is the bug?**
When visiting non-short URLs from the "Share" button, it is impossible to switch tenants

**How can one reproduce the bug?**
1. In a cluster with more than one tenant, log into Dashboards
2. Go to a page such as Discover, then click at the top Share -> Copy link (do NOT select Short URL)
3. Open a new tab and visit the copied URL.  This should load as normal.
4. From the tenant switcher, choose a different tenant
5. Note that you are returned back to the tenant as specified in the URL and not taken to the URL of the tenant you selected

**What is the expected behavior?**
Expected to be taken to the new tenant chosen

**What is your host/environment?**
 - OS: Linux / Docker
 - Version: 2.3.0
 - Plugins: Security Plugin

**Comment by peternied** [comment]
[Triage] This is likely related to the current tenant being stored in the browsers local storage which does not work well for multi-browser scenarios

**Comment by peternied** [comment]
[Triage] This could also be because the url includes the specified tenant and is preventing the updated tenant from being picked.

**Comment by jgough** [comment]
Looks like this might be a dupe of https://github.com/opensearch-project/security-dashboards-plugin/issues/665 which was closed in favour of https://github.com/opensearch-project/security-dashboards-plugin/issues/123

**Comment by leanneeliatra** [comment]
Confirmed issue on opensearch v2.6.0

**Comment by stephensarabiasurion** [comment]
We have also experienced a likely-related issue, which I assumed was related to user storage as @peternied commented originally; just wanting to comment here to ensure this use case is also considered.

If the visited url successfully redirects to the new tenant, any currently open tabs on the old tenant become buggy. Specifically, search on the old tab will occasionally fail with 403 errors, leading users to believe the index has gone missing, when in fact the UI is attempting to search against the new tenant instead. 

This new tenant isn't always immediately reflected in the UI, until a user does a refresh of the page
