### ISSUE TITLE
[FEATURE] Visibility of current tenant

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/security-dashboards-plugin#1205]
**What is the bug?**
Tenancy if enabled is a central concept in OpenSearch Dashboards however visibility into the tenant a user is currently in is hidden within menus or a few clicks away. This experience is frustrating for new and frequent users and can lead to the creation of Dashboard objects in the wrong tenant or confusion when they are loaded into a default tenant.

Currently if I want to see which tenant I am in then switch a tenant I have too: 
1. Click the user icon in the top right
2. Notice the small text under the user role
3. Click the "switch tenant" CTA
4. Interact with the modal
5. Confirm

**What is the expected behavior?**
Due to the importance of tenancy as a concept in Dashboards this information should be more visible in the interface. For example, a part of the bread-crumbing or in the navigation header so users are always aware of the tenant they are in and can easily switch to another if they would like too. They should not have to look through menus or left to guess what tenant they are in.

Idea: Tenant as a fixed breadcrumb item - clicking it opens the tenant selection modal
![image](https://user-images.githubusercontent.com/113368824/201208874-970478e9-47aa-4c6a-8136-7a8fdd0d38fe.png)

**What is your host/environment?**
 - OpenSearch Dashboards Version: 2.3.0
 - Browser: Google Chrome

**Comment by davidlago** [comment]
Work to address this (and other) issues is being tracked here https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298
