### ISSUE TITLE
[FEATURE] Custom tenant descriptions in tenant selector

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/security-dashboards-plugin#1206]
**What is the bug?**
Currently in the tenant selector modal we provide descriptions for the private and global tenant but we don't provide those descriptions for the custom tenant. In the tenant creation flow we ask users to populate a description.

As a user I may have many custom tenants and sometimes the name of the tenant might not provide me enough context on what the tenant is used for. By providing the tenant description from the custom tenant flow we can help users make decisions and enter the right tenant faster.

Current UI
<img width="771" alt="image" src="https://user-images.githubusercontent.com/113368824/201367276-0c4af5b3-abf1-40ac-ac1c-9e39078445a3.png">

**What is the expected behavior?**
Show a description for a selected custom tenant that is pulled from the tenant creation process so I can get context on the tenant without having to click into it

UI update idea: Providing a description to a custom tenant
**This idea needs UX approval and validation**
![image](https://user-images.githubusercontent.com/113368824/201367814-3d2f01e0-1c3d-4144-bb33-47fcc6778988.png)

**What is your host/environment?**
 - Version: 2.3.0
 - Browser: Google Chrome

**Comment by davidlago** [comment]
Tenants's new incarnation is being discussed as part of the [Workspaces RFC](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4615). Closing this one to make sure we capture all the feedback in one place.
