### ISSUE TITLE
[FEATURE] Tenant and Role mapping flows are disjointed

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/security-dashboards-plugin#1207]
**What is the bug?**
To use multi-tenancy in OpenSearch Dashboards a user has to create a tenant and map roles to that tenant. Currently the role creation and tenant creation experiences are separate with no intuitive way for users to move from one to the other. For admin users this can be a frustrating, confusing, and click heavy experience. 

**How can one reproduce the bug?**
1. Go to the "Security Plugin"
2. Click on the "Tenants" submenu
3. Click on the "Create Tenant" CTA
4. Notice there is no mention of mapping a tenant

**What is the expected behavior?**
A user should be able to easily map roles to a tenant in the tenant creation flow.
A user should be able to easily create a tenant in the role creation / mapping flow.

**What is your host/environment?**
 - Browser: Chrome
 - Version: 2.3.0
 - Plugins: Security Plugin

**Comment by RyanL1997** [comment]
[Triaged] @shanilpa I will follow up with you to see if we can have a demo userflow on this one.

**Comment by davidlago** [comment]
Closing in favor of (and linking to) the new [Workspaces](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4615) effort.
