### ISSUE TITLE
[FEATURE] Setting a default tenant through OpenSearch Dashboards UI

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/security-dashboards-plugin#1208]
**Is your feature request related to a problem?**
Currently in OpenSearch Dashboards there is no way for users to set a default tenant via the UI. For admin users this could be a beneficial feature that allows them to control which tenant a user loads into when they login to OSD.

**What solution would you like?**
An intuitive and simple flow that allows admin users to select an existing tenant and make it a default.
Admin users should also have clear UI affordances that show them which tenant is currently set as the default.

**What alternatives have you considered?**
Making this a part of the tenant creation flow
Deep linking this on the getting started page of the security plugin

**Do you have any additional context?**
Currently this is possible through the API and modifications in the config file (@cliu123 please confirm).

**Comment by shanilpa** [comment]
Looks like issue https://github.com/opensearch-project/security-dashboards-plugin/issues/74 is related to this and has some good information

**Comment by RyanL1997** [comment]
[Triaged] @shanilpa Thanks for filing this request. I will follow up with you.

**Comment by davidlago** [comment]
Closing alongside #74
