### ISSUE TITLE
[FEATURE] Getting started page is confusing and could use improvements

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/security-dashboards-plugin#1209]
**Is your feature request related to a problem?**
Currently the getting started page for the Security Plugin provides valuable links to key parts of configuring security related things in Dashboards. However, this page is a little confusing and has several UX issues. There is also missing links to things like tenancy and configuring those.

Some noticed issues include:
1. Documentation links not going to the right place
2. Primary CTA and Secondary CTA usage is not consistent
3. Order in the image starts with step 2 but the list starts with one
4. No linking to tenancy yet this is a central concept

**What solution would you like?**
This page can be enhanced further to provide admins a clear process to setting up the security plugin and related security features in OSD

**Comment by RyanL1997** [comment]
@shanilpa Could you please provide more details on this one?

**Comment by shanilpa** [comment]
Sounds good - will be adding more info soon.

**Comment by davidlago** [comment]
Closing until more details about what a good change would look like here.
