### ISSUE TITLE
Kibana using SSL on the security-configuration page broken in OD 1.2.1 release using Debian

### ISSUE THREAD

**Issue by lancemitchell** [opensearch-project/security-dashboards-plugin#121]
I have clean installed opendistroforelasticsearch-kibana_1.2.1_amd64.deb on multiple “Ubuntu 16.04.4 LTS” host servers. All installations I am experiencing **the same MAJOR BLOCKER**.

After installing opendistroforelasticsearch-kibana (1.2.1), Unfortunately I am experiencing a blocker when opening the Kibana security-configuration page using the latest Chrome (v79.0.3945.79 - 64-bit) and Firefox (v71.0 - 64-bit) Browsers, reporting **"Refused to execute inline script because it violates the following Content Security Policy directive: “script-src ‘unsafe-eval’”** in browser console and causing required missing icons to administrate ES.
![image](https://user-images.githubusercontent.com/18689906/70693652-deaaf880-1c8b-11ea-9a06-6c6f14ddcd09.png)

Examination of the broken page source shows the error message **“This Kibana installation has strict security requirements enabled that your current browser does not meet.”** while the Browser console reports invalid 404 URLs
```
GET https://mobile.spartansense.com:5601/app/{{actionGroupsSvgURL}} 404 (Not Found)
GET https://mobile.spartansense.com:5601/app/{{tenantsSvgURL}} 404 (Not Found)
GET https://mobile.spartansense.com:5601/app/{{internalUserDatabaseSvgURL}} 404 (Not Found)
GET https://mobile.spartansense.com:5601/app/{{rolesSvgURL}} 404 (Not Found)
GET https://mobile.spartansense.com:5601/app/{{roleMappingsSvgURL}} 404 (Not Found)
GET https://mobile.spartansense.com:5601/app/{{purgeCacheSvgURL}} 404 (Not Found)
GET https://mobile.spartansense.com:5601/app/{{authenticationSvgURL}} 404 (Not Found)
```
All these issues with trying to configure ES using the Kibana configuration page makes OD 1.2.1 release unusable.
My kibana.yml is as follows
```
server.port: 5601
server.host: "mobile.spartansense.com"
server.name: "mobile.spartansense.com"
elasticsearch.hosts: ["https://help.spartansense.com:9200"]
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
elasticsearch.ssl.certificate: /etc/kibana/ssl/mobile.spartansense.com.crt
elasticsearch.ssl.key: /etc/kibana/ssl/mobile.spartansense.com.key
elasticsearch.ssl.certificateAuthorities: [ "/etc/kibana/ssl/mobile.spartansense.com.ca.crt" ]
elasticsearch.ssl.verificationMode: full
opendistro_security.allow_client_certificates: true
opendistro_security.multitenancy.enabled: false
opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
server.ssl.enabled: true
server.ssl.certificate: /etc/kibana/ssl/mobile.spartansense.com.crt
server.ssl.key: /etc/kibana/ssl/mobile.spartansense.com.key
logging.dest: /var/log/kibana.log
csp.strict: true
```
I am not sure if the issue is faulty browser detection, but I am using the latest Firefox and Chrome browsers, so not sure why its blocking me from using the configuration page with Content Security Policy errors.
![image](https://user-images.githubusercontent.com/18689906/70693857-48c39d80-1c8c-11ea-8749-405c5d314d5b.png)
![image](https://user-images.githubusercontent.com/18689906/70693883-524d0580-1c8c-11ea-9a48-08f161cfe7cf.png)
![image](https://user-images.githubusercontent.com/18689906/70693891-5b3dd700-1c8c-11ea-8b9c-5d9527e9962c.png)
Finally,
- I am logged in as the default administrator account **admin / admin**, so I should have privileges to see the configuration page
- I have the configuration **opendistro_security.restapi.roles_enabled: [“all_access”, “security_rest_api_access”]** in _elasticsearch.yml_ on all my cluster nodes so I should be using the right user roles.

Any help with workarounds would be much appreciated

**Comment by pavbha04** [comment]
Sorry about that. We are planning to release 1.3 by Wed the latest and it has been keeping us busy. Let me work with our engineer today. Hope to respond by tomorrow am PST.

**Comment by lancemitchell** [comment]
OK Thanks. 
The incomplete Kibana security-configuration page, seems to manifest when client-side SSL is enabled: **"server.ssl.enabled: true"**. I hope they test this in release 1.3.0.  Its a critical feature for security-aware implementations. My goal is to get SAML implemented so, **SSL is CRITICAL**.

**Comment by tclin1023** [comment]
Hi @lancemitchell ,
Can you make sure you log in with admin user?
In order to see the configuration page, your CN=mobile.s... user should have admin backend role.

**Comment by lancemitchell** [comment]
Hello @tclin1023 . 
I can guarantee that I am logged in as admin user. 
The fact that admin does not show on the right is another symptom of the Kibana SSL bug, where Kibana does not recognize the logged in user privilege and shows the broken configuration page.

Try logging in yourself using **admin /admin** at my test Kibana installation
https://mobile.spartansense.com:5601/app/security-configuration#/
You will see

**Comment by tclin1023** [comment]
> Hello @tclin1023 .
> I can guarantee that I am logged in as admin user.
> The fact that admin does not show on the right is another symptom of the Kibana SSL bug, where Kibana does not recognize the logged in user privilege and shows the broken configuration page.
> 
> Try logging in yourself using **admin /admin** at my test Kibana installation
> https://mobile.spartansense.com:5601/app/security-configuration#/
> You will see

Hi @lancemitchell ,

The site cannot be reached. https://mobile.spartansense.com:5601/app/security-configuration#/

**Comment by lancemitchell** [comment]
https://mobile.spartansense.com:5601/ is very reachable and very public.
Look at the screenshots above
Here is another screenshot
I would suggest you check your browser settings
![image](https://user-images.githubusercontent.com/18689906/71044243-29e76000-20ff-11ea-84e6-f0d564b0d058.png)

**Comment by tclin1023** [comment]
Hi @lancemitchell ,

The error message that you inspected showed in previous versions as well. It does not block you from using the configuration page. I have tested admin /admin at OD 1.2.1 debian package with SSL enabled. The security configuration page and login user name work fine at my end.
Here is my configuration kibana.yml
```
server.name: kibana
server.host: "0"
elasticsearch.hosts: https://localhost:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/opendistroforelasticsearch.example.org.cert
server.ssl.key: /usr/share/kibana/config/opendistroforelasticsearch.example.org.key
```
Could you provide detail instructions for us to reproduce your issue?

**Comment by lancemitchell** [comment]
OK @tclin1023,

1. Did you not login to https://mobile.spartansense.com:5601/ and see the issue for yourself. Its real and it exists as I have proven with my screenshots and test login..donno what more I can do to prove this blocker.  But the fact that you can't acknowledge there is an issue is disturbing.

2. I have experienced this issue installing OD 1.2.1 debian on 3 separate Ubuntu 16.04.4 LTS hosts using the steps below
```
wget -qO - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch | sudo apt-key add -
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.2.1-amd64.deb
apt install opendistroforelasticsearch-kibana
touch /var/log/kibana.log
[copy mobile.spartansense.com SSL certs] to /etc/kibana/ssl
systemctl enable kibana
vi /etc/kibana/kibana.yml [Configuration included earlier in Issue]
systemctl start kibana
```

I don't know what more I can give you ??

**Comment by davidlago** [comment]
Closing as this pertains to an old version of ODFE and now ODFE is EOL. If the issue is still present with OpenSearch please open a new issue for it. Thanks!
