### ISSUE TITLE
[FEATURE] Disable private tenants through UI

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/security-dashboards-plugin#1210]
**Is your feature request related to a problem?**
Currently the private tenant can not be disabled in OpenSearch Dashboards. Some users may not require the benefits offered by a private tenant and therefore should have the option to disable this tenant type.

**What solution would you like?**
A clear an intuitive experience for users to disable the private tenant type in dashboards via the UI

**Comment by RyanL1997** [comment]
@cliu123 Could you please follow up and share you opinions on this request?

**Comment by cliu123** [comment]
The settings to enable/disable private/global tenants are static settings. User can change the settings only in yml file. Exposing the settings to UI would require to make the settings dynamic.

**Comment by peternied** [comment]
While this is a good user facing feature in terms of the security plugin, I don't think the security plugin is the correct place to make this change.  There should be a shared mechanism for dashboards to modify these 'yml file' changes

@shanilpa During triage you mentioned there was an 'administration' workstream to that might tackle scenarios like this.  Could you link this issue to that effort so features like this are easier to build.
