### ISSUE TITLE
Backport Windows support to 1.x branch

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security-dashboards-plugin#1235]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/181, backport Windows support to 1.x branch.

### Critical Path
- [x] Increment to 1.3.7
- [ ] Double check git log to ensure no features were missed
- [x] Build on windows machine
- [x] Run CI on Windows
  - [x] JDK 11
  - [ ] JDK 14
  - [x] JDK 8
- [ ] Integration tests on windows https://github.com/opensearch-project/security-dashboards-plugin/issues/1171

**Comment by scrawfor99** [comment]
[Triage 2/6] @RyanL1997 would you be able to backport the PR's you made to main and 2.x? Could you also close this issue when you finish? Thank you.

**Comment by cwperks** [comment]
Closing as associated PR was merged.
