### ISSUE TITLE
[FEATURE] Provide login options for anonymous use case

### ISSUE THREAD

**Issue by anubisg1** [opensearch-project/security-dashboards-plugin#1236]
**What is the bug?**
When anonymous authentication is enabled, a user accessing the dashboard is automatically logged in as anonymous.
In order to properly sign in, a user needs to first log out as anonyous, then he can login properly with his/her own credentials

**How can one reproduce the bug?**
1. enable anonymous authentication and another authentication like basic
2. access the dashboard, the user is automatically logged in as anonymous

**What is the expected behavior?**
This screen should be displayed and no auto-login should occur

![image](https://user-images.githubusercontent.com/4518931/205275846-23b69951-58c5-4197-9d87-fe013d9643d4.png)

Notice, that the button is already displayed today when multiple_auth is enabled, but if no, then "login as anonymous" button doesn't exist.

autologin occurs in all situations 

**What is your host/environment?**
 - OS: kubernetes
 - Version 2.4.0
 - Plugins - default installed by kubernetes operator

**Suggested fix**

Always consider anonymous login as an additional auth type in order to always display the button and do NOT autologin

**Comment by aoguan1990** [comment]
@anubisg1 As per discussion on the [forum](https://forum.opensearch.org/t/anonymous-user-multiple-authentication/11577), this is an expected behavior for now. As you just enabled basic authentication along with anonymous login, it means you only enabled single authentication option. In single authentication mode, `Login as Anonymous` button is not available. If you need this feature for single authentication mode, please reach out the maintainer @RyanL1997 to transfer this issue to a feature request.

**Comment by anubisg1** [comment]
Hello,

To be clear, what I opened as big here is "anonymous user is automatically logged in when a user opens the dashboard".

If even that is an expected behavior (and I can't understand why it would be), then it's a feature request, if it's not expected behavior, then it's a bug report.

**Comment by aoguan1990** [comment]
> Hello,

@anubisg1 `"anonymous user is automatically logged in when a user opens the dashboard"` is an expected behavior.

**Comment by RyanL1997** [comment]
Hi @anubisg1, thank you for providing more informations! I'm changing this issue to a "feature request".

**Comment by davidosorno** [comment]
@RyanL1997 I'd like to start working in this, please assign it to me and let me know if you have more information about it.

**Comment by derek-ho** [comment]
@DarshitChanpura closing this as part of your current work.
