### ISSUE TITLE
[BUG] Index template `tenant_template` is overriden by customer index template

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/security-dashboards-plugin#1246]
**What is the bug?**
The security-dashboards-plugin creates an index template `tenant_template` for `.kibana*` indices without setting an order(priority), so the order is `0` by default, which is the lowest priority. When users create a custom index template that applies to index pattern`*`(all indices including `.kibana*` indices), the custom index template overrides the plugin created index template, so the mappings of `.kibana*` indices are overridden too.
When this issue happens, if users create a custom tenant and create saved objects in the tenant, those saved objects are not visible to any users including admin users. The reason is that OSD cannot find the saved objects with wrong mappings.

**How can one reproduce the bug?**
1. Create a custom index template:
```
PUT _template/custom_template
{
  "index_patterns": ["*"],
  "mappings" : {
      "properties" : {
        "type" : {
          "type" : "text"
        }
      }
    }
}
```
2. Create a tenant
3. Create a saved object in the tenant
4. This is when the issue comes out. Users cannot see the save objects.

**What is the expected behavior?**
The saved objest is visible to users.

**Comment by peternied** [comment]
Resolved by #1247
