### ISSUE TITLE
Kibana Customization - Cannot replace icons that have euiIcon class

### ISSUE THREAD

**Issue by abhijithb92** [opensearch-project/security-dashboards-plugin#125]
I am trying to use custom brandings and I could replace quite a lot of assets but I am not able to change the Kibana icons that appear at places where euiIcon or related classes are used.

**Comment by abhijithb92** [comment]
@dhanesh95 please do follow this.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
