### ISSUE TITLE
Change the distribution build version back to 'latest' in CI workflow

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security-dashboards-plugin#1271]
### Description
Currently for adapting the new changes of dependencies in core, we are using a new distribution build in our CI workflow [1]. Once the 'latest' build gets updated, we need to change the build version in CI workflow back to 'latest'.

### Related PR
* Related https://github.com/opensearch-project/security-dashboards-plugin/pull/1269

### Reference
[1] : https://build.ci.opensearch.org/job/distribution-build-opensearch/6705/

Fix: Replace the build number with `latest` once the stable build is available

**Comment by cwperks** [comment]
Run a HEAD request to see what build number `latest` resolves to:

```
curl --head https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-3.0.0.0.zip
HTTP/2 302
content-length: 0
server: CloudFront
date: Mon, 19 Dec 2022 20:38:44 GMT
location: /ci/dbc/distribution-build-opensearch/3.0.0/6708/linux/x64/tar/builds/opensearch/plugins/opensearch-security-3.0.0.0.zip
cache-control: max-age=3600
x-cache: Hit from cloudfront
via: 1.1 42da47d5828a8cbe9a05fbe7917a66c2.cloudfront.net (CloudFront)
x-amz-cf-pop: IAD55-P3
x-amz-cf-id: VEchzcu_yfr0zS6nZpbZBROKKo6T0v-VSfCMKi92oOGmP2dPpsqaiQ==
age: 43
```
