### ISSUE TITLE
[BUG] Index patterns not loaded after creation of the index template for all indices pattern "*"

### ISSUE THREAD

**Issue by deepak-rsystems** [opensearch-project/security-dashboards-plugin#1284]
**Describe the bug**

If we load an index template for all indices "*" pattern (before dashboards pod starts and is up) with following template settings, indices patterns are not loaded anymore and saved objects are also not visible anymore and we get "Unable find saved objects" error on screen.

`"template" : {
          "settings" : {
            "index" : {
              "routing" : {
                "allocation" : {
                  "include" : {
                    "role" : "data"
                  }
                }
              },
              "refresh_interval" : "30s"
            }
          }
        }`

We checked that problem is caused by the fact that .kibana* system indices are getting the all indices index template applied and has template setting for routing allocation.
`".kibana_1" : {
    "settings" : {
      "index" : {
        "routing" : {
          "allocation" : {
            "include" : {
              "role" : "data"
            }
          }
        },
        "refresh_interval" : "30s",
        "number_of_shards" : "1",
        "auto_expand_replicas" : "0-1",
        "provided_name" : ".kibana_1",
        "creation_date" : "1668430185144",
        "number_of_replicas" : "1",
        "uuid" : "sPO3PtfcRC2DVn_ynIcl_A",
        "version" : {
          "created" : "136247827"
        }
      }
    }
  }`

**To Reproduce**
1. Go to Saved Objects
2. See error
![saved-objects-missing](https://user-images.githubusercontent.com/60732633/201940954-ff79c93b-e0ca-4268-a556-e5ce23ad635c.png)

3. But it seems, the saved object config is present there but not visible by default:

<img width="775" alt="saved-objects-missing1" src="https://user-images.githubusercontent.com/60732633/201941237-9ca3bab7-8458-4d97-893d-841423d6138f.png">

4. And if we create an index pattern, it doesn't get saved. 
5. We also noticed that, if we restart the dashboards pod, then dashboards gui starts to work fine!!

**Expected behavior**
Opensearch dashboard functionality should not be impacted due to index allocation routing on .kibana* system indices.

**OpenSearch Version**
2.3.0

**Dashboards Version**
2.3.0

**Plugins**

No custom plugin enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by scrawfor99** [comment]
[Triage] @cwperks would you be able to take a look at this issue? Thank you!

**Comment by UXabre** [comment]
I checked this in 2.5.0 and it's the same behavior. I bombarded myself to admin because i hoped it might have something to do with that but to no avail.
It gets created though in a private / custom tenant but never visible, not even on api level.

**Comment by deepak-rsystems** [comment]
Hi @opensearch-project/security-dashboards-plugin team,
Could you please let us know, what is the plan for this ticket?
Any fix planned? If yes, in which release?

**Comment by deepak-rsystems** [comment]
Hi @opensearch-project/security-dashboards-plugin team,
Could you please let us know, what is the plan for this ticket?
Any fix planned? If yes, in which release?

**Comment by scrawfor99** [comment]
Hi @deepak-rsystems, I am taking a look at this in between some other work. I am still in the early steps but would expect this certainly to be fixed by 2.14 (I did not get to it in time for the 2.13 code freeze). Sorry for the delay. I will update as I work on the issue.

**Comment by cwperks** [comment]
I have not been able to replicate this issue on 2.12.0.

[latest.zip](https://github.com/opensearch-project/security-dashboards-plugin/files/14748316/latest.zip)

I've added `node.attr.role: data` to `opensearch.yml` and startup the nodes before OSD. Before running OSD I run the request:

```
curl -XPUT -u "admin:admin" https://localhost:9200/_index_template/template_1 -k -H "Content-Type: application/json" --data '{
  "index_patterns": ["*"],
  "template": {
    "settings": {
      "index": {
        "routing": {
          "allocation": {
            "include": {
              "role": "data"
            }
          }
        },
        "refresh_interval": "30s"
      }
    }
  }
}'
```

Then bring up OSD and OSD can come up fine and create the .kibana indices. I can also create index patterns and see them on the saved objects screen.

**Comment by deepak-rsystems** [comment]
Hi @cwperks,

It seems the issue doesn't exist anymore and index template "tenant_template" has done the trick:

`$ curl -sk -u admin:admin -XGET "https://VIP:9200/_index_template/tenant_template?pretty" | head -20
{
  "index_templates" : [
    {
      "name" : "tenant_template",
      "index_template" : {
        "index_patterns" : [
          ".kibana_-*_*",
          ".kibana_0*_*",
          ".kibana_1*_*",
          ".kibana_2*_*",
          ".kibana_3*_*",
          ".kibana_4*_*",
          ".kibana_5*_*",
          ".kibana_6*_*",
          ".kibana_7*_*",
          ".kibana_8*_*",
          ".kibana_9*_*"
        ],
        "template" : {
          "settings" : {`

Not sure when this index template was added, but it seems to exist even in OS version 2.8.0.

Since this index template is targeted for kibana system indices and has a higher priority so it gets applied on kibana system indices which seem to have resolved the problem.

Thank you for the support and update.

**Comment by cwperks** [comment]
Thank you @deepak-rsystems . Marking this issue closed as its been resolved.
