### ISSUE TITLE
Create Global Index Pattern which should be visible to all Individual Tentants

### ISSUE THREAD

**Issue by divyankm** [opensearch-project/security-dashboards-plugin#1287]
**Is your feature request related to a problem?**
Currently, we have multiple tenants for example: `abc` , `xyz` , `ijk`. We are using `saved_object` api to create `index_pattern` by importing `ndson` file. We observed that tenant which was first created (`xyz`) is showing `index_pattern` when below api import ndjson file.

Only `xyz` tenant and `Global` showing the index pattern. But we want to show particular index pattern at global level (to all individual tenants as well).

API Request:
```
curl -XPOST -u <>:<> --insecure "https://< 
 >:<>/api/saved_objects/_import" -H "osd-xsrf: true" --form file=@"a.ndjson"
```

If we go with curl request by keeping importing ndjson file to each individual tenant , we have to perform multiple API request & no straight forward way to select tenants in api request. Even when new tenant gets created we will need to run individual API request.

Ref Link: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1723 

**What solution would you like?**
I think just like `Global` Tenant, in security plugin if there is any way to make any particular index pattern which is currently present in `xyz` tenant, if we can make it `Global` as well for every tenants. same with `Vizualizations` & `Dashboards`. Some Viz & Dashboards may be used by all Tenants.

**What alternatives have you considered?**
Currently we are using saved_object api to import ndjson file to individual tenant, which is cumbersome.

**Do you have any additional context?**
Do let me know if Global Index pattern can be achieved in current version, may be I am missing some user roles configurations.

Ref link: https://forum.opensearch.org/t/create-global-index-pattern-accessible-to-all-tenants-in-opensearch/11971

**Comment by scrawfor99** [comment]
[Triage] @RyanL1997 if you could take a look at this issue alongside @shanilpa, that would be appreciated.

**Comment by jimishs** [comment]
Thanks for your feedback @divyankm . We have considered the ability to share objects between tenants. Once we support that, it will be available for index patterns, visualizations and all other saved objects. 

Tagging a few other in case they have additional updates @ahopp @cliu123

**Comment by davidlago** [comment]
Linking to (and closing in favor of) the [Workspaces](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4615) effort.
