### ISSUE TITLE
I am not able to map active directory distribution group to backend roles

### ISSUE THREAD

**Issue by rjagdale** [opensearch-project/security-dashboards-plugin#1293]
When I login to kibana, I get error as "No roles available for the user, please contact your system administrator". I have configured active directory distribution group for backend role. Does opensearch support distribution group or just security group. I have attached error snapshot. As per this link(https://www.elastic.co/guide/en/elasticsearch/reference/7.17/active-directory-realm.html) elastic search does not support distribution group is this same with opensearch as well.

![kibana_error](https://user-images.githubusercontent.com/7789691/211546658-e911e1c3-8325-46f7-88ac-08f52f0e9e8e.JPG)

**Comment by dblock** [comment]
What version of the software are you trying to run? This looks like Open Distro, which is ES < 7.10 + plugins, and ODFE is EOL for a while.

Please try on the latest OpenSearch, https://opensearch.org/?

**Comment by peternied** [comment]
Hi @rjagdale, thank you for filing this issue, I would encourage you to take a look at the forums over at https://forum.opensearch.org/c/security/3. You issue may already be addressed over there. 

If you still find yourself encountering an issue, please create another issue linking to this issue and specifying the specific error/logs you are encountering. Thank you.
