### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by horacimacias** [opensearch-project/security-dashboards-plugin#13]
Could you please provide build instructions from source?

**Comment by Seegras** [comment]
"mvn compile" (works) or "mvn package" (should afaik produce a jar? doesn't work for me):
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (plugin) on project opendistro_security_kibana_plugin: Failed to create assembly: Error creating assembly archive plugin: archive cannot be empty -> [Help 1]

**Comment by lukas-vlcek** [comment]
Interestingly, the [build instructions](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin#build) recommends using:
```
./build.sh <es-version> <kibana-version> install
```
However, in the source code [build.sh](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/1a3ed3149774a6f0a00ae0712c229e872c9c3633/build.sh) the order of arguments is interpreted in different order. The meaning of arguments is:
```
./build.sh <kibana-version> <es-version> install
```
(Kibana version first, ES version second). Hmm...

**Comment by lukas-vlcek** [comment]
And there are more things that look odd to me. Like here:
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/1a3ed3149774a6f0a00ae0712c229e872c9c3633/build.sh#L126

IMO the `RPLC_PLUGIN_VERSION` string if not found in source and the `$SG_PLUGIN_VERSION` variable is not defined.

Here: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/1a3ed3149774a6f0a00ae0712c229e872c9c3633/build.sh#L134

The `release` maven profile is not defined.

This may be all valid in AWS build environment but not in my developer upstream setup.

**Comment by davidlago** [comment]
ODFE is EOL'd, and there is new documentation covering building from source for OpenSearch [here](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/DEVELOPER_GUIDE.md)
