### ISSUE TITLE
[BUG] Backend roles section of Create User page allows blank backend role

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security-dashboards-plugin#1307]
**What is the bug?**

The user creation screen allows a user to continue to add backend roles even if no text is entered. In addition to creating blank roles, the remove button is always enabled even if no text is entered. If there is only one backend role, the remove button will blank out the text that has been filled. If there is more than one role then remove will remove the entire row. 

![Screen Shot 2023-01-23 at 10 24 00 AM](https://user-images.githubusercontent.com/17432265/214078288-b7c0087c-94ef-4179-91f7-8bd7dcb89452.png)

Blank backend roles do show up for the logged in user with a blank backend role:

![Screen Shot 2023-01-23 at 10 27 41 AM](https://user-images.githubusercontent.com/17432265/214079210-34609775-0468-4efe-bc43-2fabb62c3346.png)

**How can one reproduce the bug?**
1. Go to Security -> Internal Users
2. Create a User
3. Click on `Add another backend role`

**What is the expected behavior?**

The backend role should not be blank before a new one can be added

Tested on 2.5.0

**Comment by shanilpa** [comment]
Hey @cwperks good catch! 

This makes sense to me. We should add an error message to notify the user that they need to add a backend role before adding a new row.

Here's a UI mockup for reference: 
![image](https://user-images.githubusercontent.com/113368824/214139347-ec08f36f-34af-4bb7-a89b-cca0540c4a3a.png)

**Comment by nurSaadat** [comment]
Thank you @shanilpa for a nice mockup!
I'd like to work on this issue

**Comment by cwperks** [comment]
@nurSaadat Thank you for volunteering! I have set you as the assignee on this issue.

**Comment by nurSaadat** [comment]
Hello everyone!

Could you please explain how to document changes? Does it mean adding what was changed to CHANGELOG.md? (but I didn't find one)

**Comment by RyanL1997** [comment]
> Hello everyone!
> 
> Could you please explain how to document changes? Does it mean adding what was changed to CHANGELOG.md? (but I didn't find one)

Hi @nurSaadat, thank you for taking this on. For the general bug fixes without functionality/user behavior changes, we will only document PR in the next release notes, so don't worry about that :). In addition, the description section of your PR is a good place to document those details of this fix
