### ISSUE TITLE
SAML authentication not working when Kibana is using client certificate to connect to Elasticsearch

### ISSUE THREAD

**Issue by tocw** [opensearch-project/security-dashboards-plugin#131]
Hi, 
after upgraing from 1.1.0 to 1.2.0 I'm not able to use SAML authentication if certificate authentication for Elasticsearch is set up in kibana.yml. Here is my configuration:
```
server.name: kibana-1
server.host: "0"

elasticsearch.hosts: ["https://10.10.0.1:9200"]
elasticsearch.ssl.verificationMode: none
elasticsearch.ssl.certificateAuthorities: [ "/usr/share/kibana/config/ca.pem" ]
elasticsearch.ssl.certificate: /usr/share/kibana/config/cert.pem
elasticsearch.ssl.key: /usr/share/kibana/config/cert.key
elasticsearch.ssl.keyPassphrase: *****
opendistro_security.allow_client_certificates: true

elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver

opendistro_security.auth.type: saml
server.xsrf.whitelist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]

elasticsearch.requestHeadersWhitelist: ["securitytenant", "Authorization"]
opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.enable_global: false

logging.verbose: true
```

It works fine with basic auth, after commenting out the `elasticsearch.ssl.*` lines.

What I investigated so far is that [samlHeader](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/opendistro-1.2/lib/auth/types/saml/routes.js#L68) var is undefined if ssl is enabled which results in redirecting to `/customerror?type=samlConfigError` page

Any idea what may be the problem cause?

Thanks, 
Tom

**Comment by shawnz** [comment]
Do you have the saml authenticator configured with "challenge: true" in your opendistro security config.yml file in Elasticsearch, and everything before it has "challenge: false"?

**Comment by tocw** [comment]
Exactly, everything except SAML section has challenge property set to false

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
