### ISSUE TITLE
[FEATURE] Enable / Disable the Private Tenant through OpenSearch Dashboards Security Plugin

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/security-dashboards-plugin#1317]
## Context

**Is your feature request related to a problem?**
Currently the private tenant can only be enabled / disabled through YML configuration files. Configuring through these files is a complex and somewhat frustrating experience for admin users. In order to enhance the UX for configuring tenancy it would be nice to offer admin users a dynamic way to enable / disable the private tenant through OpenSearch Dashboards Security Plugin.

**Other context notes**
- By default the private tenant is the default tenant for all users if not specifically configured by the admin.
- Saved objects created in private tenants can not be accessed by other users.
- Saved objects created in the global tenant are accessible to all users.
- The global tenant can not be disabled

**Users / Personas**
- Admin - This is a user that has access to the security plugin and can configure tenancy. They can also use tenancy like a non-admin user would.
- Non-admin - These are users that do not have access to the security plugin, they can not configure tenancy but can use the feature if it is enabled and their admin has granted them appropriate permissions to do so.

## What solution would you like?
NB: These are design mockups. Some copy is placeholder and not all interactions are polished. 
Mockups may differ from the final launched feature.

### 1. Disable private tenant
- Admin users can disable the private tenant if tenancy is enabled through the configure tab.
- When the private tenant is disabled the default tenant for all users is set to the global tenant, however the user is able to change this to a custom tenant of their choosing.
- Friction is introduced to notify the user and force them to consider their decision

https://user-images.githubusercontent.com/113368824/220742136-fca5ec5b-9e66-477e-88d4-5ed41807bb3d.mp4

----

### 2. Non-admin user notification
- When the private tenant is disabled users working in a private tenant should be shown a persistent modal notifying them that the admin has disabled the private tenant 
- The non-admin user is prompted with a persistent modal that can not be cancelled out of.
- After a set amount of time they are redirected to the global tenant

![image](https://user-images.githubusercontent.com/113368824/217098184-95c8fbf0-2cca-45d2-9419-d2134dc6aa82.png)

If users try to access a tenant via a url that has been disabled they will be notified that they no longer have access
![image](https://user-images.githubusercontent.com/113368824/220742362-b711179a-8c3a-4d16-837a-94de8a7a63ff.png)

When non-admin users try and switch a tenant they do not see the private tenant option
![image](https://user-images.githubusercontent.com/113368824/217099927-b4c93ab0-a2c6-47ac-ac8f-2bb55019cff9.png)

## Additional Details
These UX improvements are based on work/tasks outlined in [this issue](https://github.com/opensearch-project/security-dashboards-plugin/issues/1302#issuecomment-1416653794) and [this RFC](https://github.com/opensearch-project/OpenSearch/issues/5853) for making tenancy dynamically configurable.

**Comment by scrawfor99** [comment]
[Triage] Assigning to @shanilpa for further development. Thank you!

**Comment by kgcreative** [comment]
@shanilpa - has this issue launched? If so, can we close it, referencing any merged PRs that resolve this?

see: https://github.com/opensearch-project/OpenSearch/issues/5853

**Comment by shanilpa** [comment]
This feature has launched: https://github.com/opensearch-project/security/pull/2607
