### ISSUE TITLE
Add auto github release workflow

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/security-dashboards-plugin#1324]
### Is your feature request related to a problem?
As part of OpenSearch releases, `opensearch-build` pushes a tag for the release commit.
But publishing a github release based on the tag is manual.

### What solution would you like?
We've added this workflow[1] in OpenSearch which publishes github releases automatically when a tag is pushed.

Add this workflow to all repos releasing software in the project.
See example: https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/auto-release.yml
Example Release: https://github.com/opensearch-project/OpenSearch/releases/tag/2.5.0

[1] https://github.com/opensearch-project/opensearch-plugins/blob/main/WORKFLOWS.md#auto-github-releases

**Comment by cwperks** [comment]
[Triage] @cwperks could you please take this issue?

**Comment by gaiksaya** [comment]
Hi @cwperks,
This issue was tagged for 2.6.0.
Can you close it if it was resolved or tag it to be tracked for next iteration?
Thanks!

**Comment by cwperks** [comment]
Closing as this was merged to main and removing 2.6.0 label as it does not need to be backported: https://github.com/opensearch-project/security-dashboards-plugin/pull/1339. The label was previously added since the PR was merged before the 2.6.0 release.

**Comment by saratvemulapalli** [comment]
@cwperks this change has to be backported to all release lines. Which is why 2.6 was not released in this repo.

**Comment by cwperks** [comment]
@saratvemulapalli I have drafted and published the releases manually. Thank you for the comment, backport PRs have been created in this repo and the security repo to add the auto-release workflow to the 2.x branch.
