### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security-dashboards-plugin#1326]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by scrawfor99** [comment]
Taking over for DC since I talked to Chang about maintainership already.

**Comment by scrawfor99** [comment]
All set!

**Comment by dblock** [comment]
You have the `plugins` with 8 members, and `security` with 7 members that have admin access to this repo. Only folks listed in MAINTAINERS/CODEOWNERS need to have _maintain_ access, and groups don't support external collaborators and therefore should be removed. Please work with an admin to remove the group, and add individuals.

**Comment by peternied** [comment]
I've reviewed and resolved all the outstanding permissions associated with this repo.

**Comment by dblock** [comment]
Verified, thanks.
