### ISSUE TITLE
[BUG] Anonymous user cannot change `Global` tenant

### ISSUE THREAD

**Issue by zhquan** [opensearch-project/security-dashboards-plugin#1336]
**What is the bug?**
The anonymous user `opendistro_security_anonymous` can only access the `Global` tenant. When I try to switch the tenant it still shows the `Global` tenant dashboards even if it says that the tenant is switched.

**How can one reproduce the bug?**

1. Activate anonymous in `config.yml`
```
config:
  dynamic:
    http:
      anonymous_auth_enabled: true
```
2. Activate anonymous in `opensearch_dashboards.yml`
```
opensearch_security.auth.anonymous_auth_enabled: true
```
3. Login using the `admin` user
4. Create a new tenant (`public`)
5. Map `opendistro_security_anonymous` to `all_access` role.
6. In the `Global` tenant add `[eCommerce] Revenue Dashboard` example data.
7. In the `public` tenant add `[Logs] Web Traffic` example data.
8. Logout
9. Go to https://locahost:5601/app/dashboards
10. Check that the user anonymous is in the `Global` tenant with `[eCommerce] Revenue Dashboard` dashboard

![image](https://user-images.githubusercontent.com/5637233/220132101-a2065756-9e86-4fc1-89d2-e27620f4ee9f.png)

11. Switch to `public` tenant and the dashboard is still `[eCommerce] Revenue Dashboard` instead of `[Logs] Web Traffic`
![image](https://user-images.githubusercontent.com/5637233/220135015-c641cd27-0da0-496d-b4d2-1b4716288349.png)

12. The same but using the `admin` user and we can see that in the `public` tenant the dashboard is `[Logs] Web Traffic`

![image](https://user-images.githubusercontent.com/5637233/220134726-6a602f39-9e00-4ced-a5a3-c66827d6592b.png)

**What is the expected behavior?**

I expect the anonymous user (`opendistro_security_anonymous`) to have the same behavior as `admin` user. In `step 11` the dashboard is `[Logs] Web Traffic`

**What is your host/environment?**
- OS: Ubuntu
- OpenSearch and OpenSearch Dashboards: `2.5.0` and the same behavior for all `2.x.y` and `1.x.y`

**Comment by cwperks** [comment]
[Triage] @cwperks would you take a look at this issue?

**Comment by sduenas** [comment]
We fixed this issue on: https://github.com/opensearch-project/security/pull/2459
The problem is related with the `security` plugin of OpenSearch.
