### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security-dashboards-plugin#1337]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the Security Dashboards repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Security Dashboards | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | Code Hygiene, Certificate of Origin, Plugin install  | https://github.com/opensearch-project/security-dashboards-plugin/issues/1337 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

I also do not see any check for auto-push of new tests to the functional testing repository. If this is present and I missed it could you please make a note below? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by peternied** [comment]
We are running tests from the functional test repro which I think is a 'requirement' for dashboards plugins.  I'm not sure we have a BWC framework for dashboards?

Maybe we could classify some of these repositories in a different way, e.g. backend-plugins should have XYZ vs frontend-plugins should have ABC requirements

@RyanL1997 Did you have more feedback you'd want to add before we close this out

**Comment by RyanL1997** [comment]
> We are running tests from the functional test repro which I think is a 'requirement' for dashboards plugins. I'm not sure we have a BWC framework for dashboards?
> 
> Maybe we could classify some of these repositories in a different way, e.g. backend-plugins should have XYZ vs frontend-plugins should have ABC requirements
> 
> @RyanL1997 Did you have more feedback you'd want to add before we close this out

Yes I think the cypress is the only one we need to mention up right here.

**Comment by scrawfor99** [comment]
Great, I will add these notes. Thank you both.
