### ISSUE TITLE
Index permissions should not be assigned to cluster permissions and vice versa

### ISSUE THREAD

**Issue by spapadop** [opensearch-project/security-dashboards-plugin#1347]
I know the following is not important, just a nice-to-have feature. I'm using the latest opendistro 1.13.2 version.

At the moment, one can assign index permissions (e.g. `indices_all`) to the cluster permissions tab within Kibana UI: Security > Roles > Edit role. 

Likewise, when defining index permissions, suggestions like `cluster_all`, `cluster_monitor`, etc. pop up in the drop-down list.

If I am not mistaken these cases do not make sense, thus it would be optimal that the auto-complete suggestions are relevant to the permissions one is trying to define i.e. only `cluster:*` permission (groups) for cluster permissions and only `indices:*` permission (groups) for index permissions.

Going one step forward, if user anyway enters the wrong group of permissions an error/warning should occur, letting him know that it doesn't make sense.

Please let me know if my suggestion is unclear.

**Comment by scrawfor99** [comment]
[Triage] This is a similar issue to #1346. These issues could be resolved at the same time and would make a good first issue.
