### ISSUE TITLE
[BUG] Setting basePath and auth.multiple_auth_enabled results in the wrong url in the UI

### ISSUE THREAD

**Issue by mattieserver** [opensearch-project/security-dashboards-plugin#1349]
**What is the bug?**
When you set the `server.basePath` to a custom path and also set the `opensearch_security.auth.multiple_auth_enabled` to true (with openid connect) you do not get the correct URL in the UI. The UI keeps the '/auth/openid/login' path instead of adding the custom prefix from  `server.basePath`. 

**How can one reproduce the bug?**
1. set the followin config options:
```
opensearch_security.auth.type: ['basicauth', 'openid']
opensearch_security.auth.multiple_auth_enabled: True
opensearch_security.ui.openid.login.buttonname: Login with Keycloak
opensearch_security.openid.connect_url: https://not_a_real_dns:8300/auth/realms/DEMO/.well-known/openid-configuration
opensearch_security.openid.base_redirect_url: https://not_a_real_dns:5601/dashboards
opensearch_security.openid.client_id: opensearch-dashboards
opensearch_security.openid.client_secret: XXXXXXXXXXXXXXXXXXXXXXX
server.basePath: /dashboards
server.rewriteBasePath: True
```
2. Go to the login page and inspect the 'login with keycloak' button
![image](https://user-images.githubusercontent.com/3049868/221140138-ed33de18-c637-4d38-9037-4f95619d47e4.png)

**What is the expected behavior?**
The href for the openid login should include the basePath.

**What is your host/environment?**
 - OS: Ubuntu 20.04
 - Version 2.5.0 (docker)

**Do you have any screenshots?**
Yes, see in the reproduce steps.

**Do you have any additional context?**
After a quick look it looks like [OPENID_AUTH_LOGIN ](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/common/index.ts#L31) is used in [renderLoginButton](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/login/login-page.tsx#L112) without checking the serverBasePath.

**Comment by scrawfor99** [comment]
[Triage] @RyanL1997 can you follow up on this with your other OIDC work. Thank you.

**Comment by RyanL1997** [comment]
This issue has been confirmed, and #1358 is the fix of this issue. I will follow up on that PR to see if the author needs help on adding test.

**Comment by peternied** [comment]
The associated PR has been resolved in main, the fix should be available with the next 2.X release.
