### ISSUE TITLE
[BUG] Unable to edit existing Anomality Detectors after changing Authentication to SAML

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/security-dashboards-plugin#1377]
@lehmat commented on [Fri Mar 10 2023](https://github.com/opensearch-project/security-dashboards-plugin/issues/1378)

**Describe the bug**
Changing authentication from internal users to SAML authentication causes existing (created with internal user, that is now deleted) anomality detectors to be not editable with administrator access.

Details:

PUT /_dashboards/api/alerting/monitors/id-of-detector?ifSeqNo=1&ifPrimaryTerm=59
-> Response status code 200
-> Response content: {"ok":false,"resp":"[alerting_exception] User has no available detectors"}
 

**To Reproduce**
1. Change authentication method to SAML (Azure in this case), Log in with new user with pre-existing anomality detectors
2. Click on Anomaly detection on sidebar
3. Click on Detectors
4. Click on one of Detectors created
5. Anomality overview click on Edit alert settings
6. Click on Edit
7. Do not make any changes and click on Update at the bottom

**Expected behavior**
Should be able to successfully edit

**Plugins**
SAML Authentication from Opensearch AWS console enabled

**Host/Environment (please complete the following information):**
 - OS: Windows 11, Edge
 - Version 2.3 (Latest on AWS)

**Comment by peternied** [comment]
@kavilla I don't think we should use Zenhub to transfer issues.  I'm closing this out, since it wasn't posted by the author they won't get notifications.  I'll reopen the original and transfer it.

**Comment by kavilla** [comment]
I wasnt able to transfer the issue to the security dashboards repo anymore and didnt want to lose the content though by recreating.

@peternied . I know the transfer group was deleted but does that mean the repo has to onboard to another github team?

**Comment by peternied** [comment]
@kavilla I would expect members of the @opensearch-project/triage team to transfer issues.  I think you are a member, if that doesn't work I think we should adjust that groups permissions - can you dig in?
