### ISSUE TITLE
[Build break 1.0 / 1.1] Wrong Security Plugin branch

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security-dashboards-plugin#1383]
During CI builds there is a failure on Run integration tests, with the following
`Error:  The goal you specified requires a project to execute but there is no POM in this directory (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/security). Please verify you invoked Maven from the correct directory. -> [Help 1]`

From inspection it looks like the workflow is checking out the wrong branch.
```
Checking out the ref
  /usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
  Switched to a new branch 'main'
  branch 'main' set up to track 'origin/main'.
/usr/bin/git log -1 --format='%H'
'fb70a751312af9ab9683aaff878c8b145dda7ac6'
```
This reference is pointed to main - I think we need to adjust the workflow to point to the correct branch for 1.0 and 1.1 builds that use maven.

See log for additional details https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/4348472586/jobs/7597042933?pr=1365

**Comment by scrawfor99** [comment]
[Triage] Hi Peter, thank you for filling this issue. I know this is related to your work on backporting these changes for some contributors so I will be assigning this to you.

**Comment by davidlago** [comment]
Closing as we have no plans of releasing 1.0/1.1 versions
