### ISSUE TITLE
[BUG] "Get started" image is not adaptive to the browser window size.

### ISSUE THREAD

**Issue by nurSaadat** [opensearch-project/security-dashboards-plugin#1386]
**What is the bug?**
The image goes out of the text area when the browser window is minimized.

**How can one reproduce the bug?**
1. Go to Security -> Get Started
2. Minimize the browser window

**What is the expected behavior?**
The image is scaled down to match the browser window size or goes out of the range gracefully.

**What is your host/environment?**
 - OS: Ubuntu
 - Version: 18.04
 - Browser: Firefox
 - Browser version: 111 

![image](https://user-images.githubusercontent.com/39532643/227056633-6e4081d5-9327-4b12-8fcf-004ec1a2eaeb.png)
![image](https://user-images.githubusercontent.com/39532643/227056769-fecd7291-bef0-4820-a541-825b1728d468.png)

**Comment by scrawfor99** [comment]
HI @curq, I will take a look now!
