### ISSUE TITLE
[Admin] Revisit and update branch protection rules

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security-dashboards-plugin#1387]
After reviewing our many legacy branches, the protection rules are not setup correctly, such as the following pull request on 2.1

![image](https://user-images.githubusercontent.com/2754967/227057170-e2cc9a1e-b78b-497f-8a7d-d29e3505a73a.png)

As there are outstanding pull requests in nearly all branches, make sure the rules are updated and the correct workflow checks are required for changes to be merged.

**Comment by scrawfor99** [comment]
[Triage] The maintainers of the Security repository, discussed the topic and came to a general opinion on how to handle the maintenance of deprecated branches. These details will be consolidated and described below before the issue is closed.

**Comment by peternied** [comment]
@scrawfor99 was that conversation captured / who will provide the updates?

**Comment by scrawfor99** [comment]
Hi @peternied, I had thought you had some notes on the topic from last week. Judging by your comment this is not the case...

**Comment by peternied** [comment]
OK - thanks, double checking.  Basically there are a couple of branches that cannot merge because of the misalignment.  I'll be addressing this

**Comment by peternied** [comment]
This isn't actively being worked on as there are no blocked changes at this time, if this comes back up we can re-prioritize this work

**Comment by davidlago** [comment]
Closing for now, will reopen when/if it makes sense.
