### ISSUE TITLE
[BUG] securitytenant header for tenant named "global" conflicts with "Global Tenant"

### ISSUE THREAD

**Issue by smlx** [opensearch-project/security-dashboards-plugin#1411]
**What is the bug?**
The Dashboards API accepts a `securitytenant` HTTP header identifying the tenant which is targeted for API requests.

Ordinarily, `securitytenant: global` targets the reserved "Global Tenant". However, the `security-dashboards-plugin` allows you to create a tenant named "global". Suddenly, `securitytenant: global` starts targeting this new tenant. With another tenant named "global", there doesn't seem to be any way to target the reserved "Global Tenant"

**How can one reproduce the bug?**
1. Deploy Opensearch Dashboards with the Global Tenant enabled.
2. In the Global Tenant, create an index pattern with a unique name. e.g. `*-logs-*`
3. Create a tenant named "global" via the Dashboards UI and switch to it.
4. Create an index pattern with a different unique name. e.g. `application-logs-*`.
5. Hit the Dashboards API to query index patterns for the "global" tenant, and see `application-logs-*`
    ```
    $ curl -ksSL -u "$USER_AUTH" -H 'securitytenant: global' -H 'osd-xsrf: true' 'http://localhost:5601/api/saved_objects/_find?type=index-pattern'| jq '.saved_objects[]|.attributes.title'
    "application-logs-*"
    ```
7. Delete the "global" tenant you just created.
8. Hit the Dashboards API again with an identical query. See the `*-logs-*` index pattern.
    ```
    $ curl -ksSL -u "$USER_AUTH" -H 'securitytenant: global' -H 'osd-xsrf: true' 'http://localhost:5601/api/saved_objects/_find?type=index-pattern'| jq '.saved_objects[]|.attributes.title'
    "*-logs-*"
    ```

**What is the expected behavior?**
The Global tenant should have some special identifier in the `securitytenant` header which is not a legal name for a regular tenant.

**What is your host/environment?**
 - OS: Linux
 - Version 2.6.0
 - Plugins Security

**Do you have any screenshots?**
n/a

**Do you have any additional context?**
This code in the tenant resolver appears to be the culprit. It looks for an available tenant first, before falling back to the Global tenant:
https://github.com/opensearch-project/security-dashboards-plugin/blob/5e99582ea55176a16f0190998abcc99c99e7f974/server/multitenancy/tenant_resolver.ts#L97-L114

**Comment by scrawfor99** [comment]
[Triage] Hi @smlx, thank you for filing this issue. @RyanL1997, would you please follow-up on this issue? Thank you.

**Comment by RyanL1997** [comment]
Checking if @abhivka7 's change https://github.com/opensearch-project/security-dashboards-plugin/pull/1419 fixed this issue also.

**Comment by abhivka7** [comment]
Checking.

**Comment by RyanL1997** [comment]
@abhivka7 I do see that this [line](https://github.com/opensearch-project/security-dashboards-plugin/pull/1424/files#diff-77b98140ad6efc5867d7ed7eefb86b5fda98771ed1766597719d39fad64700feR22) fixed this issue:

**Comment by smlx** [comment]
Thanks for the fix, but could you please explain how to target the Global tenant with the `securitytenant` HTTP header?

**Comment by smlx** [comment]
@RyanL1997 ^^

**Comment by smlx** [comment]
Hi, is there any documentation on how to target the Global tenant using the `securitytenant` HTTP header?

**Comment by cwperks** [comment]
@smlx The list of values you can use can be found here: https://github.com/opensearch-project/security-dashboards-plugin/blob/main/server/multitenancy/tenant_resolver.ts#L27

They are:

- 'global'
- 'Global'
- '' <- Empty string

It looks like `global` should be forbidden as a custom tenant name because the custom tenants and getting resolved before global here: https://github.com/opensearch-project/security-dashboards-plugin/blob/main/server/multitenancy/tenant_resolver.ts#L129-L146

^ I would try with empty string.
