### ISSUE TITLE
Node.js v18 Compatibility Test for [security-dashboards-plugin]

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/security-dashboards-plugin#1430]
## Introduction
As part of our continued efforts to improve OpenSearch Dashboards, we are planning to upgrade the underlying Node.js version from v14 to v18. This change will enhance performance, add new features, and bolster security. However, such major version changes might also affect the compatibility of existing plugins. Here is more introduction: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3601.

Therefore, we kindly request assistance in testing this plugin the compatibility of with this new version of Node.js. We've prepared a branch with the Node.js v18 upgrade, which you can find here:
https://github.com/AMoo-Miki/OpenSearch-Dashboards/tree/node-18-webpack-4

## Steps to Proceed
* If you think your plugin won't be affected by OpenSearch Dashboards Node.js upgrade. Pls ignore the rest steps and close the issue directly.
* Pull the provided branch that includes the Node.js v18 upgrade and OpenSearch 3.0.0.
* Hook up your plugin with the updated OpenSearch Dashboards.
* Run your existing test suites and perform manual testing as necessary.
* If no issues are encountered, feel free to close this issue.
* If there are any problems, report them in this issue thread and also **link them in the overall OpenSearch Dashboards Node.js upgrade issue thread** https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4058
The purpose of linking any questions or issues back to the main issue is to maintain visibility and transparency among all plugin owners. A problem encountered by one plugin might also affect others. This shared knowledge base will foster collaborative problem-solving and prevent duplication of effort.

We appreciate your support and cooperation in ensuring a smooth transition to Node.js v18 for the entire OpenSearch Dashboards community.

**Comment by ananzh** [comment]
The official Node.js 18 PR raised in OSD: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4071

**Comment by scrawfor99** [comment]
[Triage] Hi @ananzh, thank you for creating this issue. Security dashboards will likely be impacted by this upgrade so we will need to review the code and follow the steps you outlined. This could be a good option for a first time contributor. Marking as help wanted & 3.0.0.

**Comment by ananzh** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4071 support node 14, 16 and 18. Pls test on node 18. 
```
nvm install 18.16.0
nvm use 18.16.0
```

**Comment by ananzh** [comment]
@scrawfor99 our target release is 2.8. Since node 14 `Node.js 14 (LTS): Security Support Ends in 1 month on 30 Apr 2023`, due to this major security concern and OSD supports multiple node versions, we don't consider it as breaking change.

**Comment by scrawfor99** [comment]
Taking a look at this now.

**Comment by scrawfor99** [comment]
Verified all functionality is as expected with the updated version. Closing this issue. Thank you again @ananzh!
