### ISSUE TITLE
Getting popup(Select your tenant) even when multitenancy is disabled.

### ISSUE THREAD

**Issue by ramanavenky22** [opensearch-project/security-dashboards-plugin#1436]
Describe the bug

I have disabled multitenancy in both config.yml(multitenancy_enabled: false) and opensearch_dashboards.yml(opensearch_security.multitenancy.enabled: false) but when i open dashboards UI i am getting a popup  to enable multitenancy.

To Reproduce

Disable multi-tenancy
Open a new window of Dashboards.

Expected behavior
The user should not be asked about a disabled feature.

OpenSearch Version
2.7.0

Dashboards Version
2.7.0

Screenshots
<img width="683" alt="image" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/68619433/01084758-0805-44b0-a3d0-10f5055d72ec">

**Comment by Alwinius** [comment]
Same here, for us this occured when updating using the opensearch-operator from 2.5.0 to 2.7.0. Different to the other issues relating to a similar bug, the tenant selection is now empty (as seen in screenshot) and under Security - Tenants the tenants feature is disabled everywhere

**Comment by hobti01** [comment]
We also see the issue in Opensearch 2.7.0, security plugin 2.7.0.0 with dashboards.yml configuration
```yaml
opensearch_security:
  multitenancy:
    enabled: false
```

Original bug(s) are linked through here: https://github.com/opensearch-project/security-dashboards-plugin/issues/838
and the fix https://github.com/opensearch-project/security-dashboards-plugin/pull/965
was documented in the 2.0.0.0 release https://github.com/opensearch-project/security-dashboards-plugin/releases/tag/2.0.0.0
this seems like a regression.

**Comment by davidlago** [comment]
@ramanavenky22 / @hobti01  this issue has a fix going out in our upcoming 2.8.0 release (tentative release date 6/6)

**Comment by arminnikdelbert** [comment]
This is marked as closed in v2.8.0: https://github.com/opensearch-project/security-dashboards-plugin/issues/1436
I think we should upgrade
