### ISSUE TITLE
Confirmation dialog for removing permission is unstyled at bottom of page

### ISSUE THREAD

**Issue by aetter** [opensearch-project/security-dashboards-plugin#146]
If you attempt to delete anything from the index permissions tab of a role, the confirmation dialog pops up in the lower-left of the screen completely unstyled. I suspect this problem occurs in other places, as well.

Reproducible in Chromium Edge and Firefox.

1. Make a new role with an index pattern and some permissions in ODFE 1.4.0.
2. Save Role Definition.
3. Edit the role.
4. Try to remove a permission.

![seq1](https://user-images.githubusercontent.com/9122297/75593495-678b3200-5a3a-11ea-851b-0ea977e17a55.png)

![seq2](https://user-images.githubusercontent.com/9122297/75593500-6a862280-5a3a-11ea-96d4-68a79dd6110e.png)

**Comment by sujithvm** [comment]
@aetter This was fixed in ODFE 1.4.0.0. How are you running kibana (docker, cloudfront.. ) ? 
Probably the release was cut before the fix was applied. 
FIx PR: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/136

**Comment by aetter** [comment]
I'm on Docker images `amazon/opendistro-for-elasticsearch:1.4.0` and `amazon/opendistro-for-elasticsearch-kibana:1.4.0`.

**Comment by sujithvm** [comment]
@aetter I will check with the infra team and make a new release if necessary for ODFE docker.

**Comment by davidlago** [comment]
Apologies for the late reply here. Tested with OpenSearch 1.2.4 and the issue is no longer reproducible (the UI has changed substantially and those buttons are no longer there in that form).
