### ISSUE TITLE
[FEATURE] onboard to capabilities service

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/security-dashboards-plugin#1468]
**Is your feature request related to a problem?**
As a plugin I would like to check if certain features of security enabled without actually hitting APIs and failing.

**What solution would you like?**
For [example](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/vis_builder/server/capabilities_provider.ts#L6).

Then I can post with the `/api/core/capabilities` with my plugin name and check if i can do stuff with the securityDashboards plugin.

If not enable then it won't be added to this list.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by scrawfor99** [comment]
[Triage] @kavilla thank you for filing this issue. @cwperks could you please follow-up on this request. Thank you both.

**Comment by scrawfor99** [comment]
Closing this issue for now. If required please reopen this issue with additional details about the request. Thank you.
