### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by norsco15** [opensearch-project/security-dashboards-plugin#1470]
**What is the bug?**
Hello! I faced a problem. I’m trying to include my OpenSearch Dashboard in my website using iframe like this : 

`<iframe src="https://localhost:5601" style="width: 100vw; height: 100vh;"></iframe>`

So it's loaded into the iframe, but it constantly asks for a login-password, I enter the correct user/password, but it doesn't connect into the dashboard and again requires input.

Console Errors are in the following screenshot : 
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/118997756/d111b035-2c51-4b29-a1c5-9778c2d89e19)

At the same time, when i open the link of the iframe (localhost:5601) in a separate tab, everything works correctly.

**What is the expected behavior?**
The expected behavior is that the dashboard should work using iframe the same as without iframe.

**Do you have any additional context?**
My opensearch.yml file configuration is : 

```
plugins.security.disabled: "false"
plugins.security.ssl.transport.pemcert_filepath: node1.pem
plugins.security.ssl.transport.pemkey_filepath: node1-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: node1.pem
plugins.security.ssl.http.pemkey_filepath: node1-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
plugins.security.authcz.admin_dn:
  - 'CN=A,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA'
plugins.security.nodes_dn:
  - 'CN=node1.dns.a-record,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA'
  - 'CN=node2.dns.a-record,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA'
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access", "client1_role"]
```

And my opensearch_dashboards.yml file configuration is the following :

```
opensearch.hosts: ["https://localhost:9200"]
opensearch.ssl.verificationMode: certificate
server.ssl.enabled: true
server.ssl.certificate: "C:\path\to\client.pem"
server.ssl.key: "C:\path\to\client-key.pem"
opensearch.ssl.certificateAuthorities: ["C:\path\to\root-ca.pem"]
opensearch.username: kibanaserver
opensearch.password: kibanaserver
opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.enable_global: true
opensearch_security.multitenancy.tenants.enable_private: true
opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
opensearch_security.multitenancy.enable_filter: false
opensearch_security.cookie.secure: false
server.cors: true
csp.rules:
  - "frame-src 'self' http://localhost:3001"
  - "frame-ancestors 'self' http://localhost:3001"
```

Does anyone have an idea how to resolve this issue ?

**Comment by davidlago** [comment]
Please see [this discussion in the forums](https://forum.opensearch.org/t/enabled-jwt-authentication-for-opensearch/13345). The dashboard embed still needs to access something behind an authentication "wall" (unless you set it up to be anonymous/non-auth'd).
