### ISSUE TITLE
[BUG] login always takes you to the last selected tenant

### ISSUE THREAD

**Issue by agottoli** [opensearch-project/security-dashboards-plugin#1475]
**What is the bug?**
url query parameter security_tenant is ignored when you log in

**How can one reproduce the bug?**
1. create a dashboard in a tenant (e.g. tenant-1)
2. select share > permalink with short url
3. copy dashboard short link
4. select Overview
5. select another tenant from profile > swich tenants (e.g private)
6. logout
7. paste dashboard short link and log in
8. see error dashboards does not exists
9. check current tenant from profile, you are in the wrong tenant (private)

**What is the expected behavior?**
After login you should be in tenant specified in security_tenant query parameter

**What is your host/environment?**
opensearch 2.8.0
opensearch-dashboards 2.8.0

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5139570/b1991b73-1333-4192-b1e0-362fbd0306d4)
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5139570/e66ce159-dac3-482c-94c0-043ec1fc664d)
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5139570/363f13f9-b3f3-48f5-86d6-2d19b732d1d1)
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5139570/3dc403e7-5b8f-404b-b3c7-652d9ea35c0f)
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5139570/3e60fbaf-9537-4bec-b301-a41db6860b6a)
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5139570/928407dc-e9b1-4942-94e9-ba3655cf244d)

**Comment by davidlago** [comment]
Thanks for the detailed report, @agottoli. Closing as a duplicate of #1203. Good news is, there is a PR out to fix this and we're targeting our next release to get this change in.
