### ISSUE TITLE
URL fragment get lost in redirect

### ISSUE THREAD

**Issue by jerrywang-db** [opensearch-project/security-dashboards-plugin#1476]
**Is your feature request related to a problem? Please describe.**

When working with Kibana, the authentication expires after certain time (e.g. 30 minutes), and the page is redirected to the authentication page. And when authentication completed, the page can not be redirected back to where it was because the URL fragment is not preserved. 

**Describe the solution you'd like**

The page should be redirected to the original URL after authentication. ElasticSearch has fixed this issue: https://github.com/elastic/kibana/pull/44513

**Describe alternatives you've considered**

**Additional context**

**Comment by scrawfor99** [comment]
[Triage] Hi @jerrywang-db, thank you for filing this issue. @cwperks has volunteered to take a look at addressing this.

**Comment by devardee** [comment]
The requested feature is already merged https://github.com/opensearch-project/security-dashboards-plugin/pull/1039

@davidlago can we close this issue ?

cc: @prabhat-chaturvedi

**Comment by davidlago** [comment]
Closing, thanks for the ping! The PRs were not linked to this issue explicitly so it didn't auto-close.
