### ISSUE TITLE
[BUG] Some permissions are categorized incorrectly in security dashboards UI

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1481]
**What is the bug?**
Some permissions are categorized incorrectly as index permissions when they are actually cluster permissions according to https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java#L664-L676. For example: 
<img width="841" alt="Screen Shot 2023-06-21 at 11 26 46 AM" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/949c16e5-f69c-4249-9863-c83f321cbc19">

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by DarshitChanpura** [comment]
[Triage] Closing this as it was completed via #1480
