### ISSUE TITLE
[BUG] Need for invalid permission clean up?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security-dashboards-plugin#1483]
**What is the bug?**
Coming from https://github.com/opensearch-project/security-dashboards-plugin/issues/1481, there is a possiblity that users have used the Dashboards dropdown to create permissions object were a cluster permission was included in the list of index permissions.  These permissions might be creating confusion since they are not authorizing actions as expected.

**How can one reproduce the bug?**
1. Edit permission on a role
1. Select the index permissions
2. Select the permission `indices:data/write/reindex` and apply it
3. Attempt to run a reindex with an account that uses that role

**What is the expected behavior?**
Reindex should fail because permission really weren't granted, it should be clear how the permissions should be modified to grant that permission

**Comment by peternied** [comment]
@setiah Could you weigh in if you think this requires are migration to detect these invalid configurations and the appropriate action to take on them (Delete the invalid permission, create the correct permission on the role)?

**Comment by DarshitChanpura** [comment]
[Triage] @setiah Would you please add you thoughts here?

**Comment by peternied** [comment]
[Triage] I don't think its clear that this would be high value for security plugin users - this area will be approached when permissions declarations are revisited
