### ISSUE TITLE
[BUG] FATAL  Error: Cannot find module '../../../../packages/osd-std'

### ISSUE THREAD

**Issue by ruanyl** [opensearch-project/security-dashboards-plugin#1487]
**What is the bug?**
Found this on `main` branch, runtime error which says `FATAL  Error: Cannot find module '../../../../packages/osd-std'`

**How can one reproduce the bug?**
1. Build [security-dashboards-plugin](https://github.com/opensearch-project/security-dashboards-plugin)
2. Install `security-dashboards-plugin` tarball
3. Start OSD server
4. Open OSD, you should see error

**What is the expected behavior?**
No error

**What is your host/environment?**
Not applicable

**Do you have any screenshots?**
Not applicable

**Do you have any additional context?**
The reason is the path of imported `osd-std` package, it should not be a relative path `'../../../../packages/osd-std'`, but instead from `@osd/std`

**Comment by DarshitChanpura** [comment]
[Triage] Thanks for filing this issue. @cwperks Please add your thoughts on this.

**Comment by AMoo-Miki** [comment]
This will be a 2.9 release blocker.

**Comment by wbeckler** [comment]
How did this get past CI?

**Comment by davidlago** [comment]
Good question @wbeckler... I see the PR that introduced those imports with the relative paths [passed all CI checks](https://github.com/opensearch-project/security-dashboards-plugin/pull/1462/checks). @cwperks  I see you are assigned to it, please look into how this snuck past CI to make sure we catch future ones. Thanks!

**Comment by peternied** [comment]
Thanks for providing a fix in the description @ruanyl.  Would you be able to reproduce your build scenario from a fresh repository(ies), and then copy the full transcript of your log so we can inspect it?

**Comment by peternied** [comment]
In my PR, I didn't look into `how this snuck past CI`, I suspect it has to do with path differences from how our CI workflow is set up compared to how ruanyl performed their build.  The code that was called out is clearly wrong, but there might be more issues even with my PR.

@cwperks I'll look to your guidance on what makes sense around merging #1498.

**Comment by peternied** [comment]
Reopening to make sure the investigation into the root cause isn't lost

**Comment by scrawfor99** [comment]
[Triage] Hi @ruanyl, thank you for filing this issue. Looks like this is being addressed by work done by @cwperks.
