### ISSUE TITLE
[FEATURE] Dropdown for backend roles in create internal user

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1488]
- try to create new internal user
- After filling out username/password you have the option to add backend roles
- However this doesn't have any dropdown/indication of existing backend roles, 
- I tried adding "Admin" tenant but found out the existing one is lowercase

If possible there should be a dropdown indicating existing backend roles, or make it clear that you are creating a new one in case of misspellings or capitalization mismatches

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho, thank you for filing this issue. Unfortunately, because of how external IdPs work this is not something that is within scope for the Security plugin's plans.
