### ISSUE TITLE
Inconsistent security behaviour after multi-tenancy index migration

### ISSUE THREAD

**Issue by tremmert** [opensearch-project/security-dashboards-plugin#149]
Please let us know if this is fixed in a newer version.

Using Kibana & ES 6.6.2 with v.0.8.0.0 We can't update to 7 at the moment as we have a number of our own plugins, but we could update to ES 6.8.x and v 0.10.0.0 ?  if that would help 

We have created: 

- a tenant, called mytenant
- a role mytenant-admin

role spec being
`{
  "cluster": [
    "UNLIMITED"
  ],
  "indices": {
    "my_data-mytenant*": {
      "*": [
        "UNLIMITED"
      ]
    }
  },
  "tenants": {
    "mytenant": "RW"
  }
}`

and that works fine....

UNTIL we restart kibana, and it does index migration. 

Before index migration happens there is a kibana index, called something like .kibana_123345_mytenant, and anyone with the mytenant-admin role can do pretty much anything inside the mytenant tenant... create index patterns, create dashboards, save searches, etc...

After index migration, the .kibana_123345_mytenant gets re-indexed to an index .kibana_123345_mytenant_1 and then copied to .kibana_123345_mytenant _2  , and an alias is created pointing .kibana_123345_mytenant to .kibana_123345_mytenant _2 

And then when you log in again as a user with the mytenant-admin role, almost NOTHING works.

It seem there is no access rights, either to the alias or the copied-to-index.

The fact that the migration completel changes he security requirements is very inconsistent, and poses the worrying question of what else may have changed.... 

Its just completely odd that the security requirement before and after an index migration should be so different.

**Comment by davidlago** [comment]
Sorry for the late reply... were you able to find a workaround/solution to this?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
