### ISSUE TITLE
[BUG] missing roles button doesn't do anything

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1490]
- Clear all roles from a user 
- Try to login as that user
- This button doesn't do anything/link you back to anything
- Can't login at all in general - is this expected/a bug? Should we prevent people from deleting all roles linked to a user if it breaks like this?

<img width="1512" alt="Screen Shot 2023-06-27 at 12 30 36 PM" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/f47c97fe-04df-4b9f-852f-0b7238c869ba">

**Comment by cwperks** [comment]
Would it make sense for that button to be a logout button?

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho thank you for opening this issue. This issue seems like a good one to get some UX/UI input on. Marking as such.

**Comment by kamingleung** [comment]
I also think a Logout button would be more appropriate for this specific case.

Follow-up question: Is this screen only shown to users with 0 roles? What about users that has no Dashboards access (if that possible)?

**Comment by leanneeliatra** [comment]
Will start this issue

**Comment by leanneeliatra** [comment]
I can also see the button/page if I directly visit the URL: http://localhost:5601/app/customerror/missing-role
Issue in progress.

**Comment by leanneeliatra** [comment]
Added a logout action to this button. See PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/1564
& associated integration tests PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/830

**Comment by leanneeliatra** [comment]
I have merged in the updated changes from the main branch, as this branch was behind.

**Comment by davidlago** [comment]
@RyanL1997 could you please lend a hand here? Thanks!

**Comment by leanneeliatra** [comment]
**2 tickets are linked to this:
1. The bug fix**
- Ryan has tested manually and the cypress tests are passing.
- I have requested very final reviews (hopefully) from the users the CI called out: cliu123, scrawfor99 and davidlago.
- Link: https://github.com/opensearch-project/security-dashboards-plugin/pull/1564
**3. The tests**

**Comment by leanneeliatra** [comment]
Update: 

**2 tickets are linked to this:**

**1. The bug fix itself**
https://github.com/opensearch-project/security-dashboards-plugin/pull/1564
**Merged**

2. The tests
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/830
**Need one final review, I have requested this on the PR and in slack.**

**Comment by leanneeliatra** [comment]
**Update**

Both the bugfix and the tests are merged now. 
**This ticket can be moved to done**

**Comment by davidlago** [comment]
Thanks @leanneeliatra !
