### ISSUE TITLE
Is there any way to auto refresh JWT access_token ?

### ISSUE THREAD

**Issue by pengsili** [opensearch-project/security-dashboards-plugin#1492]
**Is your feature request related to a problem? Please describe.**

Dear support,
We deployed OpenSearch and enabled SSO by integrating with our keycloak. According to the security policy of our company, the JWT access_token will be expired in 5 minutes. But the refresh_token is 3 hours. Users said that they had to login again every 5 minuts. We checked with the support of keycloak in our company. They said this strategy was required by our security team, and adviced that application using our keycloak should regularly refresh the token by code.

**Describe the solution you'd like**

So i wonder if OpenSearch already has such strategy to auto refresh the token and i only need enable it in config. if not, please advice how to handle this case?

Thanks a lot for your help

**Comment by wbeckler** [comment]
I assume this is something handled by the security-dashboards-plugin, so transferring to that repo. Please transfer back if I'm mistaken.

**Comment by cwperks** [comment]
Hi @pengsili, the security-dashboards-plugin has support for [refreshing access tokens](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/server/auth/types/openid/openid_auth.ts#L204-L263) for OpenID Connect auth providers like Keycloak. When the current access token expires, security-dashboards-plugin should be calling the token endpoint of the identity provider with `grant_type`: `refresh_token` to obtain a new access token. 

There is a comment in the code to check with the IdP (keycloak) to make sure the refreshing access tokens in available in the IdP. 

```
// if no id_token from refresh token call, maybe the Idp doesn't allow refresh id_token
```

----

I have not personally tested out the refresh token logic before, but I see in the code that it is reading `id_token` from the token endpoint response and not using `access_token` which is also being parsed out in:

```
export async function callTokenEndpoint(
  tokenEndpoint: string,
  query: any,
  wreckClient: typeof wreck
): Promise<TokenResponse> {
  const tokenResponse = await wreckClient.post(tokenEndpoint, {
    payload: stringify(query),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
  });
  ...
  return {
    idToken: tokenPayload.id_token,
    accessToken: tokenPayload.access_token,
    refreshToken: tokenPayload.refresh_token,
    expiresIn: tokenPayload.expires_in,
  };
}
```

**Comment by cwperks** [comment]
@pengsili In keycloak its possible to extend the expiry of the refresh tokens in the `Realm Settings -> Sessions` tab and increasing `SSO Session Idle`. The access token lifespan is configured in `Realm Settings -> Tokens` tab. In the security-dashboards-plugin a new access token is obtained using the refresh token after the access token has expired, but the refresh token is still within its valid window. If they are configured to have the same expiry of if the `SSO Session Idle` is set to a value lower than the access token expiry then refreshing the access token will not work. I am closing this issue.
