### ISSUE TITLE
[BUG] OIDC refresh token logic doesn't work correctly 

### ISSUE THREAD

**Issue by uladzimir-tryputska** [opensearch-project/security-dashboards-plugin#1507]
**What is the bug?**
When id token is expired, security plugin is asking for a new id token. New id token is stored in user cookies, but it is not used in the current session, further requests are failing because they are using the previous expired id token 

**How can one reproduce the bug?**
We are using Gitlab as IDP, where id token life time is 2 minutes. Or any IDP can be used with small token expiration  time
1. Login into Opensearch Dashboard
2. Wait for > 2 mins
3. Click any link -> error

**What is the expected behavior?**
After id token is refreshed, the new id token should be used for further request

**What is your host/environment?**
 - official Opensearch Dashboard image 2.8.0.0

**Do you have any screenshots?**
Error in the dashboard console 
```sh
Error: Authentication Exception
    at SecurityClient.authinfo (/usr/share/opensearch-dashboards/plugins/securityDashboards/server/backend/opensearch_security_client.ts:118:13)
    at runMicrotasks (<anonymous>)
    at process.authHeaders (node:internal/process/task_queues:96:5)
    at /usr/share/opensearch-dashboards/plugins/securityDashboards/server/auth/types/authentication_type.ts:213:23
    at Object.interceptAuth [as authenticate] (/usr/share/opensearch-dashboards/src/core/server/http/lifecycle/auth.js:112:22)
    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at module.exports.internals.Auth._authenticate (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/auth.js:273:30)
    at Request._lifecycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)
    at Request._execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)
```
**Do you have any additional context?**
New id token is stored here 
https://github.com/opensearch-project/security-dashboards-plugin/blob/2.8.0.0/server/auth/types/openid/openid_auth.ts#L245
but when authorization header is built for next queries, an old id token is still in use
https://github.com/opensearch-project/security-dashboards-plugin/blob/2.8.0.0/server/auth/types/authentication_type.ts#L163
I suppose it is because of how cookies are managed in the code https://github.com/opensearch-project/security-dashboards-plugin/blob/2.8.0.0/server/session/cookie_splitter.ts

**Comment by peternied** [comment]
[Triage] this is a duplicate of https://github.com/opensearch-project/security-dashboards-plugin/issues/828 however this shorter lifespan token is a bigger issue in this scenario.  Please follow up on that issue with additional thoughts.

**Comment by uladzimir-tryputska** [comment]
Issue was not fixed with #828 and still present in the 2.14 version

**Comment by uladzimir-tryputska** [comment]
And it's gotten  even worse, because refresh token end point is not called any more, when id token is expired :)  

isValidCookie() https://github.com/opensearch-project/security-dashboards-plugin/blob/2.14.0.0/server/auth/types/authentication_type.ts#L145, where refresh token logic is located, is not called any more, because cookie is cleared here https://github.com/opensearch-project/security-dashboards-plugin/blob/2.14.0.0/server/auth/types/authentication_type.ts#L139. And it is cleared because token is expired. Expiration logic was changed recently.
@peternied how can I reopen issue? I don' t see any button for this

**Comment by uladzimir-tryputska** [comment]
created follow up bug https://github.com/opensearch-project/security-dashboards-plugin/issues/2015
