### ISSUE TITLE
[BUG] 1.x should contain changes from 1.3 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security-dashboards-plugin#1520]
**What is the bug?**
From the [project branching guidance](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching), security-dashboard-plugin's 1.3 branch would have changes propagated from 1.x.  Looking at the current state of the branches many changes have been pushed directly from main into 1.3

**How can one reproduce the bug?**
1. Inspect a comparison of the branches https://github.com/opensearch-project/security-dashboards-plugin/compare/1.x...1.3
1. There should be trivial differences between the branches, whereas there are ~30 commits difference

**What is the expected behavior?**
All changes in 1.3 should also be present in 1.x

**Do you have any additional context?**
- Coming from https://github.com/opensearch-project/security-dashboards-plugin/pull/1514

**Comment by DarshitChanpura** [comment]
Closing this as the attached PR is merged.
