### ISSUE TITLE
[FEATURE] Password Strength UI

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1523]
Similar to other websites that have password strength UI when creating a user, the security dashboards plugin should have something similar. 

- A UI component that shows whether a given password is weak to very strong
- Shows red/green progress bar as password gets stronger

**Comment by derek-ho** [comment]
First Step: - Don't allow users to create users with passwords that violate the regex rule specified in the config file
Second step: - Try to use https://github.com/dropbox/zxcvbn - or similar to match UI with what backend would return for the strength of a given password

**Comment by scrawfor99** [comment]
[Triage] @derek-ho thank you for filing this issue. Going to tag UX/UI, and assign this issue to you ;)

**Comment by peternied** [comment]
I'm not sure if we have precedence for this kind of scenario, but approach 1 seems like a good candidate.

If you need another alternative, consider adding a parameter to the password setting API such as a 'dry-run' flag.  Then you can reuse whatever error comes from the backend system to populate the front end ❌, or a ✔️

**Comment by kamingleung** [comment]
On a high-level, strong/weak indicators alone is rather ambiguous. We should provide upfront guidance on how to make their password strong, eliminating any guesses on users. 

As users are typing in their passwords, I would consider specifically listing out which password criteria users are missing, so that users have clear actionable path.

**Comment by kamingleung** [comment]
@derek-ho 

> Two possible ways we can solve this, as @cwperks pointed out, rule/regex based regex seems to be at odds, or at least not 1:1 with library based password scoring.
Is there an issue that gives full context behind why we need a password strength UI? What did @cwperks pointed out? Thanks.

**Comment by derek-ho** [comment]
@kamingleung I think there is two things here - 
1. Does the password meet the minimum criteria to be accepted by OpenSearch - should be addressed in another PR: #1581 
2. Is the password considered strong enough to be accepted by OpenSearch - related to zxcvbn library. In order to implement this on the UI I am calling the same library the backend is calling to validate the strength of a password - however this doesn't have some specific set of standards as far as I can tell - it is based on how long the library thinks it would take to crack the given password, thus showing it as a progress bar. For example test is a very weak password, test12 is weak (better than test), but test123 is considered very weak again, even though test123 is more complex than test12. Outside of a strength bar I think this will be hard to communicate to users.
