### ISSUE TITLE
[BUG] SSO login redirect to home page instead of nexturl

### ISSUE THREAD

**Issue by mourya-satyam-888** [opensearch-project/security-dashboards-plugin#1528]
**Describe the bug**

If I do native login it redirect me to the nexturl the dashboard or something whose link I have opened but while login using Azure SSO it redirect me to home page irrespective of what I had opened

**To Reproduce**
1. login and open discover section
2. Copy url and logout
3. open the copied url
4. It would ask to login and do login with sso

**Expected behavior**
It should have opened discover section but instead it redirect to home page

**OpenSearch Version**
2.7.0

**Dashboards Version**
2.7.0

**Comment by scrawfor99** [comment]
[Triage] Hi @mourya-satyam-888, thank you for filing this issue. Could you please provide a trace of your HTTP traffic? Thank you.

**Comment by mourya-satyam-888** [comment]
if I logged out and try to hit this endpoint(removed my domain for policy purpose) : https://mydomain/app/login?nextUrl=%2Fapp%2Falerting
and do login with sso then redirected to azure ad idp and if authentication successful it redirect me to home page instead of alerting but in native login it is as expected.

not sure is it intended if so then its feature request rather than a bug

**Comment by cwperks** [comment]
@mourya-satyam-888 Thank you for filing this issue. This request may be a better fit for the [OpenSearch forums](https://forum.opensearch.org/c/security/3) where there may be other users that have faced a similar issue. 

I am marking this as closed, but would also be able to provide a little more info about Azure SSO and what type of Identity Provider this is? (OIDC, SAML or LDAP) and an example configuration of the security plugin's `config.yml` `authc` section with any sensitive data omitted?
