### ISSUE TITLE
[BUG] install_dashboards github action is not properly handling multi-digit major or minor versions

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security-dashboards-plugin#1532]
Now that 2.x is on 2.10, its exposed an issue on the `install-dashboards` Github Action which has logic to extract the branch name and major version from `package.json`. The commands are currently using `cut` and assuming that the major and minor versions are both single digits which is not the case now.

Problematic Block: https://github.com/opensearch-project/security-dashboards-plugin/blob/main/.github/actions/install-dashboards/action.yml#L41-L46

This is currently block the version increment PR in the 2.x branch: https://github.com/opensearch-project/security-dashboards-plugin/pull/1526

**Comment by RyanL1997** [comment]
Closing this due to the merge of #1537
