### ISSUE TITLE
[FEATURE] Mimic the pre-commit hooks from OpenSearch Dashboards

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security-dashboards-plugin#1539]
**Is your feature request related to a problem?**

There have been many instances of contributors pushing up code to review only to find issues with linting from failures in checks like Unit Tests and Integration Tests. In OpenSearch-Dashboards, automatic linting is performed as a pre-commit hook which ensures that there are no linting errors before pushing to a remote repository. 

**What solution would you like?**

This repo should mimic the same pre-commit hooks as OSD. Feature is requested here: https://github.com/opensearch-project/security-dashboards-plugin/pull/1538#discussion_r1282539144

**Do you have any additional context?**

I believe this is setup on `osd:bootstrap` [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/a52e95cbcc5075a4716274749d71d7d635704c4f/package.json#L75). I'm currently looking at other dashboards plugins repos to see if we can mimic a setup from another dashboards plugin repo.

**Comment by derek-ho** [comment]
Completed this in: https://github.com/opensearch-project/security-dashboards-plugin/pull/1851
