### ISSUE TITLE
[BUG] Selecting Tenant Erases NextURL

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1588]
**What is the bug?**
Selecting tenant pop-up erases nextURL parameter, which makes link sharing not work

**How can one reproduce the bug?**
copy a link to OSD specific page
Open in incognito and paste it in
login as any user
Select tenant
Redirection fails and user is landed at the linked hash, but everything else is lost

**What is the expected behavior?**
Selecting tenant has no effect on going to the link

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho, thank you for filing this issue. I believe that this behavior is consistent with redirecting the tenant to the default landing page when it is swapped. The only case this would not be expected would be when the tenant you are swapping to is the one that the nextURL should apply to. Can you clarify what types of scenarios you were discussing here? 

We may want to bring in UX for this discussion as well around the intended behavior.

**Comment by scrawfor99** [comment]
Closing this until further information can be provided about the scenarios where this issue was encountered. Please re-open if further details can be provided.
