### ISSUE TITLE
[BUG] Impossible to add customized permission group to a role

### ISSUE THREAD

**Issue by Kluk** [opensearch-project/security-dashboards-plugin#1597]
**What is the bug?**
Since the following feature was implemented https://github.com/opensearch-project/security-dashboards-plugin/issues/1346, it is not possible to add a customized permission group to a role, whether as cluster or index permissions.
When a customized permission group is created, it is not possible to manually assign it as cluster or index permission, and Dashboards does not define it automatically. So, when trying to add a customized permission group into the cluster permission or index permission field of a role, the permission group does not appear in the drop-down menu.

Here is a customized permission group containing only cluster permissions in OpenSearch Dashboards 2.9.0:
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5413585/aa62c107-061c-4836-b646-e1c46c8f109b)
The group is not detected as cluster permission even if it only contains cluster permissions.

Then, when trying to add it to a role, the permission group does not appear in the drop-down menu:
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5413585/24cbb4bf-a298-4f24-93da-c2c5808e45e7)

In OpenSearch Dashboards 2.7.0, it was still working:
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5413585/827830db-7f74-4235-a4ac-a011eedbfa95)

The same behaviour happens with a group containing index permissions.
Also, the feature linked above makes customized permission groups containing both cluster and index permissions completely useless.
A permission group containing both types of permission should be available in both drop-down menus or we should not be able to create them as they have no use.

**How can one reproduce the bug?**
1. Go to 'Management -> Security -> Permissions'
2. Create an action group containing cluster or index permissions.
3. Go to 'Management -> Security -> Roles'
4. Create or edit a role. Try to add the permission group to cluster or index permission.
5. See that it is not possible as the group does not appear in any drop-down menu.

**What is the expected behavior?**
Whether remove the feature https://github.com/opensearch-project/security-dashboards-plugin/issues/1346, or let us choose if a permission group is a cluster permissions group or an index permissions group. Or, let Dashboards choose regarding the type of permissions contained in the group and make it impossible to mix both types of permission.

**What is your host/environment?**
 - Docker version 24.0.6-rd, build da4c87c
 - OpenSearch version 2.9.0
 - OpenSearch Dashboards version 2.9.0

**Do you have any screenshots?**
Screenshots are linked above.

**Do you have any additional context?**
I was testing OpenSearch v2.9.0 with docker as I'm running OpenSearch 2.7.0 in AWS and I wanted to upgrade to version 2.9.0.
I will remove all my permission groups before the upgrade and add every permission manually to every role before the migration to avoid any issues generated by this bug. However, I still hope to be able to use permission groups in the future.

**Comment by scrawfor99** [comment]
[Triage] HI @Kluk, thank you for opening this issue. It sounds like this was previously working and now is not. We will investigate the potential regression and address it. Alternatively we can look into implementing this in a new feature if not previously supported.

**Comment by derek-ho** [comment]
@Kluk able to replicate this, will work on getting a fix out ASAP
