### ISSUE TITLE
[CI] Re-enable Cypress workflow run

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security-dashboards-plugin#1612]
Cypress workflows have been disabled temporarily to avoid blocking CI due to https://github.com/opensearch-project/security-dashboards-plugin/issues/1599. This issue serves as a reminder that once the cypress issues are resolved, Cypress workflows should be re-enabled.

**Comment by scrawfor99** [comment]
[Triage] Thanks @DarshitChanpura for filing this issue as a reminder. If you can link the Cypress fix that will tell us we are good to re-enable that would be great. 

Thank you again.

**Comment by cwperks** [comment]
Closing as a duplicate of https://github.com/opensearch-project/security-dashboards-plugin/issues/1599
