### ISSUE TITLE
[BUG] 2.11 Deleting log type fails

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/security-dashboards-plugin#1615]
**What is the bug?**

Latest release of Brave:

https://github.com/opensearch-project/security-dashboards-plugin/assets/2643715/22ab82a8-194b-499e-a0fb-b40df4e01bad

**What is the expected behavior?**

**What is your host/environment?**
2.11

**Do you have any screenshots?**
^^

**Do you have any additional context?**
^^

**Comment by ict-one-nl** [comment]
Should have created this in: https://github.com/opensearch-project/security-analytics-dashboards-plugin could someone move this?

**Comment by davidlago** [comment]
@opensearch-project/triage could you please help us move this to the [security-analytics-dashboards-plugin](https://github.com/opensearch-project/security-analytics-dashboards-plugin) repo?

(@lezzago @sbcd90 FYI)
