### ISSUE TITLE
[FEATURE] Add UI support to add existing roles while creating a user

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1628]
**Is your feature request related to a problem?**
Currently, mapping a user to a role via the UI involves two steps:
1. Create the user
2. Map the user to the role

https://opensearch.org/docs/latest/security/access-control/api/#create-user - there is existing functionality that allows you to pass in existing roles when creating a user - this should be available on the UI as well

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by cwperks** [comment]
[Triage] Thank you for filing the issue @derek-ho. If you have any suggestions for UX around the issue please add to the description to make it clear what acceptance for this issue would look like.
