### ISSUE TITLE
Change security-auditlog-* index replicas

### ISSUE THREAD

**Issue by orest-gulman** [opensearch-project/security-dashboards-plugin#164]
It would be good to have a possibility for managing a template or setting that indicates count of replicas.
https://discuss.opendistrocommunity.dev/t/change-security-auditlog-index-replicas/1799

**Comment by davidlago** [comment]
Closing as solved via workaround [here](https://forum.opensearch.org/t/change-security-auditlog-index-replicas/1799/6)
