### ISSUE TITLE
`Global` showing in user dropdown when multi-tenancy is disabled

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security-dashboards-plugin#1640]
I noticed that when running OpenSearch-Dashboards with multi-tenancy disabled, that the text `Global` appears when clicking on the user dropdown.

<img width="213" alt="Screenshot 2023-11-03 at 10 09 38 AM" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/17432265/66060d76-f9f8-408a-8bd5-00125e26b280">

`Global` is multi-tenancy specific text to indicate that any dashboards or visualizations are viewable by everyone else with access to the global tenant. When multi-tenancy is disabled, I would not expect any multi-tenancy specific language in the User dropdown.

One Option: Since multi-tenancy is now dynamic, it may be possible to link to the admin page in security to learn more about multi-tenancy.

Acceptance Criteria:

- [ ] Propose new UX to replace the text `Global` when multi-tenancy is disabled
- [ ] Submit a PR that implements the new UX

**Comment by scrawfor99** [comment]
[Triage] This seems like a good first issue. Thank you for filing this issue @cwperks.

**Comment by cwperks** [comment]
@derek-ho Could this be the case if multi-tenancy is dynamically changed from enabled to disabled?

**Comment by derek-ho** [comment]
@cwperks understood your point, and was able to replicate the bug. My proposed UX would be just to remove the "Global", or whatever tenant text is there entirely, similar to how the "Switch Tenants" option in the dropdown is not present at all when dynamically changed. I will raise a PR following this idea.
