### ISSUE TITLE
[Enhancement] Implement Cypress 13 frame work to security dashboard plugin

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security-dashboards-plugin#1655]
### Description
Implement Cypress 13 frame work to security dashboard plugin

Related PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/1579

### Exit Criteria
- [ ] Setup the Cypress 13 env in security frontend
- [ ] Setup the E2E OIDC functional test workflow for Linux
- [ ] Refactor the E2E SAML functional test workflow for Linux

**Comment by davidlago** [comment]
[Grooming] This does not include Windows runner work, to be split off in its own issue by @RyanL1997
