### ISSUE TITLE
[FEATURE] open up api to create/request iframe url

### ISSUE THREAD

**Issue by Scarehcrow** [opensearch-project/security-dashboards-plugin#1665]
**Is your feature request related to a problem?**
I've created dashboards with the python library, now that I want to share a dashboard with a predefined specific filter already in place I'm stuck. 
I can click the share button in the dashboard page and copy the short url but there is no way to automate this process.

**What solution would you like?**
Make the api available as for the visualisation and dashboard:
:5601/api/saved_objects/dashboard and :5601/api/saved_objects/visualiszation
eg: :5601/api/saved_objects/url (to create the short url)

**What alternatives have you considered?**
uploading an ndjson file via python for creating the url, but that failed aswell.

**Do you have any additional context?**
basicly the screenshot options should be in the API: 
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/86321364/956e652e-b484-4b31-baa8-13ac57c122ca)

**Comment by cwperks** [comment]
[Triage] Thank you for filing @Scarehcrow. Linking to an [RFC for workspaces](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298) in opensearch-dashboards which can take this feature request into account. 

Closing this issue. The sharing feature will be replaced with workspaces and only bug fixes are going into the sharing feature of multi-tenancy.
