### ISSUE TITLE
[Enhancement] Add Multi-Auth integration test into e2e functional testing by using Cypress 13

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security-dashboards-plugin#1667]
**Is your feature request related to a problem?**
In #1655, it introduced two new e2e workflows for testing external auths of OIDC and SAML for Security frontend. And the security frontend also contains the test of `saml_multiauth` (see [here](https://github.com/opensearch-project/security-dashboards-plugin/blob/main/test/jest_integration/saml_multiauth.test.ts)). We should transfer this into another e2e workflow and also add the coverage for OIDC when multi-auth is configured.

**Pre-requisite**
* The merge of https://github.com/opensearch-project/security-dashboards-plugin/pull/1579

**Exit Criteria**
- [ ] Refactor the `saml_multiauth` test into a e2e cypress workflow
- [ ] Add the coverage for OIDC when multi-auth is enabled

**Comment by cwperks** [comment]
Closing since https://github.com/opensearch-project/security-dashboards-plugin/pull/1729 has been merged.
