### ISSUE TITLE
`system:admin/system_index` permission not visible in index-permissions drop down

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security-dashboards-plugin#1697]
## Description

We are unable to grant system index permission to a role via dashboard since the permission `system:admin/system_index` is not visible in the dropdown list.

![Screenshot 2023-12-13 at 6 17 54 PM](https://github.com/opensearch-project/security-dashboards-plugin/assets/35282393/b0e234c7-df11-4b26-b72e-0e81e6aeaf36)

## What is expected?
- [ ] The permission `system:admin/system_index` should be visible in index permissions drop down.

**Comment by peternied** [comment]
[Triage] Thanks for filing - and thanks for the pull request.
