### ISSUE TITLE
Kibana status is Yellow - plugin:opendistro_security@6.6.2 Setting up index template.

### ISSUE THREAD

**Issue by shadowlord017** [opensearch-project/security-dashboards-plugin#17]
ES cluster failed and was restarted. After ES cluster was restored (green), kibana said "Tenant indicies migration failed". After kibana was restarted - now it says "Setting up index template" for 
plugin:opendistro_security@6.6.2
ES indices are all green

opendistroforelasticsearch-kibana.x86_64 0:0.8.0-1

**Comment by sgavrylenko** [comment]
have the same issue, after hosts reboot, in web interface of kibana status is yellow
in list of plugins status I can see

plugin:opendistro_security@6.7.1 | Setting up index template

but at the same time in logs of elastic presents "Cluster health status changed from [YELLOW] to [GREEN]"

**Comment by sgavrylenko** [comment]
fixed. In my case in kibana output was presents message 
`{"type":"log","@timestamp":"2019-06-05T19:35:46Z","tags":["warning","migrations"],"pid":1,"message":"Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_-1139641934_admin_16 and restarting Kibana."}`

after removing this index the problem gone away

**Comment by mporracindie** [comment]
This keeps happening to me and the solution is always as @shadowlord017 mention, deleting this index. 
Does anyone have an idea on why this is happening? How can we avoid it?

**Comment by manishvtr** [comment]
getting error in Kibana plugin status


plugin:opendistro_security@6.7.1 | Setting up index template.
