### ISSUE TITLE
[BUG] Misleading error message - Search error instead of Permission denied in dashboards

### ISSUE THREAD

**Issue by aggarwalShivani** [opensearch-project/security-dashboards-plugin#1700]
(Raised new issue as the [older one](https://github.com/opensearch-project/security-dashboards-plugin/issues/1000) could not be reopened)

**What is the bug?**
When a user tries to **access** an index-pattern on dashboards for which they **do not have read permission**, then it displays **"Search Error" with a stacktrace.** 
<img width="406" alt="image" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/39588384/c5e7a09f-faf8-4baa-9c88-eb7b28ae6151">

**Problem**
This is quite a misleading message and it would have been better to specify a Permission issue instead.

This behaviour has been running since Kibana versions > 7.8.
With kibana 7.8, on such a scenario, a clear permission error was displayed on the UI.

<img width="532" alt="image" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/39588384/0ff417bf-4e3f-4522-961d-905ba0a10a14">

**How can one reproduce the bug?**
1. Install Opensearch, Opensearch-dashboards with security enabled
2. As admin user, create indices like log-default-17.12.2023 and test-default-17.12.2023.
3. Login to Opensearch-dashboards as admin user and create index patterns like log* and test* for the two indices respectively.
4. Create a user (say testuser) with read-write permissions only to log*
5. Login to Opensearch-dashboards UI **with testuser** and try to access the index pattern test* ( i.e. for which user has no permission.

**What is the expected behavior?**
A clear error message that, atleast indicates that it is related to permissions, must be displayed.
In opensearch pod logs, it does display that user didnt have permission for the required operation. However, the same is not displayed on Opensearch dashboards UI.

**What is your host/environment?**
 - OS: rocky8
 - Version: 2.11.0
 - Plugins: Opensearch, Opensearch-dashboards with their rspective security plugins 

**Do you have any screenshots?**
Attached.

**Do you have any additional context?**
Ref to previous tickets raised for this 
- https://forum.opensearch.org/t/permission-denied-error-message-is-not-displayed-in-dashboard/14171
- https://github.com/opensearch-project/security-dashboards-plugin/issues/1000 (had got closed due to inactivity)

**Comment by mrudrego** [comment]
@peternied  can you please assign this issue to me, i'm can work on this ?

Thanks,

**Comment by peternied** [comment]
@mrudrego Thanks - I've assigned this issue to you, looking forward to seeing a PR

**Comment by mrudrego** [comment]
@peternied , the behaviour on the main branch of code has changed. When a user tries to access an index for which they do not have permission, we get **Forbidden** message as below.
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/20531270/3bf92998-d1c6-40a1-a45e-0e3df4cde090)

I hope this is expected behaviour.

Only small concern/query is about the stacktrace showing the complete source code of the file. Can this cause any security issue?

Thanks,

**Comment by peternied** [comment]
@mrudrego That code is executed on the client side - there is no way to keep the call stack 'hidden' because the browser is executing it, nothing unexpected there - good question.

**Comment by mrudrego** [comment]
@peternied  thanks for the response.
So i think we can close this bug since the fix is already available in the main branch and working as expected.
