### ISSUE TITLE
[BUG] Run CI checks after building OSD, security-dashboards-plugin zip and installing with the ./bin/opensearch-dashboards-plugin install file:/path/to/security-dashboards-plugin.zip

### ISSUE THREAD

**Issue by cwperks** [opensearch-project/security-dashboards-plugin#1709]
**What is the bug?**

When security-dashboards-plugin runs OpenSearch-Dashboards w/ the security dashboards plugin installed, it starts OSD using `yarn start` instead of a built version of OSD and using the executable script `./bin/opensearch-dashboards`. 

There's been a couple of issues that have slipped by the CI checks that would be caught with this.

- https://github.com/opensearch-project/security-dashboards-plugin/issues/1704
- https://github.com/opensearch-project/security-dashboards-plugin/issues/1487

The CI checks should be refactored to build OSD, security-dashboards-plugin and install the dashboards plugin using the dashboards-plugin install executable. 

1. In OSD-Core run `yarn build`. Output is in `./build/opensearch-dashboards-{version}-{platform}-{architecture}/`
2. In security-dashboards-plugin run `yarn build`. Output is in `./build/security-dashboards-{version}.zip`
3. Install the dashboards plugin. In `./build/opensearch-dashboards-{version}-{platform}-{architecture}/` run `./bin/opensearch-dashboards-plugin install file:/path/to/security-dashboards-plugin.zip`
4. Run OSD with `./bin/opensearch-dashboards`

**Comment by scrawfor99** [comment]
[Triage] Hi @cwperks, thanks for filing this issue. This is a great issue since it will help us have more affective testing.
