### ISSUE TITLE
[BUG] Spelling mistakes in server/ folder code

### ISSUE THREAD

**Issue by shoustech** [opensearch-project/security-dashboards-plugin#1740]
**What is the bug?**
Hello All! I feel that this is a minor thing but I thought it might be good to bring to attention spelling mistakes that I am finding in variables / comments. I have provided a list of files that I found in the `server/` folder of the plugin that had mis-spelt variables.

**How can one reproduce the bug?**
Open one of the files at the line number that I have provided below. You will find the spelling mistake on that line. 

**Do you have any additional context?**
Correct `additonal` to `additional`
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/authentication_type.ts#L120
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/authentication_type.ts#L121
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/authentication_type.ts#L122
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/authentication_type.ts#L170
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/authentication_type.ts#L171

Correct `availabe` to `available`
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/authentication_type.ts#L260C2-L260C2
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/tenant_resolver.ts#L34
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/tenant_resolver.ts#L48
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/tenant_resolver.ts#L58
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/tenant_resolver.ts#L99
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/basic/routes.ts#L126
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/basic/routes.ts#L216

Correct `endpont` to `endpoint`
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/openid/helper.ts#L117
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/auth/types/openid/helper.ts#L118

Correct `teanats` to `tenants`
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/backend/opensearch_security_client.ts#L79

Correct `stroage` to `storage`
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/routes.ts#L24
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/routes.ts#L47C43-L47C43
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/routes.ts#L56
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/routes.ts#L72

Correct `configuratoin` to `configuration`
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/plugin.ts#L32
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/plugin.ts#L97

Correct `tenent` to `tenant`
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/tenant_index.ts#L82
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/tenant_index.ts#L84
https://github.com/opensearch-project/security-dashboards-plugin/blob/3f81415d6c77bb275b3d3a84a8409cccdc30a7a1/server/multitenancy/tenant_index.ts#L97

**Comment by scrawfor99** [comment]
[Triage] Hi @shoustech, thanks for finding these typos. Feel free to open a pull request to address these typos! We will happily review :)
