### ISSUE TITLE
[FEATURE] Is es-lint-plugin-cypress dependency used?

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1745]
**Is your feature request related to a problem?**
I noticed that there is this dependency: https://github.com/opensearch-project/security-dashboards-plugin/blob/main/package.json#L41 that seems not to be used. 
https://github.com/search?q=repo%3Aopensearch-project%2Fsecurity-dashboards-plugin+eslint-plugin-cypress&type=code

Can it be removed? Or at least moved to a dev dependency? By name it seems to only be used by cypress.

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho, nice catch. Seems like someone should go ahead and make sure that this is not needed and remove it if so.

**Comment by derek-ho** [comment]
Closing with the merge of: https://github.com/opensearch-project/security-dashboards-plugin/pull/1746
