### ISSUE TITLE
[BUG] Copying Short URL is not adding the security_tenant query parameter

### ISSUE THREAD

**Issue by devardee** [opensearch-project/security-dashboards-plugin#1769]
**What is the bug?**

In Dashboards, to share visualizations we generate short url's and click on `Copy link` button. The copied url is not adding the `security_tenant` query parameter.

**How can one reproduce the bug?**
Adding the screen capture

**What is the expected behavior?**
The copied link should have the `security_tenant` query parameter. So that the short link can be resolved correctly.

**What is your host/environment?**
 - OS: iOS
 - Version: mainline [3.0.0]
 - Plugins: security plugin

**Do you have any screenshots?**
Yes

https://github.com/opensearch-project/security-dashboards-plugin/assets/80896069/2212cf20-afd4-47b5-982e-001eb2b0fccf

**Do you have any additional context?**
No

**Comment by cwperks** [comment]
@devardee There was a recent PR related to tenancy and short links that should resolve the tenant when the short URL is used: https://github.com/opensearch-project/security-dashboards-plugin/pull/1462

**Comment by scrawfor99** [comment]
[Triage] Hi @devardee, thanks for filing an issue. We can probably resolve this issue in a similar way to #1462, so we can close this when a fix is put in place to correct this behavior.

**Comment by cwperks** [comment]
I reproduced the error on the 2.12 release and see this error in the dashboards logs.

```
opensearch-dashboards-1  | {"type":"log","@timestamp":"2024-02-23T15:50:14Z","tags":["error","http","server","OpenSearchDashboards"],"pid":1,"message":"TypeError: Cannot read properties of undefined (reading 'location')\n    at addTenantParameterToResolvedShortLink (/usr/share/opensearch-dashboards/plugins/securityDashboards/server/multitenancy/tenant_resolver.ts:213:46)\n    at /usr/share/opensearch-dashboards/plugins/securityDashboards/server/plugin.ts:130:46\n    at interceptPreResponse (/usr/share/opensearch-dashboards/src/core/server/http/lifecycle/on_pre_response.js:107:30)\n    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:57:29)\n    at Request._invoke (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:398:55)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Request._postCycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:469:32)\n    at Request._reply (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:448:9)"
```

**Comment by derek-ho** [comment]
Completed by @cwperks in: https://github.com/opensearch-project/security-dashboards-plugin/pull/1804
