### ISSUE TITLE
[BUG] cypress-test workflow failing on main 

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1779]
**What is the bug?**
Cypress-test workflow started failing on main. This needs to be looked into/resolved. It doesn't seem to affect 2.x line, so there may have been some change upstream on OSD or FTR. 

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho, thank you for filing this issue. Since this is about a failing workflow we can close this issue once the workflow is fixed. Reproduction steps would then be to make a change to trigger the workflow and review the logs.

**Comment by derek-ho** [comment]
Doing what the github runner is doing under the hood succeeds:

```
runner@fv-az1391-58:~/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/opensearch-dashboards-functional-test$ curl -XPOST http://localhost:5601/api/saved_objects/index-pattern/index-pattern1 -H "osd-xsrf: true" -H "Content-Type: application/json" -d '{"attributes": {"title": "s*", "timeFieldName": "timestamp"}, "references": []}' -u "admin:testPassword123_"
{"statusCode":401,"error":"Unauthorized","message":"Authentication Exception"}runner@fv-az1391-58:~/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/opensearch-dashboards-functional-test$ curl -XPOST http://localhost:5601/api/saved_objects/index-pattern/index-pattern1 -H "osd-xsrf: true" -H "Content-Type: application/json" -d '{"attributes": {"title": "s*", "timeFieldName": "timestamp"}, "references": []}' -u "admin:myStrongPassword123!"
{"type":"index-pattern","id":"index-pattern1","attributes":{"title":"s*","timeFieldName":"timestamp"},"references":[],"migrationVersion":{"index-pattern":"7.6.0"},"updated_at":"2024-02-12T21:45:29.096Z","version":"WzAsMV0=","namespaces":[["__user__admin"]]}```
```
