### ISSUE TITLE
[Review Needed] Review the RFC to introduce application level configuration at OSD

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/security-dashboards-plugin#1791]
Hi, team

Please review this RFC introduce application level configuration at OSD https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5796

Once you review the proposal and raise concern if any, then you can resolve this issue.

**Comment by derek-ho** [comment]
[Triage] This is related to the OSD campaign to support hot reloading of settings in security dashboards plugin - we have several settings that we shouldn't hot reload, so we need to get more details about this feature overall. @cwperks mentioned that we have a separate section for this - and we may want to look into migrating or commenting more about our concerns in the meta.

**Comment by scrawfor99** [comment]
[Triage] Hi @tianleh going to close this since it seems like this is complete.

**Comment by cwperks** [comment]
@tianleh I added a [comment](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5796#issuecomment-1977051904) on the issue in OSD core to provide context on how security-dashboards-plugin achieves dynamic configuration for some of its config values.
