### ISSUE TITLE
[FEATURE] Support multiple datasources in the "Service Accounts" tab

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1799]
**Is your feature request related to a problem?**
Support multiple datasources functionality in the "Service Accounts" tab. 

**Acceptance criteria**
- Data source picker shared component is present on the page with a sensible UX
- Data source selections that should be persisted across tabs is accurately persisted
- Selected datasource prior to landing on this page is correctly populated (if applicable), and defaults are selected if not applicable

**What solution would you like?**
Support multiple datasources in the "Service Accounts" tab. 

**What alternatives have you considered?**
None

**Do you have any additional context?**
Depends on #1795 to have data source picker available.

**Comment by derek-ho** [comment]
@cwperks can you provide some color here on whether you think this is appropriate? I see that this was not backported to 2.x and the UI seems to have limited functionality. Is there a reason why this isn't backported? Does it make sense to keep it in main but not 2.x and if we keep it should we support multiple datasources for it?

**Comment by cwperks** [comment]
@derek-ho The selector should be on all pages including this one, but the other pages have priority. I left some thoughts on the original PR [here](https://github.com/opensearch-project/security-dashboards-plugin/pull/1502#issuecomment-1775726390). IMO it has limited support atm so I don't think it should be backported to 2.x and perhaps reverted if there is no plan for long term support.

**Comment by derek-ho** [comment]
[Triage] This is part of the meta of supporting multi datasources in the security plugin.

**Comment by zhongnansu** [comment]
Hi Derek, is this completed by #1870, can we close? @derek-ho

**Comment by derek-ho** [comment]
Code in feature branch not in main yet, closing
