### ISSUE TITLE
[FEATURE] Purge cache should have confirmation or Toast

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1815]
**Is your feature request related to a problem?**
The purge cache button on the "Get Started" page purges the cache. However, there is no confirmation modal that they are sure they want to purge the cache. There is also no toast indication that the purge was successful or errored out, even though the network call is coming back. We should add these to give a better user experience. We should also add it to make multi-datasource cache purging more clear/user friendly.

**What solution would you like?**
Modal confirmation to purge the cache and/or toast message with success or error message.

**What alternatives have you considered?**
None

**Do you have any additional context?**
None

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho, thank you for filing this issue. This seems like a great improvement for users.
