### ISSUE TITLE
[BUG] Documentation for developer guide needs to be corrected

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security-dashboards-plugin#1830]
**What is the bug?**
Currently the developer guide for both the security and security-dashboards repos is outdated. 

Aside from some small phrases which are no longer accurate (i.e. recent versions), there are also some aspects that are no longer supported. 

Specifically in the dashboards doc, we state:

> Next, checkout the [1.x branch](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/1.x) from OpenSearch-Dashboards repo. Follow the [developer guide](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.x/DEVELOPER_GUIDE.md) and replace the version of `opensearch-dashboards.yml` there with this:

```
server.host: "0"
opensearch.hosts: ["https://localhost:9200"]
opensearch.ssl.verificationMode: none
opensearch.username: "kibanaserver"
opensearch.password: "kibanaserver"
opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
opensearch_security.readonly_mode.roles: ["kibana_read_only"]

# Use this setting if you are running opensearch-dashboards without https
opensearch_security.cookie.secure: false
```

This will throw an error since "0" is not considered a valid host by dashboards core anymore. We should update this and any other info. I also suggest we focus on 2.x instead of the no longer developed 1.x line.

**Comment by cwperks** [comment]
[Triage] Thank you for filing this issue @scrawfor99 . Will you be submitting a PR to resolve this issue?

**Comment by scrawfor99** [comment]
It looks like @cwperks already took care of this?

**Comment by derek-ho** [comment]
Can confirm I am seeing this on main, closing
