### ISSUE TITLE
java.lang.IllegalStateException: Username cannot have '|' in the security plugin.

### ISSUE THREAD

**Issue by karthikeayan** [opensearch-project/security-dashboards-plugin#184]
Elasticsearch Version: 7.4
Platform: AWS

Authentication: AWS Cognito with Open ID connect(Auth0)

When:
Only when fine grained access control enabled

**Comment by bdellegrazie** [comment]
hi @seraphjiang can you please explain why you've tagged this as "wontfix"?

It's impossible to authenticate from an external IdP using Cognito without this capability.

**Comment by debjanibnrj** [comment]
As of now "|" is a reserved character and can’t be supported in username.

**Comment by bdellegrazie** [comment]
@seraphjiang : could you use the `sub` field instead - isn't that what's for?

For anyone else having to deal with this - I'm connecting Auth0 to Cognito and then OpenDistro is authenticating against Cognito.
I worked around this as follows:
* SAML integration from Auth0 to Cognito
However I manipulated the SAML on the Auth0 side to permit _only_ the email claim as the `nameidentifier`. This means the username in Cognito ends up as the email address prefixed by the SAML integration name, separated by a hyphen.

Couldn't use OIDC integration in Auth0 as it doesn't let me modify the username claim passed through to Cognito.

**Comment by cliu123** [comment]
This is not something that can be fixed because `|` is a reserved character. It's nice that there's a workaround above.
