### ISSUE TITLE
[BUG] Automatic login as anonymous user when passing wrong username and password

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security-dashboards-plugin#1840]
With anonymous auth enabled, a user is automatically logged in as `opendistro_security_anonymous` upon passing wrong crendentials. See the attached video:

https://github.com/opensearch-project/security-dashboards-plugin/assets/35282393/210a838f-0c8c-44e7-a1fa-c1c72d86d8c0

#### Steps to reproduce:
1. Download docker-compose.yml for opensearch.
2. Ensure the image points to staging repository and version 3.0.0
3. Spin-up the cluster (ensure anonymous auth is enabled)
4. Pass random username + password in the basic authentication form.
5. Check that you are logged in as anonymous.

### Exit Criteria:
- [ ] Upon failed login, user should not be logged in as anonymous user.

**Comment by scrawfor99** [comment]
[Triage] Hi @DarshitChanpura, thank you for filing this issue. This sounds like a good issue to get fixed since this is likely unexpected.
