### ISSUE TITLE
[Workspace] Migrate tenant data to workspace

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/security-dashboards-plugin#1847]
**Is your feature request related to a problem? Please describe.**

As workspace and multi-tenancy are mutually exclusive, they can't turn on at the same time.

Data is inside of a tenant cannot be accessed when multi-tenancy is disabled. We need find out a way to help users migrate tenant data to workspace

**Describe the solution you'd like**

**Describe alternatives you've considered**

As a workaround, user can export all saved objects from `saved objects` page under `Management/Dashboards Management` before turn on workspace and import it to workspace afterwards.

**Additional context**

https://github.com/opensearch-project/security-dashboards-plugin/pull/1822
opensearch-project/OpenSearch-Dashboards#4944

**Comment by scrawfor99** [comment]
[Triage] Hi @Hailong-am, thank you for filing this issue. It sounds like this work is based on supporting the workspace feature deployment. Is there someone from the owning team/group that can help provide details for how this is being done elsewhere or otherwise work with the Security plugin for this feature request?

**Comment by Hailong-am** [comment]
> [Triage] Hi @Hailong-am, thank you for filing this issue. It sounds like this work is based on supporting the workspace feature deployment. As is, workspaces is not a security-dashboards/security feature. This work would probably be best assigned under the umbrella of the workspaces change. The security plugin can look into deprecating multi-tenancy once workspaces is launched, but the actual development of this support would likely fall under the workspace development not the security plugin.

@scrawfor99  Two reasons here:
1. workspaces don't have access to tenant data, it's more reasonable for dashbaord-security plugin to read tenant data and migrate it to workspace, workspace plugin could provide some functions to do the actual migration and that need dashboard-security plugin call those functions.
2. the UX and how to implement this has not decided yet. It's used for tracking purpose at this moment.

**Comment by scrawfor99** [comment]
@peternied could you look at the above see what you think?

**Comment by peternied** [comment]
Being that there are no details on how to accomplish this issue - it does not meet out triage requirements.  I'm recommending closing this issue out.

@Hailong-am For project planning / tracking issues associated with Workspaces please add them to your tracking mechanism of choice.

**Comment by scrawfor99** [comment]
[Triage] Going to close this issue for the reasons discussed above. Thanks.
