### ISSUE TITLE
[BUG][Doc] AuthenticationType class has an invalid doc link

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/security-dashboards-plugin#1850]
**What is the bug?**

This bug is about the comment in the code which contains an invalid doc link. 

https://github.com/opensearch-project/security-dashboards-plugin/blob/3bff6dbd139b782988c80284c702b9261ab2f267/server/auth/types/authentication_type.ts#L117

We shall either remove it or replace it with a valid link.

**How can one reproduce the bug?**

Check the code link https://github.com/opensearch-project/security-dashboards-plugin/blob/3bff6dbd139b782988c80284c702b9261ab2f267/server/auth/types/authentication_type.ts#L117

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Hi @tianleh thanks for finding this issue. Please feel free to create a PR directing to the correct OpenSearch.org url.
