### ISSUE TITLE
[FEATURE] [MDS] add support to read/set dataSourceId in the URL

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1858]
**Is your feature request related to a problem?**
If a create page/view/edit page is shared as a link, when somebody else opens it up they may not be looking at the correct context. If it is set/read from the URL that would help things. It would also help in cases of logout not to lose context. 

**What solution would you like?**
Set/read the current datasource from the URL

**What alternatives have you considered?**
Local storage, session storage, but this wouldn't be shared across sharing

**Do you have any additional context?**

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho thanks for filing this issue. This makes sense as it would allow users to share the datasource they want to reference when passing URLs. We will need to figure out cases where a datasource is not accessible for the receiving user (i.e. the person who gets the link does not have access to the datasource).

**Comment by derek-ho** [comment]
Merged into feature branch
