### ISSUE TITLE
Inspect stig profile is failed for the open distro kibana version

### ISSUE THREAD

**Issue by RajendraLadkat** [opensearch-project/security-dashboards-plugin#186]
We are using opendistro kibana and elasticsearch version. Inspect test for kibana home is failing. As per the version of kibana 0.9.0 its home is /usr/share/kibana instead of /home/kibana.
Due to this when we try to build kibana docker image using RHEL 7.2 as a base image it will file the stig test for kibana home. we defined the kibana home as /usr/share/kibana in test but as during kibana user creation inside docker image its default home inside /etc/passwd is /home/kibana instead of /usr/share/kibana. Due to this stig test is failed

**Comment by davidlago** [comment]
Lots of things have changed since this issue was open (apologies for the very late reply!) and we have been successfully building the now named OpenSearch Dashboards as docker images without issues. If this persists in today's post-ODFE versions, please open a new issue.
