### ISSUE TITLE
Change plugin name to use same version number as Alerting (or remove version altogether)

### ISSUE THREAD

**Issue by DanielLeeJM** [opensearch-project/security-dashboards-plugin#19]
When attempting to uninstall kibana plugin for security, the following is observed:

[@localhost kibana]$ sudo bin/kibana-plugin list
opendistro-alerting@0.9.0.0
opendistro_security@6.7.1
[@localhost kibana]$ sudo bin/kibana-plugin remove opendistro_security@6.7.1
Unable to remove plugin because of error: "Plugin [opendistro_security@6.7.1] is not installed"

The correct way to remove this plugin is to use:
[@localhost kibana]$ sudo bin/kibana-plugin remove opendistro_security

The expected way to remove this plugin is to use:
[@localhost kibana]$ sudo bin/kibana-plugin remove opendistro_security@6.7.1

Please amend the name so the expected behaviour is observed.

In addition: 
Kibana fails to restart after uninstallation, Kibana status from systemctl status kibana.service returns green but cannot be accessed via browser at localhost:5601. Kibana is not ready and constantly attempts to restart.
Log files from running:

journalctl -u kibana.service 

May 24 16:59:48 localhost.localdomain kibana[18792]: {"type":"log","@timestamp":"2019-05-24T08:59:48Z","tags":["plugin","warning"],"pid":18792,"path":"/usr/share/kibana/src/legacy/core_plugins/ems_util","message
May 24 16:59:50 localhost.localdomain kibana[18792]: {"type":"log","@timestamp":"2019-05-24T08:59:50Z","tags":["fatal","root"],"pid":18792,"message":"{ [Error: EACCES: permission denied, rmdir '/usr/share/kibana
May 24 16:59:50 localhost.localdomain kibana[18792]: FATAL  Error: EACCES: permission denied, rmdir '/usr/share/kibana/optimize/bundles/src/ui'
May 24 16:59:50 localhost.localdomain systemd[1]: kibana.service: main process exited, code=exited, status=1/FAILURE
May 24 16:59:50 localhost.localdomain systemd[1]: Unit kibana.service entered failed state.
May 24 16:59:50 localhost.localdomain systemd[1]: kibana.service failed.
May 24 16:59:50 localhost.localdomain systemd[1]: kibana.service holdoff time over, scheduling restart.
May 24 16:59:50 localhost.localdomain systemd[1]: Stopped Kibana.
May 24 16:59:50 localhost.localdomain systemd[1]: Started Kibana.
May 24 17:00:00 localhost.localdomain kibana[18805]: {"type":"log","@timestamp":"2019-05-24T09:00:00Z","tags":["plugin","warning"],"pid":18805,"path":"/usr/share/kibana/src/legacy/core_plugins/ems_util","message
May 24 17:00:01 localhost.localdomain kibana[18805]: {"type":"log","@timestamp":"2019-05-24T09:00:01Z","tags":["fatal","root"],"pid":18805,"message":"{ [Error: EACCES: permission denied, rmdir '/usr/share/kibana
May 24 17:00:01 localhost.localdomain kibana[18805]: FATAL  Error: EACCES: permission denied, rmdir '/usr/share/kibana/optimize/bundles/src/ui'
May 24 17:00:01 localhost.localdomain systemd[1]: kibana.service: main process exited, code=exited, status=1/FAILURE
May 24 17:00:01 localhost.localdomain systemd[1]: Unit kibana.service entered failed state.
May 24 17:00:01 localhost.localdomain systemd[1]: kibana.service failed.
May 24 17:00:02 localhost.localdomain systemd[1]: kibana.service holdoff time over, scheduling restart.
May 24 17:00:02 localhost.localdomain systemd[1]: Stopped Kibana.
May 24 17:00:02 localhost.localdomain systemd[1]: Started Kibana.

This will continue looping. The fix is to change permissions of folder "'/usr/share/kibana/optimize/bundles/src/ui" by recursively invoking chmod over the optimize folder. 
sudo chmod -R 777 optimize
sudo systemctl stop kibana.service
sudo systemctl start kibana.service

After waiting several minutes, kibana will restart as expected.

**Comment by aetter** [comment]
Hi @DanielLeeJM, I'm not able to reproduce the permissions error on the optimize directory on a new RHEL 8 machine. Provided I run everything with sudo, everything seems to remove/restart cleanly.

That said, I absolutely agree that we should change the Kibana plugin names to follow the same standard we have on the Elasticsearch side. So if we have to include a version, it should be `opendistro_alerting@0.9.0.0` and `opendistro_security@0.9.0.0`. Even better would be `opendistro_alerting` and `opendistro_security`.

Current output (note the lack of naming consistency on the Kibana side):

```bash
./bin/elasticsearch-plugin list
opendistro_alerting
opendistro_performance_analyzer
opendistro_security
opendistro_sql

./bin/kibana-plugin list
opendistro-alerting@0.9.0.0
opendistro_security@6.7.1
```

**Comment by davidlago** [comment]
There have been a lot of renames fro opendistro to opensearch. If the problem persists today with OpenSearch naming, please feel free to open a new issue. Thanks!
