### ISSUE TITLE
[BUG] SAML and SAML multi auth tests are flaky

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1900]
Starting from today, I started seeing errors/timeouts in the following tests: 

Snapshot based E2E SAML tests workflow / Run Cypress E2E SAML tests

Snapshot based E2E SAML multi-auth tests workflow / Run Cypress E2E SAML multi-auth tests 

We should look into these failures and fix any issues that could be causing flakiness. @DarshitChanpura recently had changes around anonymous and saml auth, which may or may not be related. PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/1839

**Comment by derek-ho** [comment]
Fix: https://github.com/opensearch-project/security/pull/4269#pullrequestreview-2011545784

**Comment by scrawfor99** [comment]
[Triage] HI @derek-ho thank for filing this issue. Looks like this has been resolved.
