### ISSUE TITLE
[FEATURE] [RFC] Investigate and clean up helper functions which are only used in one place

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1906]
**Is your feature request related to a problem?**
When adding MDS support for security dashboards plugins, almost all API calls had to be changed. When investigating these changes, I noticed a few things that could be improved:
- Some helper functions are not used at all (and may have been forgotten to be removed) - we should look into a linter rule that helps us find and remove these
- Some helper functions are defined and only used in one place (can we move them inline)? For example https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/apps/configuration/utils/role-list-utils.tsx#L108 - is only used in one place
- Some helper functions may be doing too simple of a job - for example httpGet helper function, which is simply extracting the `get` method off of the httpStart object, and calling another function with it - does this really need to exist, or can we change all calls to directly pass in the `get` method? Would this be more or less readable?

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho thanks for filing this issue. @derek-ho to add follow up so going to leave untriaged.
