### ISSUE TITLE
[BUG] [MDS] No available datasources or illegal datasource crashes the plugin

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1934]
**What is the bug?**
When no datasources available, or illegal option passed in via URL the plugin crashes

**How can one reproduce the bug?**
- enable MDS
- navigate to the security dashboards plugin
- Pass in either non-existent datasource, or no datasources connected
<img width="1512" alt="Screenshot 2024-05-01 at 11 18 39 AM" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/7cd284e9-7ec8-49a7-81b0-3f1ff3ebb1fa">

**What is the expected behavior?**

<img width="1150" alt="Screenshot 2024-04-19 at 11 16 01 AM" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/26328171/82d42366-06a2-41cd-9c1d-f598173a9bee">

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho thanks for filing this issue. The follow-up design you provided seems like a good way to handle this scenario and looks like you have a good start on this. Going to mark triaged.

**Comment by DarshitChanpura** [comment]
A way to reproduce this issue:
1. Log in as admin and create a user with `security_rest_api_access` role mapped to it (To be able to access the Security tab in left navigation pane)
2. Create a dataSource connection to another cluster, say 9202.
3. Now set 9202 as default dataSource.
4. Log out as admin and login as the newly created user.
5. Navigate to Security tab and you should see the following screen:
<img width="1440" alt="Screenshot 2024-05-07 at 2 30 26 PM" src="https://github.com/opensearch-project/security-dashboards-plugin/assets/35282393/95004964-e096-42d6-9dc3-0eb1754548eb">

**Comment by DarshitChanpura** [comment]
A BIG QUESTION here is if the user doesn't have access to default data-source then `Switch to default data-source` button is of no use since it will always bring you back to the same screen.

**Comment by scrawfor99** [comment]
@DarshitChanpura @derek-ho do we have the ability to fetch a list of accessible datasources based on permissions? For instance, can we know that User A definitely has access to Datasource 1? 

If so, we may be able to redirect to default if is accessible by the user and otherwise the last accessed datasource they have permission for? 

If not, I suggest we enforce access for a disconnected landing page all users can hit. Similar to the login screen where they are not yet auth'd we can kick them back to a landing page regardless of their permissions and then have deterministic behavior in the case where the datasource is not permitted.

**Comment by DarshitChanpura** [comment]
> do we have the ability to fetch a list of accessible datasources based on permissions? For instance, can we know that User A definitely has access to Datasource 1?

No we do not. DataSources information is stored as saved object inside the kibana and tenant index. When aggregation view is enabled, the user will require read permissions to the tenant which contains that particular datasource.

> If not, I suggest we enforce access for a disconnected landing page all users can hit. Similar to the login screen where they are not yet auth'd we can kick them back to a landing page regardless of their permissions and then have deterministic behavior in the case where the datasource is not permitted.

There is no way to enforce that right now, so instead we bring them to a page which allows them to switch to local cluster. This scenario will only be required when aggregation view is enabled. When it is disabled, the page auto-reloads with default datasource.

**Comment by DarshitChanpura** [comment]
Corresponding PR closed. No plan to fix.
