### ISSUE TITLE
[FEATURE] Add a view button for password input text-box

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security-dashboards-plugin#1940]
We should add a View button to password input field. This would allow users to peek at their typed password. 
Something like:
![Screenshot 2024-05-08 at 12 11 17 PM](https://github.com/opensearch-project/security-dashboards-plugin/assets/35282393/3c5eb6ab-de9f-4736-a952-d85f5c29b954)

The view button can be implemented as 1 of the 2 following behaviors:
1. Password is only visible when holding the view button down.
2. View button acts as a toggle between displaying password in plain-text and masking it.

**Comment by derek-ho** [comment]
Looks like this can help: https://oui.opensearch.org/1.0/#/forms/form-controls#password-field

**Comment by cwperks** [comment]
[Triage] Thank you for the feature request @DarshitChanpura. Does OUI currently support a reveal button?

**Comment by DarshitChanpura** [comment]
Yes, however OUI comes with its own set of web-pack compilation failures. We'll probly have to address those along-with this fix, if we plan to use the OUI component.
