### ISSUE TITLE
[BUG] Duplicate URL fragment when clicking on security plugin

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#1967]
**What is the bug?**
When visiting the security dashboards plugin, the url may look something like this:
http://localhost:5601/qml/app/security-dashboards-plugin#/qml/app/security-dashboards-plugin/getstarted

Instead it should look like this:
http://localhost:5601/qml/app/security-dashboards-plugin#/getstarted
**How can one reproduce the bug?**
Click on security dashboards plugin
Check URL

**What is the expected behavior?**
URL fragment is not duplicated
**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho thank you for filing this issue. This looks unintended and something that can be easily resolved by looking into the URL mapping setup.
