### ISSUE TITLE
[BUG] login failed: Invalid username or password 

### ISSUE THREAD

**Issue by datavisorzhenglanhou** [opensearch-project/security-dashboards-plugin#1968]
**Describe the bug**

login failed: Invalid username or password 

ERROR:
{"type":"log","@timestamp":"2024-05-18T12:56:30Z","tags":["error","plugins","securityDashboards"],"pid":40,"message":"Failed authentication: Error: GET /_plugins/_security/authinfo API not allowlisted"}

**Comment by scrawfor99** [comment]
[Triage] Hi @datavisorzhenglanhou, thank you for filing this issue. Unfortunately, there is not enough details shared to take any action here. This is probably a configuration issue. Going to close.
