### ISSUE TITLE
[BUG] Add security_tenant parameter for short links

### ISSUE THREAD

**Issue by mxmorin** [opensearch-project/security-dashboards-plugin#1970]
**Describe the bug**

When a link is generated on a dashboard or saved query, the initial tenant is not specified. A user whose current tenant is not that of the link cannot access the dashboard.
Adding the ?security_tenant parameter allows access to the dashboard
Could you add this parameter on all links ?

**Expected behavior**
The dashboard should be accessible regardless of the current tenant.

**OpenSearch Version**
2.12

**Dashboards Version**
2.12

**Comment by scrawfor99** [comment]
[Triage] Hi @mxmorin thank you for filing this issue. This seems like a reasonable feature to add. Please feel free to open a PR introducing this change for review.

**Comment by cwperks** [comment]
Hi @mxmorin, a fix for this issue was released in 2.13: https://github.com/opensearch-project/security-dashboards-plugin/pull/1804

**Comment by cwperks** [comment]
Closing as duplicate of https://github.com/opensearch-project/security-dashboards-plugin/issues/1769
