### ISSUE TITLE
[FEATURE] Support Version Decoupling in Security Dashboards Plugin

### ISSUE THREAD

**Issue by ZilongX** [opensearch-project/security-dashboards-plugin#1971]
**Is your feature request related to a problem?**
OpenSearch plugins currently tightly couple their versions with the underlying OpenSearch/OpenSearch Dashboards version. This tight coupling can lead to challenges in maintaining and upgrading plugins independently. To enable supporting of the decoupling of the plugin versions from the OpenSearch versions will allow for more flexibility in managing and updating plugins.

More details is available at RFC Plugins Version Decoupling - https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5877

**What solution would you like?**
Support version decoupling in the security dashboards plugin, where end users would be able to consume the latest version of security dashboards plugin with a range of supported OS versions instead of just one version

**What alternatives have you considered?**
More as detailed in [Plugins Version Decoupling](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5877)

**Do you have any additional context?**
More as detailed in [Plugins Version Decoupling](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5877)

**Comment by scrawfor99** [comment]
[Triage] This issue is part of the larger effort to support version decoupling in plugins.
