### ISSUE TITLE
Kibana Index management opendistro aws elasticsearch 7.4

### ISSUE THREAD

**Issue by R00T88** [opensearch-project/security-dashboards-plugin#198]
Hi all,
i have deployed aws elastichsearch 7.4 with opendistro Fine–grained access control with internal database.
i'm able to create index and upload doc without any problem but im not able as master user to view indices under index management tab to apply indices policy to them.

How can i view al indices present into it?

Thanks

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
