### ISSUE TITLE
[BUG / CI]  Investigate OIDC Cypress E2E test failures on 2.x CI runs

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security-dashboards-plugin#1986]
**What is the bug?**
E2E Cypress tests for OIDC flow seem to have failed for past few commits on 2.x:
https://github.com/opensearch-project/security-dashboards-plugin/actions/workflows/cypress-test-oidc-e2e.yml?query=branch%3A2.x

This issue is a request to investigate the CI failures and if possible, bring CI back to healthy state.

**What is the expected behavior?**
CI should be green.

**Comment by derek-ho** [comment]
Based on the history of this, it seems like https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/9178464893 introduced it, and it was fixed with the merging of your latest PR. I will close this until it starts happening again/we get a reproduction of it.
