### ISSUE TITLE
Different indexes are accessed depending on the tenant

### ISSUE THREAD

**Issue by linzehai0801** [opensearch-project/security-dashboards-plugin#1987]
Different indices are accessed according to different tenants
1、Create a permission to access all the indexes
![1](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/88591254/1f70d60c-d690-4a6e-91a3-e39fbb9a2c21)
2、At this point you will have access to all the indexes
![2](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/88591254/815b3217-e984-4eb5-949f-b85aef5d9817)
3、Changing role permissions
![3](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/88591254/a59eb658-510b-4100-a9be-6ebe75a4863c)
![4](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/88591254/89dc158f-1ecc-4495-a7fe-522d08bb29bd)

In this case, the user has no access to anything, but the index is existing.How do I change it

**Comment by scrawfor99** [comment]
[Triage] Hi @linzehai0801, thank you for filing this issue. Based on the info you provided, this seems like a configuration question best addressed over on the forum: https://forum.opensearch.org/. Please feel free to follow up there for more specific guidance.

**Comment by cwperks** [comment]
@linzehai0801 On the discover tab, it shows the "Index Patterns" from Dashboards Management -> Index Patterns.

These saved patterns are tenant-specific so if you create them on the private tenant of the first user, they would not show for the other user. Can you confirm if the `jumpserver-*` index pattern exists in the global tenant and you are on the same tenant for the first and second user?

If you navigate to Dev Tools as the second user you should be able to read any `jumpserver*` matching index.
