### ISSUE TITLE
[FEATURE] Support JDK 21 for main branch

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#2009]
**Is your feature request related to a problem?**
Coming form: https://github.com/opensearch-project/security/pull/4457, the security backend plugin's jdk version was recently changed to 21 on main. When not running JDK 21 in the dashboard plugin's CI, we see errors like
```
Exception in thread "main" java.lang.IllegalStateException: opensearch-security requires Java 21:, your system: 11.0.23+9-LTS
```
Link: 
 https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/9549400899/job/26318874294?pr=1941. 
**What solution would you like?**
Change the JDK versions used in dashboard CI to 21 for main branch
**What alternatives have you considered?**
None
**Do you have any additional context?**
No

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho, for filing this issue. This seems like a good request based on the overall campaign. Will mark as triaged.
