### ISSUE TITLE
[BUG] Missing OIDC refresh token calls in case of expired id token

### ISSUE THREAD

**Issue by uladzimir-tryputska** [opensearch-project/security-dashboards-plugin#2015]
**What is the bug?**
Dashboard security plugin doesn't call refresh token in case id token is expired

**How can one reproduce the bug?**
We are using Gitlab as IDP, where id token life time is 2 minutes. Or any IDP can be used with small token expiration time

- Login into Opensearch Dashboard
- Wait for > 2 mins
- Click any link on the Dashboard-> relogin happens

**What is the expected behavior?**
Refresh token end point call happens and new id token is used for further request

**What is your host/environment?**
Opensearch Dashboard image 2.14.0.0

**Do you have any additional context?**
isValidCookie() https://github.com/opensearch-project/security-dashboards-plugin/blob/2.14.0.0/server/auth/types/authentication_type.ts#L145, where refresh token logic is located, is not called any more, because cookie is cleared here https://github.com/opensearch-project/security-dashboards-plugin/blob/2.14.0.0/server/auth/types/authentication_type.ts#L139. And it is cleared because token is expired. Expiration logic was changed recently.

**Comment by derek-ho** [comment]
This was merged in time for 2.15 release, it should fix it: https://github.com/opensearch-project/security-dashboards-plugin/pull/1990
