### ISSUE TITLE
[FEATURE] Security Plugin Navigation Changes

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#2020]
**Is your feature request related to a problem?**
Coming from: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7029, security dashboards should conform to the new navigation changes coming from core. We should register under the category "Data Administration"
**What solution would you like?**
Registering under "Data Administration" group if the feature flag Nav Groups is enabled
**What alternatives have you considered?**
None
**Do you have any additional context?**
No

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho thank you for filing this issue. Going to mark as triaged.
