### ISSUE TITLE
Kibana multi-tenancy, dashboard tab shows 'Edit new Dashboard'

### ISSUE THREAD

**Issue by GianSilvCRI** [opensearch-project/security-dashboards-plugin#204]
I'm using opendistro 1.2.0

After switching tenant, the first time I navigate to dashboard tab what I see is a screen showing an empty new dashboard, ready to be created and saved. 

But if I navigate again on dashboard tab, what I see is the list of available dashboards for this tenant, as expected.

This happens also with a user with a role of read_only. Which is even worse, since it is not allowed to create or edit dashboards. Indeed in this case the 'read only user' sees the same screen for creating/editing a dashboard, but without the buttons 'save', 'cancel' and 'add' on top left corner.

Why is this happing?

**Comment by remioo** [comment]
Hello,
I have the same issue on opendistro 1.4.0

**Comment by orest-gulman** [comment]
hi, same issue in 1.7.0. It's not nice because the users that have **read_only** role also getting a purpose to create a new dashboard which is not allowed for them.

**Comment by orest-gulman** [comment]
@zengyan-amazon, I think that this should be considered as a bug. Thanks!

**Comment by davidlago** [comment]
I am unable to reproduce this behavior using version 2.1.0, so I'm assuming this issue has been resolved. If that's not the case, please feel free to re-open with additional repro steps. Thanks!
