### ISSUE TITLE
[FEATURE] Retry Bootstrap Step for OSD

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/security-dashboards-plugin#2046]
**Is your feature request related to a problem?**
During CI checks, it is common that actions fail, especially during bootstrapping/downloading dependencies, especially for windows. We should automatically retry these actions to reduce manual intervention. 
**What solution would you like?**
Retry bootstrapping/downloading dependencies
**What alternatives have you considered?**
None
**Do you have any additional context?**
No

**Comment by scrawfor99** [comment]
[Triage] Hi @derek-ho, thanks for filing this issue. This seems like a good change to improve the CI success rate.
