### ISSUE TITLE
problem with self signed cert with oidc

### ISSUE THREAD

**Issue by hermanhmlee** [opensearch-project/security-dashboards-plugin#210]
i haven't figured out whether this is the right module that handles the OpenID Connect code - it doesn't seem like so please let me know if I should go to another module instead. Since I can't get SAML to work, I am trying OIDC and I get a self-signed cert error when I use OIDC. I already put the CA cert in 

config:
  pemtrustedcas_filepath: /path/to/trusted_cas.pem

as well.

Error from the log:

,"tags":["error","openid"],"pid":XXXXX,"level":"error","error":{"message":"Client request error: self signed certificate","name":"Error","stack":"Error: self signed certificate\n    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)\n    at emitNone (events.js:106:13)\n    at TLSSocket.emit (events.js:208:7)\n    at TLSSocket._finishInit (_tls_wrap.js:643:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)","code":"DEPTH_ZERO_SELF_SIGNED_CERT"},"message":"Client request error: self signed certificate"

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!

**Comment by RobinGoussey** [comment]
Hi, I took me a while to figure out as well, this property is missing from any documentation, perhaps this could be added @davidlago ?
I was trying to find out how to add a root_ca, but couldn't find anything in any docs or google search, I found it by looking at the code:
opensearch_security.openid.root_ca: my_dir/root_ca.pem

**Comment by davidlago** [comment]
Thanks for the follow-up! I've gone ahead and created https://github.com/opensearch-project/documentation-website/issues/1499 to add it to our docs!
