### ISSUE TITLE
OpenID in ODFE do not refreshes the access token

### ISSUE THREAD

**Issue by agarwalgovind** [opensearch-project/security-dashboards-plugin#213]
When using OpenID with ODFE the access token gets timeout and the Kibana UI gets blocked if used with an external IDP SSO like keycloak etc.

**Comment by agarwalgovind** [comment]
Raised a PR for the issue -
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/217

**Comment by agarwalgovind** [comment]
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/217

**Comment by agarwalgovind** [comment]
[https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/217](url)

**Comment by zengyan-amazon** [comment]
duplicate with https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/232

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
