### ISSUE TITLE
build fail due to https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001587.tgz: Request failed \"403 Forbidden\"".

### ISSUE THREAD

**Issue by PrincePranav235** [opensearch-project/security-dashboards-plugin#2160]
During building the image,
while running  RUN npm install -g yarn, getting below errors
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! errno UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! request to https://registry.npmjs.org/yarn failed, reason: unable to verify the first certificate

and also,

$ scripts/use_node ./preinstall_check
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.5.2"
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001587.tgz: Request failed \"403 Forbidden\"".

Can anyone tell, how to deal with this issue?

**Comment by cwperks** [comment]
[Triage] @PrincePranav235 What version of npm are you using? Make sure to use the same node version as OSD Core: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.node-version

I don't think this is an issue with this repository. Closing this issue, please re-open if you suspect there to be a bug.
