### ISSUE TITLE
Kibana Security - plain text in conf (Authentication and Authorization)

### ISSUE THREAD

**Issue by hiloyt** [opensearch-project/security-dashboards-plugin#22]
![plaintext](https://user-images.githubusercontent.com/48281929/58457306-9fb9b900-8126-11e9-809c-d35b2c31c078.png)

Security without security. Can it be possible to hide AD bind and password in Kibana UI?

**Comment by floragunncom** [comment]
You can use environment variables: https://github.com/floragunncom/search-guard/issues/619

**Comment by Alexpast1423** [comment]
Actually on 1.13 version plugin

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
