### ISSUE TITLE
Kibana plugin does not list newly created role

### ISSUE THREAD

**Issue by stempher** [opensearch-project/security-dashboards-plugin#230]
Hi
If i create a role using api request:
```
PUT _opendistro/_security/api/roles/test-api
{
  "index_permissions": [{
    "index_patterns": [
      "test-*"
    ],
    "allowed_actions": [
      "read"
    ]
  },
  {
    "index_patterns": [
      "?kibana*"
    ],
    "allowed_actions": [
      "indices_all"
    ]
  }],
  "tenant_permissions": [{
    "tenant_patterns": [
      "global_tenant"
    ],
    "allowed_actions": [
      "kibana_all_write"
    ]
  }]
}
```
then it cannot be found in the web interface in the roles mapping section.
If i create role mapping using api, then an error is displayed in the web interface
![photo_2020-05-28_13-36-46](https://user-images.githubusercontent.com/23376762/83655526-35ecae80-a5c7-11ea-990a-07c3f94ceec9.jpg)
What am I doing wrong?

**Comment by vijshah** [comment]
I was able to get roles created in API appear in UI list using 2 techniques.
1) Edit the role and save it with or without changes
2) Logout of Kibana and login back
