### ISSUE TITLE
Always logging into kibana app even subject_key and roles_keys not found with jwt enabled

### ISSUE THREAD

**Issue by syeddk** [opensearch-project/security-dashboards-plugin#235]
Hi

I have integrated jwt in kibana with user based jwt access and its working fine when logging into existing users
but whenever i am trying to access with invalid/not existing subject_key and roles_key, its logging into kibana instead of failing

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
