### ISSUE TITLE
Unable to select custom tenant

### ISSUE THREAD

**Issue by Thoro** [opensearch-project/security-dashboards-plugin#236]
Hi,

I followed the manual here: https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/multi-tenancy/

I can create everything, but when selecting the tenant under /app/security-multitenancy#/ and reload it select Private again, for the integrated admin_tenant, Global and Private the selection works fine and is saved after a reload.

What could be the issue? Kibana doesn't log any errors (returns 200 on /api/v1/multitenancy/tenant)

This happens with a restricted user, AND the access_all user

**Comment by jiangzhuo** [comment]
I occurred the same issue. I am using AWS managed elasticsearch(7.4) and kibana.
As @Thoro said, after clearing all cookies. I can select other tenant.

> After configuring further tenants the issue reappeared, I can make it work by clearing all cookies, but that shouldn't be necessary!

**Comment by davidlago** [comment]
The tenant selection has been revamped, and at this time I'm not able to reproduce this issue with version 2.1.0 of OpenSearch. Please feel free to re-open if that's not the case for you and we can take a further look!
