### ISSUE TITLE
multi-tenancy page:  Selecting new page destroys link if server.basePath set 

### ISSUE THREAD

**Issue by turettn** [opensearch-project/security-dashboards-plugin#245]
When a user switches tenants via the Kibana GUI Plugin, it resets the URL for several of the links (to include discover, dashboards, and visualizations).

Unfortunately, if [server.basePath](https://www.elastic.co/guide/en/kibana/current/settings.html) is set in the Kibana config (commonly done when the server is being a reverse proxy), the resulting URL is malformed.  For example, it will reset `http://staging/my_kibana_server/app/kibana#/discover` to `http://staging/app/kibana#/discover`.

Since nginx doesn't know where to route /app/, this results in a HTTP404.

It's a one-line fix to make the plugin respect server.basePath - I'll push a PR shortly.

**Comment by ohdearaugustin** [comment]
I can confirm that issue in version 1.8.0 and 1.9.0.

My current workaround is to reload the browser after switching the tenant (F5), then the urls are correct again.

**Comment by ohdearaugustin** [comment]
@sujithvm As it seems you are a really active developer here. Can you please take a view at that issue and pull request. Thanks in advance.

**Comment by turettn** [comment]
This appears to have been closed by #246.
