### ISSUE TITLE
Opendistro Security(1.8.0.0) readonly page not working in Kibana 7.7.0 - Dashboard page is empty

### ISSUE THREAD

**Issue by kanieren** [opensearch-project/security-dashboards-plugin#248]
Is there anyone who faces like this kind of issue? I have a users and I want that they can only see kibana dashboards. 
So, I have added them to "kibana_read_only" role group in open distro security settings, but when read only mode was active dashboard page is empty. everything is normal out of this mode. 

There is no errors in logs.

![unnamed](https://user-images.githubusercontent.com/41611043/84398775-07935280-ac09-11ea-83b0-f92a8c985631.png)

ES Version: 7.7.0
Kibana: 7.7.0
Opendistro: 1.8.0.0

I have never faced with this issue previous relases, ex. kibana:7.6.1

**Comment by dsvk** [comment]
Yes, just received a report of the same problem from a readonly user. The 7.7.0 + 1.8.0.0 stack is affected, an older one still on 7.6.1 + 1.7.0.0 is not. There are no other configuration differences between the two stacks - both were deployed by the same pipeline, the only change was bumping the Elastic and OpenDistro release versions to be installed.

**Comment by Jrodseth** [comment]
Also experienced the issue with the same versions - preventing us from upgrading until this is resolved.

**Comment by mrhorvath** [comment]
I'm having this same issue.  I brought up the official docker image and created a test user following the instructions in the documentation for a read only role, https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/users-roles/#sample-roles.  This includes pairing the kibana_user role mapping, as indicated in the predefined roles section, https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/users-roles/#predefined-roles.

When I add the role mapping from the test user to 'kibana_read_only', the test user only has dashboards available (great!), but the user's dashboard page is empty (boo!).

**Comment by bog-sb** [comment]
i also have the same issue. just tested now 1.9.0 and it doesn't seem to be fixed here either.

**Comment by Agudelo91** [comment]
Same here... any news about it?

Thanks

**Comment by helmanofer** [comment]
I am using opendistro 1.8.0.0 both on windows10 and on ubuntu.
On windows it works perfectly, on unbuntu, it doesn't

**Comment by ianadeem** [comment]
Same problem here. I've tested on Chrome/Firefox on Ubuntu and Windows. None of the combinations is working.

**Comment by RameshKatkam** [comment]
Hello!

I am facing similar issue. Any update on the resolution is appreciated. 

Thanks,
Ramesh

**Comment by dduong26** [comment]
Hey everyone,

I'm also experiencing the same issue as OP

**Comment by sushovan23** [comment]
any timeline to when this bug will be fixed?

**Comment by h-bomb** [comment]
I'm having the same issue (using Open Distro Elasticsearch `7.7` in AWS.) I've been trying to build a read-only role in Kibana without much luck. Has anyone developed a work-around role that at leasts locks down all the _writeable_ areas in Kibana?

**Comment by markusbecker** [comment]
Same issue here. Any update on this?

**Comment by boehmerm** [comment]
Same problem here.

**Comment by rosslutsch** [comment]
same issue here:

Using 1.9.0 with kibana 7.8
Create a tenant with a user, test that the user can view dashboards then when applying the dashonly role the user can see the dashboard menu but no actual dashboards. 

Maybe need to add read kibana* index read permision or something?

**Comment by deepakprasad119** [comment]
Same Issue, here. 
I tried all built-in roles and some combination of custom roles. None of them matches kibana_read_only.

It would be very helpful if someone could share a workaround if found any.

**Comment by deepakprasad119** [comment]
> I'm having the same issue (using Open Distro Elasticsearch `7.7` in AWS.) I've built a read-only role in Kibana, but it doesn't hide the left nav areas (like the built-in read-only does). It does produce security errors if you attempt to make changes (not great, but will have to do until a fix is released.) Has anyone developed a work-around role that closely mimics the built-in read-only role(s)?

Hi Mate, have you found any workaround for this?

**Comment by rosslutsch** [comment]
To get kibana to only display the dashboard with the read only role you have to add opendistro_security.readonly_mode.roles: ["dashonly"] to kibana.yaml the problem is it doesn't show any dashboards, not sure where to from there though? lemme know if you make progress

**Comment by gferrette** [comment]
Hello!

Is anyone knows if this feature still have this bug on opendistro last version? (1.11.0)

Thanks!

**Comment by markusbecker** [comment]
> Hello!
> 
> Is anyone knows if this feature still have this bug on opendistro last version? (1.11.0)
> 
> Thanks!

Doesnt seem like someone is working on it. I am currently stuck with the AWS managed ES on 7.4 due to that reason. Would love to upgrade in the future to use reporting and such features for my client. :/

**Comment by dsvk** [comment]
Readonly users appear to work for me again on 1.12.0 using the same setup as before on 1.7.0. Can anyone confirm?

For the record, I have not tested 1.10.1 or 1.11.0 so I am not certain whether this only got fixed now or if any of those earlier releases might also work. I don't plan on downgrading though.

**Comment by GopalManiQ** [comment]
@dsvk I am trying to create a read-only user in the latest version (1.12) but it is not working as expected. Could you share the steps that you have followed to achieve this?

**Comment by rosslutsch** [comment]
Maybe share your configuration, create a role under security roles, add the index you want to give permissions to and add read and search action groups, then map the role to your user and bob could be your uncle

**Comment by davidlago** [comment]
No further repro steps, problem does not seem present in newer versions, closing the issue. Please feel free to re-open with additional repro steps/config files for newer versions and we'll take a look!
