### ISSUE TITLE
Tenant selection in menu

### ISSUE THREAD

**Issue by mareban** [opensearch-project/security-dashboards-plugin#265]
Hello,

Does this kibana parameter works  for ODFE 1.6.0.1 "opendistro_security.multitenancy.enable_filter" please ?

I've tried but it 's not working for me :-( 

Thanks for your help

**Comment by davidlago** [comment]
Paramenter is working as expected, I hope you got this sorted on yoru end! If not, please re-open and provide additional repro steps to troubleshoot further. Thanks!
