### ISSUE TITLE
Make tenant index replica count configurable 

### ISSUE THREAD

**Issue by jsirianni** [opensearch-project/security-dashboards-plugin#272]
It would be nice to have control over the tenant index template, specifically when it comes to replicas. It looks like the code sets the shard count, but uses whatever the cluster defaults to for replicas.

[existing code](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/lib/elasticsearch/setup_index_template.js)
```
        try {
            await callAdminAsKibanaUser('indices.putTemplate', {
                name: `tenant_template`,
                body: {
                    index_patterns: [
                        index+"_-*_*",
                        index+"_0*_*",
                        index+"_1*_*",
                        index+"_2*_*",
                        index+"_3*_*",
                        index+"_4*_*",
                        index+"_5*_*",
                        index+"_6*_*",
                        index+"_7*_*",
                        index+"_8*_*",
                        index+"_9*_*",
                    ],
                    settings: {
                        number_of_shards: 1,
                    },
                    mappings: migrator.getActiveMappings(),
                },
            });
```

**Comment by shawnz** [comment]
As a workaround you can just create your own template which has a higher order value and set the setting there

**Comment by davidlago** [comment]
Workaround available. If there is enough interest around this feature, please feel free to re-open with a proposed PR and we'll take a look!
