### ISSUE TITLE
Kibana returns Internal Server Error when given expired security_authentication cookie

### ISSUE THREAD

**Issue by jsmyczek** [opensearch-project/security-dashboards-plugin#283]
Steps to reproduce:
1. Run `docker-compose up` with [attached files](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/files/4947548/docker-compose.zip).
2. Create test user:
```
$ curl --user 'admin:admin' --header "Content-Type: application/json" --request PUT --data '{"password":"ABcd12#$"}'  http://localhost:9200/_opendistro/_security/api/internalusers/auser
{"status":"CREATED","message":"'auser' created."}
```
3. Login to obtain authentication cookie:
```
$ curl --request POST --include --header 'kbn-xsrf: true' --header 'Content-Type: application/json' --data '{"username":"auser","password":"ABcd12#$"}' http://localhost:5601/kibana/api/v1/auth/login
HTTP/1.1 200 OK
kbn-name: kibana
content-type: application/json; charset=utf-8
cache-control: private, no-cache, no-store, must-revalidate
set-cookie: security_storage=Fe26.2**1f519aad09220c6ab2ee85a5ca11b1ec603b4b8e24f9219309423e923bee437a*1XpKpnFqt4ZvHxEZnZ07HA*Tec0LzJ9r57lv6YkMPS7auqUY8ciSswu9-B2hWdrh0jpfGV52aUuIjn6oj7F8gP5**0f5b6c416140474925bcb1cfbeff2cd4e27d982ffccd4ff9277425b93477496e*3SgYG4jhTRieYraH21Il4aWkhRM3gBhH12ftYifBaF8; HttpOnly; Path=/
set-cookie: security_authentication=Fe26.2**b628ebbbcc6c038c5ca21cf9141711e9dc423a924f773b8e5793cc345d302b94*guD5k7tgw-6ptOiks5fIQw*oF2vJkLGRIy8q6c9eiU-uE0uiEDkTB-jcoKUe8XdNwFpJ-7j9ikxTM3c1-hfZOlUCsdEcD3I0vtBgdYJzQLHY-XMO7AxgL8MXEz90Bib9dw3BQfqxMJ-xA9DTu8YXdTrDTZApM9lDv9KQCj20-8-3zILkhdd2UjvhyWHtOQPFxqUh6T5c9B4F7rR2zt5_F-2gA-9bt5hNmR2iHI8-zDuGtlgEwpJD0nUPAiVL2UGEiU5tMSiEHl1d2pfGfSjmoFx**3ad42b223af2a5f344203cc156feba68e00e515a26787e163994984569784838*Ao1yQZFXlh2yjiXQEVcgD6bihf1qeGv9eqTOe85Nk6M; Max-Age=3600; Expires=Wed, 15 Jul 2020 23:29:30 GMT; HttpOnly; Path=/
content-length: 107
Date: Wed, 15 Jul 2020 22:29:30 GMT
Connection: keep-alive
```
4. Change user's password:
```
$ curl --user 'admin:admin' --header "Content-Type: application/json" --request PUT --data '{"password":"EFgh34%^"}'  http://localhost:9200/_opendistro/_security/api/internalusers/auser
{"status":"OK","message":"'auser' updated."}
```
5. Try to use authentication cookie from step 3:
```
$ curl --cookie 'security_authentication=Fe26.2**b628ebbbcc6c038c5ca21cf9141711e9dc423a924f773b8e5793cc345d302b94*guD5k7tgw-6ptOiks5fIQw*oF2vJkLGRIy8q6c9eiU-uE0uiEDkTB-jcoKUe8XdNwFpJ-7j9ikxTM3c1-hfZOlUCsdEcD3I0vtBgdYJzQLHY-XMO7AxgL8MXEz90Bib9dw3BQfqxMJ-xA9DTu8YXdTrDTZApM9lDv9KQCj20-8-3zILkhdd2UjvhyWHtOQPFxqUh6T5c9B4F7rR2zt5_F-2gA-9bt5hNmR2iHI8-zDuGtlgEwpJD0nUPAiVL2UGEiU5tMSiEHl1d2pfGfSjmoFx**3ad42b223af2a5f344203cc156feba68e00e515a26787e163994984569784838*Ao1yQZFXlh2yjiXQEVcgD6bihf1qeGv9eqTOe85Nk6M' http://localhost:5601/kibana/api/v1/configuration/account
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```
Backend logs:
```
odfe-node    | [2020-07-15T22:31:23,574][WARN ][c.a.o.s.a.BackendRegistry] [odfe-node] Authentication finally failed for auser from 172.21.0.3:52002
odfe-kibana  | {"type":"error","@timestamp":"2020-07-15T22:31:22Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"AuthenticationError","stack":"AuthenticationError: Internal Server Error\n    at wrapElasticsearchError (/usr/share/kibana/plugins/opendistro_security/lib/backend/errors/wrap_elasticsearch_error.js:36:12)\n    at SecurityConfigurationBackend.list (/usr/share/kibana/plugins/opendistro_security/lib/configuration/backend/opendistro_security_configuration_backend.js:133:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/v1/configuration/account","path":"/api/v1/configuration/account","href":"/api/v1/configuration/account"},"message":"Internal Server Error"}
odfe-kibana  | {"type":"response","@timestamp":"2020-07-15T22:31:22Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/api/v1/configuration/account","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.66.0","accept":"*/*"},"remoteAddress":"172.21.0.1","userAgent":"172.21.0.1"},"res":{"statusCode":500,"responseTime":723,"contentLength":9},"message":"GET /api/v1/configuration/account 500 723ms - 9.0B"}
```

Expected result: `302 Found` redirection to login page.

**Comment by zengyan-amazon** [comment]
Hi @jsmyczek , thanks for reaching out!

In the current implementation, Kibana will try to validate the cookie and extract the user credentials from cookie. When user credentials are present in the cookie, Kibana will simply use it when calling Elasticsearch, without verifying the credentials to save additional authentication call for each request.

In your example, you get cookie from Kibana API and then change the password by calling ES API. Kibana is not aware of the password change. So when calling Kibana API with the cookie, the credentials are invalid, Kibana still pass the credentials from cookie to call ES, thus get authentication failure.

I agree that Kibana should not return 5xx in this case, however, I am thinking returning `401 unauthorized` makes a bit more sense than `302 redirect to login page`, then the client side can call logout API to clear the cookie and redo authentication, or use latest credentials to refresh the cookie. Please let us know your idea.

**Comment by jsmyczek** [comment]
Hi @zengyan-amazon,

I suggested `302` as this was the status code I have usually seen, for example when credentials are missing:
```
$ curl --include http://localhost:5601/kibana/api/v1/configuration/account
HTTP/1.1 302 Found
location: /kibana/login?nextUrl=%2Fkibana%2Fapi%2Fv1%2Fconfiguration%2Faccount
```
or when credentials are invalid:
```
$ curl --include --user 'admin:wrongpass' http://localhost:5601/kibana/api/v1/configuration/account
HTTP/1.1 302 Found
location: /kibana/login?nextUrl=%2Fkibana%2Fapi%2Fv1%2Fconfiguration%2Faccount
```
or when authentication cookie is invalid:
```
$ curl --include --cookie 'security_authentication=dummy' http://localhost:5601/kibana/api/v1/configuration/account
HTTP/1.1 302 Found
location: /kibana/login?nextUrl=%2Fkibana%2Fapi%2Fv1%2Fconfiguration%2Faccount
```
but if you think `401` is better that's fine with me.

**Comment by zengyan-amazon** [comment]
I was able to reproduce this issue. Looks like the 500 error are caused by https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/master/lib/backend/errors/wrap_elasticsearch_error.js#L35-L37 where HapiJS cannot handle `AuthenticationError`, thus throws `500 Internal Server Error`.

So I would propose to use Boom to wrap this 401 error from ES as well, so that Hapi server can return 401 instead of 500 to the client side when Elasticsearch returns 401 to Kibana.

@dinusX @hardik-k-shah can you share your thoughts on this?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
