### ISSUE TITLE
Kibana login page does not load - possible webpack/babel build issue

### ISSUE THREAD

**Issue by maybe-sybr** [opensearch-project/security-dashboards-plugin#286]
I have been attempting to spin up a simple OD elastic/kibana kubernetes pod on top of podman. I'm now at the point where I've got ES up and Kibana appears to be happily talking to it on the backend, but I can't get the Kibana UI to show me a login screen. It sits there animating the "Loading Elastic" progress bar forever.

In Firefox, I see the following messages in the developer console:

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). login:342:1
^ A single error about an inline script not firing due to content security policy is expected! bootstrap.js:11:20

window.controllers/Controllers is deprecated. Do not use it for UA detection. kbn-ui-shared-deps.js:288:214031

Uncaught TypeError: __webpack_require__(...) is not a function
    <anonymous> commons.bundle.js:3
    __webpack_require__ security-login.bundle.js:71
    <anonymous> commons.bundle.js:3
    __webpack_require__ security-login.bundle.js:71
    2515 security-login.bundle.js:225
    __webpack_require__ security-login.bundle.js:71
    checkDeferredModules security-login.bundle.js:42
    <anonymous> security-login.bundle.js:190
    <anonymous> security-login.bundle.js:191
commons.bundle.js:3:150

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.
```

I believe the culprit must be the `TypeError` which might be a similar issue to either:
 * webpack/webpack#9379, where apparently "adding `sourceType: "unambiguous"` to `babel.config.js`" fixed the breakage, or
 * webpack/webpack#6544, where apparently "excluding node_modules from babel transpilation" fixed the breakage

I'm not really in a position to try to repro this on the dev branch right now as I'm not familiar with the node ecosystem, hopefully someone can work out if this is actually a reproducible issue or suggest some debugging steps I could try.

**Comment by tornis** [comment]
Hello,

I have this same problem.

My environment is:
Elasticsearch-oss-7.8.0
Kibana-oss-7.8.0
plugin open distro version 1.9

After installing the security plugin, Kibana presents the following error in browser:

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-P5polb1UreUSOe5V/Pv7tc+yeZuJXiOi/3fqhGsU7BE='), or a nonce ('nonce-...') is required to enable inline execution.
`

**Comment by luishdez** [comment]
I don't think it's a build issue. I think it is deliberate

<img width="392" alt="disabled-spc" src="https://user-images.githubusercontent.com/38347/96689855-3d98ce00-1383-11eb-9322-a1fde7c5a6d6.png">

**Comment by cesarqdt** [comment]
UP!

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
