### ISSUE TITLE
JWT authentication: kibana rejects valid tokens after session expiry

### ISSUE THREAD

**Issue by bwalsh** [opensearch-project/security-dashboards-plugin#31]
Symptoms:

1) user successfully logs in using jwt access token. Token based user, roles all OK
2) access token refreshed on a 10 minute basis
3) new access token delivered to kibana, usually kibana responds without an issue.

However, sometimes:
4-a) kibana responds with 302 /kibana/customerror?type=sessionExpired#?_g=()
4-b) I can test the token delivered in step 3 with elastic and it authenticates fine.

5) clearing all cookies, starting in incognito session, trying in different browser, all produce same 302 error

Workaround:

Only restarting kibana seems to work. :-(
After restarting only kibana, and using same token, authentication works.

Comments:

Suspect, but can't validate that kibana server is somehow maintaining state associated with token or it's cookie ?

## kibana log in verbose mode
```
kibana-service       | {"type":"log","@timestamp":"2019-06-04T22:24:11Z","tags":["plugin","debug"],"pid":1,"message":"Checking Elasticsearch version"}
kibana-service       | {"type":"log","@timestamp":"2019-06-04T22:24:13Z","tags":["debug","legacy-proxy"],"pid":1,"message":"Event is being forwarded: connection"}
kibana-service       | {"type":"log","@timestamp":"2019-06-04T22:24:13Z","tags":["debug","legacy-service"],"pid":1,"message":"Request will be handled by proxy POST:/elasticsearch/_msearch?rest_total_hits_as_int=true&ignore_throttled=true."}
kibana-service       | {"type":"response","@timestamp":"2019-06-04T22:24:13Z","tags":[],"pid":1,"method":"post","statusCode":302,"req":{"url":"/elasticsearch/_msearch?rest_total_hits_as_int=true&ignore_throttled=true","method":"post","headers":{"connection":"upgrade","host":"localhost","content-length":"1383","accept":"application/json, text/plain, */*","origin":"http://localhost","kbn-version":"6.7.1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36","dnt":"1","content-type":"application/x-ndjson","referer":"http://localhost/kibana/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","securitytenant":"__user__"},"remoteAddress":"172.19.0.11","userAgent":"172.19.0.11","referer":"http://localhost/kibana/app/kibana"},"res":{"statusCode":302,"responseTime":8,"contentLength":9},"message":"POST /elasticsearch/_msearch?rest_total_hits_as_int=true&ignore_throttled=true 302 8ms - 9.0B"}
kibana-service       | {"type":"log","@timestamp":"2019-06-04T22:24:13Z","tags":["debug","legacy-proxy"],"pid":1,"message":"Event is being forwarded: connection"}
kibana-service       | {"type":"log","@timestamp":"2019-06-04T22:24:13Z","tags":["debug","legacy-service"],"pid":1,"message":"Request will be handled by proxy GET:/customerror?type=sessionExpired."}
kibana-service       | {"type":"response","@timestamp":"2019-06-04T22:24:13Z","tags":[],"pid":1,"method":"get","statusCode":200,"req":{"url":"/customerror?type=sessionExpired","method":"get","headers":{"connection":"upgrade","host":"localhost","accept":"application/json, text/plain, */*","kbn-version":"6.7.1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36","dnt":"1","referer":"http://localhost/kibana/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.19.0.11","userAgent":"172.19.0.11","referer":"http://localhost/kibana/app/kibana"},"res":{"statusCode":200,"responseTime":8,"contentLength":9},"message":"GET /customerror?type=sessionExpired 200 8ms - 9.0B"}
kibana-service       | {"type":"log","@timestamp":"2019-06-04T22:24:13Z","tags":["plugin","debug"],"pid":1,"message":"Checking Elasticsearch version"}

```

**Comment by bwalsh** [comment]
I've verified that a new token was sent.  However, kibana does _not_ respond with it's own `security_authentication` cookie.

**Comment by bwalsh** [comment]
@hardik-k-shah

https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blame/v0.9.0.0/lib/auth/types/AuthType.js#L149-L155

I'm suspecting this section.  My tokens always have the same header:

```
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "XXXX_key_2019-03-08T05:28:18Z"
}
```

Would that cause the " no need to return new credentials" test to ignore the new token?

**Comment by bwalsh** [comment]
I suspect, but cannot prove, that the `security_authentication` cookie is out of step with the `Authorization: Bearer` token.

My brute force workaround seems to confirm this.

In nginx:

```
        # remove kibana's security_authentication cookie.
        set $sans_security_authentication $http_cookie;
        if ($http_cookie ~ "(.*)(?:^|;)\s*security_authentication=[^;]+(.*)") {
            set $sans_security_authentication $1$2;
        }
        proxy_set_header Cookie $sans_security_authentication;

...

        location /kibana {
            proxy_pass_request_headers off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            rewrite /kibana/(.*) /$1 break;
            proxy_set_header Authorization "$access_token";
            proxy_set_header kbn-version "$http_kbn_version";
            proxy_pass http://kibana-service:5601/;
        }

```

**Comment by horacimacias** [comment]
Not that I'm experiencing the same but I believe there is something wrong on how Kibana refreshes cookies' TTL when receiving requests. In my case I'm using SAML, not JWT, but user experience I believe is similar (session expiry is not updated even user is actively using kibana).

I'll create a separate issue for this (currently github is giving me 500 errors =:O) but here's the post I created sometime back: 
https://discuss.opendistrocommunity.dev/t/kibana-session-keepalive-when-using-saml/724

**Comment by samoilenko** [comment]
any updates?

**Comment by kakulukia** [comment]
Any updates?

**Comment by shamsalmon** [comment]
Try setting your cookie ttl to the same exact time as your access token expiration ```opendistro_security.cookie.ttl```

**Comment by maismail** [comment]
Any updates?

**Comment by maismail** [comment]
I managed to get it working by adding the following configurations:
opendistro_security.cookie.ttl : [jwtExiprationTime]
opendistro_security.session.ttl: 2 * [jwtExiprationTime]
opendistro_security.session.keepalive: true

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
