### ISSUE TITLE
Dropdown list to set Backend role for Internal User not available

### ISSUE THREAD

**Issue by matsyavatar** [opensearch-project/security-dashboards-plugin#33]
Opendistro-for-elasticsearch version 0.9.0
Ubuntu 18.04.02
While setting up backend role for internal users, dropdown list will ensure that there is no spelling mistakes and make it easier for admin to setup roles.

**Comment by davidlago** [comment]
Apologies for the very late response here. If this is still an issue in the newer versions, please re-open pointing to the spelling mistake that needs fixing. Thanks!
