### ISSUE TITLE
Set custom cookie Max-Age

### ISSUE THREAD

**Issue by aaf1** [opensearch-project/security-dashboards-plugin#34]
Hi, i use opendistro for elasticsearch.
After 1h inactive in interface i need to login again,  i want to increase this timeout
is it possible to configure it? 
i use ldap authorization 
set-cookie: security_authentication=Fe26.2**825c7bb605a776758bbed010d99af2930f13dbd16265bdf5f7042dfda81ca910*yEcrEdmu8wDHrKOb0yBtYQ*bxogIjV4NLzjHUK_2IJXvmXq1bxnQJ_iSJj-1qtOALGUAJaIXuS_VOKfu4fTTgajqKMl3B0G3TiH1a-_aKe04s61MfsTIOK1eXEezT4xipI8Qf8ONo9RnjCzW_3Ih21ZASqlFKUtaU42my577T0jGHTGr-DDxf655wh719TOESylhXzH1-QGo8a0mROKpdYHQoY7EcbvgTOsrZjq1ZXROLGHTLEuP9VC4jU1grKoSJk**098b3b2bf35cc56a5920628aa5aad7da9ce323c04de3c284bdf66c6db9ded9d1*hT-vlP2OglYA6RAdeMN9tN2OvGr7G3kFtW7_2buB1ho; ### **Max-Age=3600**; Expires=Thu, 06 Jun 2019 10:12:13

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
