### ISSUE TITLE
Can't use parent OU for userbase

### ISSUE THREAD

**Issue by justinrush** [opensearch-project/security-dashboards-plugin#36]
I have several OUs that contain user accounts I'd like to use to authenticate and authorize via LDAP (AD).  All of the OUs containing the user accounts are under OU=Core,DC=example,DC=com.  However, when I specify that as the "userbase" argument for authc and authz, all login attempts fail.  If I change the userbase to be OU=Admins,OU=Core,DC=example,DC=com ... or OU=Service Accounts,OU=Core,DC=example,DC=com ... user accounts in those specific OUs are able to login to Kibana.

Is specifying a parent OU for "userbase" that doesn't directly contain user accounts supported?  Is there another option I'm missing to tell the security plugin to recursively look for user accounts in "userbase"?

I'm using amazon/opendistro-for-elasticsearch:0.9.0

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
