### ISSUE TITLE
Session expiry not updated when using SAML

### ISSUE THREAD

**Issue by horacimacias** [opensearch-project/security-dashboards-plugin#37]
I’m using kibana with SAML authentication.
For some reason when the user logs in, I get a security_authentication cookie on my browser but the expiry time is set to 1h from the login time.

This means 1h after I logged in, **regardless of using or not kibana in between**, my session expires.

Is there any way to have this cookie expiration update on every request?

If I’m actively using kibana (or using automatic refreshes) I would expect my session to not expire.

Looking at https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/88f7dd343e53fabc466f92b90a9165db105d9b7b/lib/auth/types/saml/Saml.js 1 I can see the following:

>             if (tokenPayload.exp) {
>             // The token's exp value trumps the config setting
>             this.sessionKeepAlive = false;
>             session.exp = parseInt(tokenPayload.exp, 10);
>         } else if(this.sessionTTL) {
>             session.expiryTime = Date.now() + this.sessionTTL
>         }

but regardless of which settings I use I don’t get my cookie extended.

Also looking at https://docs.search-guard.com/latest/kibana-authentication-search-guard 1 (which I believe is the base for this plugin) it mentions:

> searchguard.session.keepalive	boolean, if set to true the session lifetime is extended by searchguard.session.ttl upon each request. Default: true

has anybody been able to setup keepalive so every new request refreshes the security cookie?

**Comment by squigg** [comment]
Having exactly the same issue - regardless of activity the session expires and I have to perform a full page refresh to re-establish a session using SAML.

Whilst this in itself is annoying, when combined with the fact it doesn't then return to the previous URL, it completely breaks live dashboards on screens.

**Comment by shamsalmon** [comment]
> Having exactly the same issue - regardless of activity the session expires and I have to perform a full page refresh to re-establish a session using SAML.
> 
> Whilst this in itself is annoying, when combined with the fact it doesn't then return to the previous URL, it completely breaks live dashboards on screens.

I believe this should resolve your later problem: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/72

**Comment by horacimacias** [comment]
looks very promising, thanks!

**Comment by shamsalmon** [comment]
> looks very promising, thanks!

There is actually still a problem. On live dashboards refresh request send a POST which means this will reply back with a 401 and not know what to do with the request because it only handles GET requests.

The problem with the code you posted above is that its pulling the session expiry from your authentication provider. If you set keepalive (`opendistro_security.session.keepalive`) then it will add time to the cookie but the session will expire separately in the saml authentication code and you will still have to reauth. I am waiting on feedback from the maintainers here to see what to do about 401s on ajax POST requests which will happen to you in that situation.

**Comment by jlusky** [comment]
This isn't a question.  It's a bug.  SAML is unusable for anything but a demo.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
