### ISSUE TITLE
Can't create user with role using Kibana GUI

### ISSUE THREAD

**Issue by newman0089** [opensearch-project/security-dashboards-plugin#447]
I am trying to create a user using the Kibana GUI. I am following these steps:
1. Open Kibana
2. Log in as admin
3. Security> Internal User Database> Add a new internal user
4. Provide username and password
5. In the Open Distro Security Rolesds field, select the role
5. Click Add backend role

But instead of creating a user, there is a redirect to the authorization page `/login?Type=basicauthLogout`
I am running odfe in docker. I am using the demo config provided by the docker image.
Images version 1.9.0

In the kibana log:
`odfe-kibana   | {"type":"response","@timestamp":"2020-09-07T14:22:15Z","tags":[],"pid":1,"method":"post","statusCode":403,"req":{"url":"/api/v1/configuration/internalusers/test","method":"post","headers":{"host":"192.168.1.3:5601","connection":"keep-alive","content-length":"97","accept":"application/json, text/plain, */*","kbn-version":"7.8.0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36","content-type":"application/json;charset=UTF-8","origin":"http://192.168.1.3:5601","referer":"http://192.168.1.3:5601/app/security-configuration","accept-encoding":"gzip, deflate","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7","securitytenant":"__user__"},"remoteAddress":"11.11.11.11","userAgent":"11.11.11.11","referer":"http://192.168.1.3:5601/app/security-configuration"},"res":{"statusCode":403,"responseTime":14,"contentLength":9},"message":"POST /api/v1/configuration/internalusers/test 403 14ms - 9.0B"}`

In the elastic log:
```
odfe-node1    | [2020-09-07T14:21:56,376][INFO ][stdout                   ] [odfe-node1] [FINE] No subscribers registered for event class com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigFactory$NodesDnModelImpl
odfe-node1    | [2020-09-07T14:21:56,376][INFO ][stdout                   ] [odfe-node1] [FINE] No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
```
What could be the problem? What settings are missing?

Thanks!

**Comment by dduong26** [comment]
What I had to do to bypass this was:

1 - Create the user with password and **NO** roles assigned.
2 - Then I go to Role Mappings, add, select role, add user, submit

**Comment by newman0089** [comment]
@dduong26, Thanks for the answer! I will try this method.

**Comment by newman0089** [comment]
@seanneumann, Do I understand correctly that this is a bug of version 1.9.0 of the open distro?

**Comment by dduong26** [comment]
@newman0089 np :)  it looks like a bug because on 1.9 I get this same issue but on 1.7 this bug doesn't exist.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
