### ISSUE TITLE
Session Issues w/Security Plug-in

### ISSUE THREAD

**Issue by g-man70** [opensearch-project/security-dashboards-plugin#490]
We are using LDAP authentication. LDAP users are not able to log back in to Kibana after their session expires. They are receiving the error pasted below. I see no corresponding logged events in the kibana or elasticsearch logs, or the security_auditlog index.

An error occurred while checking your credentials, make sure you have an Elasticsearch cluster secured by Security running.

Another issue users are experiencing is that once their session expires, they are not re-directed to the login page. Instead, Kibana appears to be non-functional or they receive permission errors.

I have the following OD session settings applied to kibana.yml.

opendistro_security.cookie.ttl: 86400000
opendistro_security.session.ttl: 86400000
opendistro_security.session.keepalive: true

ES Version is 6.8.1
OD Version is 0.10

**Comment by yuriydzobak** [comment]
The smae bug in 1.9.0 vesion

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
