### ISSUE TITLE
Cannot use method PATCH in Kibana Dev Tools Console

### ISSUE THREAD

**Issue by DJSundog** [opensearch-project/security-dashboards-plugin#51]
Not sure if this is the right repo for this issue or not, but figure it's a good place to start.

According to the docs at [https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#patch-user](https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#patch-user), to update individual attributes of an internal user one should submit a request using HTTP PATCH method.

However, the dev tools console in Kibana rejects PATCH as an allowed method:

```javascript
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "child \"method\" fails because [\"method\" must be one of [HEAD, GET, POST, PUT, DELETE]]",
  "validation": {
    "source": "query",
    "keys": [
      "method"
    ]
  }
}
```

I have confirmed that using `curl -XPATCH` with the appropriate request body does update the internal user properly.

It would be useful if either:

(a) Kibana were updated to accept PATCH method in dev tools console

or 

(b) The API were updated to accept POST method for endpoints currently using PATCH.

**Comment by francisco-hoo** [comment]
Hi @DJSundog, 

Can you tell me the curl command? Which flags and headers did you pass over the request to patch multiple Tentants?

**Comment by mbchris** [comment]
Hi,

although this is an older one, I'd like to confirm this.

In Kibana:
```
PATCH _opendistro/_security/api/rolesmapping/kibanauser
{
  [
  {
    "op": "add", "path": "/backend_roles", "value": ["mybackendrole"]
  }
]
}
```

ends up with:
```
{"statusCode":400,"error":"Bad Request","message":"[request query.method]: Method must be one of, case insensitive ['HEAD', 'GET', 'POST', 'PUT', 'DELETE']. Received 'PATCH'."}
```

Using curl, it works:

```
curl -k -u user:pwd -X PATCH "https://opendistroelastichost:9200/_opendistro/_security/api/rolesmapping/kibana_user" -H 'Content-Type: application/json' -d'
[
  {
    "op": "add", "path": "/backend_roles", "value": ["mybackendrole"]
  }
]'

```

```
{" status":"OK","message":"'kibana_user' updated."}
```

Kibana also shows an syntax error when using ```PATCH``` verb.

**Comment by farvour** [comment]
I can confirm this is happening to me as well. For those using AWS's Elasticsearch it means their documentation doesn't work either and I had to turn the single PATCH into individual PUTs if I wanted to use the built-in console.

Step 14:
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/saml.html#saml-enable

**Comment by abdalians** [comment]
exact same issue here.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
