### ISSUE TITLE
When multi-tenancy is disabled option to switch tenant should not be available

### ISSUE THREAD

**Issue by vrozov** [opensearch-project/security-dashboards-plugin#520]
Starting with 1.10.1.x there is an option to switch tenant when multi-tenancy is disabled. This option should not be there. Selecting this option leads to disappearance of logout option.

**Comment by tianleh** [comment]
Hi, vrozov@

I tried to reproduce the issue. After I clicked that option from profile button on top right, a modal with instruction message will be display and also the logout button is still there. Can you please share your steps/screenshots for "disappearance of logout option" to help us research?

<img width="1039" alt="Screen Shot 2020-10-19 at 6 01 44 PM" src="https://user-images.githubusercontent.com/60111637/96527618-61e69480-1235-11eb-921d-05afa60956d0.png">
<img width="326" alt="Screen Shot 2020-10-19 at 6 03 15 PM" src="https://user-images.githubusercontent.com/60111637/96527623-6448ee80-1235-11eb-9f2c-048af82ca6cb.png">

**Comment by vrozov** [comment]
It is reproducible with Chrome.

**Comment by vrozov** [comment]
<img width="1384" alt="Screen Shot 2020-10-19 at 22 06 30" src="https://user-images.githubusercontent.com/12200381/96542707-86ebff00-1257-11eb-8b75-6cbe7ab96870.png">

**Comment by vrozov** [comment]
<img width="1382" alt="Screen Shot 2020-10-19 at 22 06 47" src="https://user-images.githubusercontent.com/12200381/96542736-93705780-1257-11eb-95b6-c148443f108e.png">

**Comment by OlleLarsson** [comment]
I got this issue as well, and strangely enough if I set `opendistro_security.multitenancy.enabled: false` this behaviour disappears. Even tough it looks as if mutitenancy is disabled by default, see [here](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/main/server/index.ts#L105)

**Comment by zengyan-amazon** [comment]
include @kgcreative in this conversation

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
