### ISSUE TITLE
Create index pattern throws internal server error after update to v1.10.1.2

### ISSUE THREAD

**Issue by mradman-tildeloop** [opensearch-project/security-dashboards-plugin#529]
When creating an index pattern with a user with restricted access it no longer shows the available(filtered) indices but the request fails completely showing 0 results:
The endpoint `https://kb.packetai.co:5601/internal/index-pattern-management/resolve_index/*` returns `{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."}`,
with the following error in elasticsearch:
`No permissions for [indices:admin/resolve/index]`

The issue was not present in the prior version where the request would not fail but return only available indices of that user.
The behavior is also explained [here](https://github.com/elastic/kibana/issues/72219).

**Comment by zengyan-amazon** [comment]
@mradman-tildeloop it seems more like a permission configuration issue, `_resolve` API is new in ES 7.9. Can you try granting `indices:admin/resolve/index` permission to that restricted user?

**Comment by zengyan-amazon** [comment]
the fix of https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/530 should allow adding arbitrary permission on the new UI

**Comment by oscarkraemer** [comment]
Adding `indices:admin/resolve/index` to my user made it possible for my user to create new index pattern but only if I made the  `"index_patterns": "*"`. This means that all users with this permissions would be able to see the names of *all* indices in Elasticsearch this includes the tenant/user-indices as well, which I think it is too much privilege.

I don't understand how #530 will fix this issue, but I'm not that familiar with the code. (I'm using rpm, version: 1.10.1.0)

**Comment by zengyan-amazon** [comment]
@oscarkraemer I understand allowing all users to see all indices might be too much, but that is how Kibana is implemented. Technically, this is a Kibana index pattern implementation issue, not a security plugin issue.

#530 is just allow users to type arbitrary permission string on UI, which doesn't help with reducing the visibility of indices

**Comment by weiwarren** [comment]
Another issue with  ```"index_patterns": "*"``` is it causes document / field level filtering to break 

https://discuss.opendistrocommunity.dev/t/including-fields-not-working/641

**Comment by vrozov** [comment]
@zengyan-amazon Why this is not a security plugin issue? The evaluation of `indices:admin/resolve/index` is done by the security plugin. Do you mean that kibana always sends request with `*`? Even in this case security plugin may be able to filter response based on granted privileges and index pattern.

**Comment by BlackMetalz** [comment]
> @zengyan-amazon Why this is not a security plugin issue? The evaluation of `indices:admin/resolve/index` is done by the security plugin. Do you mean that kibana always sends request with `*`? Even in this case security plugin may be able to filter response based on granted privileges and index pattern.

I have the same question!

**Comment by astephon88** [comment]
It appears that the ES devs DO believe it's a security plugin issue. Their solution here https://github.com/elastic/elasticsearch/pull/60112 was to add indicies:admin/resolve/index to the X-PACK view_index_metadata privilege that can be applied to individual indices.

**Comment by amkgi** [comment]
Are you planning to fix this in OpenSearch Dashboard? We can't fully use tenants for some users.

**Comment by amkgi** [comment]
I tried to use DLS for resolve this issue, but I faced with new issue. Role for specific user:
```json
{
  "rnddls" : {
    "reserved" : false,
    "hidden" : false,
    "cluster_permissions" : [ ],
    "index_permissions" : [
      {
        "index_patterns" : [
          "rnddls*"
        ],
        "dls" : "",
        "fls" : [ ],
        "masked_fields" : [ ],
        "allowed_actions" : [
          "indices_all"
        ]
      },
      {
        "index_patterns" : [
          "*"
        ],
        "dls" : "{ \"term\": { \"Client\": \"rnddls\"}}",
        "fls" : [ ],
        "masked_fields" : [ ],
        "allowed_actions" : [
          "indices:admin/resolve/index"
        ]
      }
    ],
    "tenant_permissions" : [ ],
    "static" : false
  }
}
```
I got error:
```json
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."}
```
Logs:
```
opensearch-dashboards    | {"type":"response","@timestamp":"2021-09-18T14:54:10Z","tags":[],"pid":1,"method":"post","statusCode":200,"req":{"url":"/auth/login","method":"post","headers":{"host":"localhost:5601","content-type":"application/json","origin":"http://localhost:5601","osd-version":"1.0.0","accept-encoding":"gzip, deflate","connection":"keep-alive","accept":"*/*","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","referer":"http://localhost:5601/app/login?nextUrl=%2F","content-length":"41","accept-language":"ru"},"remoteAddress":"172.20.0.1","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","referer":"http://localhost:5601/app/login?nextUrl=%2F"},"res":{"statusCode":200,"responseTime":10,"contentLength":9},"message":"POST /auth/login 200 10ms - 9.0B"}
opensearch-dashboards    | {"type":"log","@timestamp":"2021-09-18T14:54:10Z","tags":["error","opensearch","data"],"pid":1,"message":"[version_conflict_engine_exception]: [config:1.0.0]: version conflict, document already exists (current version [1])"}
opensearch-dashboards    | {"type":"log","@timestamp":"2021-09-18T14:54:10Z","tags":["error","http"],"pid":1,"message":"{ Error: Saved object [config/1.0.0] not found\n    at Function.createGenericNotFoundError (/usr/share/opensearch-dashboards/src/core/server/saved_objects/service/lib/errors.js:149:37)\n    at SavedObjectsRepository.get (/usr/share/opensearch-dashboards/src/core/server/saved_objects/service/lib/repository.js:916:46)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  data: null,\n  isBoom: true,\n  isServer: false,\n  output:\n   { statusCode: 404,\n     payload:\n      { statusCode: 404,\n        error: 'Not Found',\n        message: 'Saved object [config/1.0.0] not found' },\n     headers: {} },\n  reformat: [Function],\n  typeof: [Function: notFound],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/notFound' }"}
opensearch-dashboards    | {"type":"error","@timestamp":"2021-09-18T14:54:10Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toInternalError (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:82:19)\n    at Router.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:177:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/","path":"/","href":"/"},"message":"Internal Server Error"}
opensearch-dashboards    | {"type":"response","@timestamp":"2021-09-18T14:54:10Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","upgrade-insecure-requests":"1","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","referer":"http://localhost:5601/app/login?nextUrl=%2F","accept-language":"ru","accept-encoding":"gzip, deflate","securitytenant":"__user__"},"remoteAddress":"172.20.0.1","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","referer":"http://localhost:5601/app/login?nextUrl=%2F"},"res":{"statusCode":500,"responseTime":53,"contentLength":9},"message":"GET / 500 53ms - 9.0B"}
```

Any ideas how to resolve this issue differently?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
