### ISSUE TITLE
Allow user to copy/move dashboard or visualization object from one tenant to another tenant

### ISSUE THREAD

**Issue by hardik-k-shah** [opensearch-project/security-dashboards-plugin#53]
Currently, there is no way user can copy/move dashboard or visualization object from one tenant to another tenant. 

**Use-cases**: 

1. If user is belongs to multiple tenant and if he created dashboard or visualization into one tenant and wants to copy or move to other tenant. 
2. Migrating or installing security plugin on existing production cluster:  If admin or user with restore permission, restored snapshot of kibana index (which was created without Security plugin), and want to copy/move dashboards to different tenant based on their access model 

We should provide a button on kibana plugin for copy/move from one tenant to another tenant. This feature may requires changes to back-end plugin too.

**Comment by seungyongshim** [comment]
+1

**Comment by DJSundog** [comment]
Has any progress been made on this by any chance?

**Comment by jimymodi** [comment]
+1

**Comment by EgonGalvani** [comment]
+1

**Comment by gdspicer58** [comment]
+1

**Comment by laysauchoa** [comment]
+1

**Comment by gdspicer58** [comment]
FYI, I found a workaround, you can go to the left hand menu > Stack Management > Saved Objects > (choose the visualizations/dashboards that you want) > Click Export

Then switch tenants, go back to Stack Management > Saved Objects > Import the file that you exported from the other tenant

**Comment by laysauchoa** [comment]
thanks @gdspicer58 saved me a lot of time!

**Comment by ken-cai** [comment]
use api

```
curl -X POST "localhost:5601/api/saved_objects/_bulk_create?overwrite=true" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -H 'securitytenant:<name of private tenant space>' -d @home.json
```
//home.json
```
[{
    "type": "config",
    "id": "7.8.0",
    "attributes": {
        "buildNum": 9007199254740991,
        "defaultIndex": "<index-pattern-id>",
        "defaultRoute": "/app/kibana#/dashboard/test"
    }
}]
```

also add user/pass to the headers if needed

**Comment by androidkencai** [comment]
use api

```
curl -X POST "localhost:5601/api/saved_objects/_bulk_create?overwrite=true" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -H 'securitytenant:<name of private tenant space>' -d @home.json
```
//home.json
```
[{
    "type": "config",
    "id": "7.8.0",
    "attributes": {
        "buildNum": 9007199254740991,
        "defaultIndex": "<index-pattern-id>",
        "defaultRoute": "/app/kibana#/dashboard/test"
    }
}]
```

also add user/pass to the headers if needed

**Comment by davidlago** [comment]
Work to address this (and other) issues is being tracked here https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298
