### ISSUE TITLE
Preserve URL fragment during SAML handshake.

### ISSUE THREAD

**Issue by ssanchezjoss** [opensearch-project/security-dashboards-plugin#543]
Hi, we are using Open Distro (1.6.0) with the security plugin activated, and integration with Auth0 SSO.

After logging in via SAML for the first time, we were brought to the default application within Kibana and we aren't preserving the original URL that the user tried to visit before being prompted to login.

Current SAML handshake flow:
-Unauthenticated user navigates to https://kibana.com/app/kibana#/dashboard/demo_dashboard 
-User authenticates at IdP and is redirected back to Kibana 
-User lands on kibana home page https://kibana.com/app/kibana loosing the deeplink (fragment after # ) 

We came to notice that Elastic has solved this issuee in https://github.com/elastic/kibana/pull/44513 , which was merged to several 7.x releases. We also understand that ODES 1.6.0 comes with elasticsearch 7.6.1, and was released 6 months later of the above mentioned PR. 

Moreover, we are currently using the same IdP with many other services and the redirection works fine.
Thank you very much!

**Comment by shawnz** [comment]
This would also be a big help for us.

**Comment by cliu123** [comment]
The issue has been resolve with PR https://github.com/opensearch-project/security-dashboards-plugin/pull/1039
