### ISSUE TITLE
Wreck doesn't respect the root_ca option when using openid

### ISSUE THREAD

**Issue by rkbennett** [opensearch-project/security-dashboards-plugin#569]
When using version 1.10.1.2 with openid (keycloak in my environment) with ssl on the IdM provider, kibana enters a "TOO_MANY_REDIRECTS" state. 
The error in kibana fails with a client error, saying it "failed to verify the first certificate." 
This happens even when opendistro_security.openid.root_ca is set. 
The only way I've been able to work around this is by setting rejectUnauthorized: false on the wreck call where it is attempting to get a Token.

**Comment by rkbennett** [comment]
I'm using 1.10.2 ^

**Comment by rkbennett** [comment]
As an update, I was also able to bypass this by adding an environment variable of "NODE_EXTRA_CA_CERTS=/path/to/oidc-root-ca.pem

**Comment by jksmth** [comment]
> As an update, I was also able to bypass this by adding an environment variable of "NODE_EXTRA_CA_CERTS=/path/to/oidc-root-ca.pem"

I had a similar issue and also used this work around.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
