### ISSUE TITLE
The indices which match this index pattern don't contain any time fields when index permission is set

### ISSUE THREAD

**Issue by mxmorin** [opensearch-project/security-dashboards-plugin#571]
I've two indices prod-appli1 and prod-appli2
I've set index permission for the role1 as prod-appli1

When the user with the role role1 want to create an index pattern prod*, the list prints prod-appli1. But when clicking Next step button, The indices which match this index pattern don't contain any time fields is printed and i can't choose timestamp field

Clicking Create index pattern button triggered  no permissions for [indices:data/read/field_caps]  error

Creating prod-appli1 index pattern works well

**Comment by mxmorin** [comment]
I made it working by adding an index permission like this
![image](https://user-images.githubusercontent.com/58942529/97446293-87a72400-192e-11eb-9c32-077d29ad8998.png)

field_caps* is for index pattern, search* is for Discover to avoid security permission error

Very complex

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
