### ISSUE TITLE
Question: Suggestions on handling rotation of opendistro_security.openid.client_secret

### ISSUE THREAD

**Issue by sushovan23** [opensearch-project/security-dashboards-plugin#572]
Any suggestions on handling of rotation of opendistro_security.openid.client_secret in the kibana.yml file? So far we have separate script which checks if secret is updated and then it updates the value in kibana.yml file and restarts the service.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
