### ISSUE TITLE
Build artifacts for recent Github tagged releases missing?

### ISSUE THREAD

**Issue by Infraded** [opensearch-project/security-dashboards-plugin#61]
I've seen several releases cut on this repo for the plugin (v0.9.0.1 & v0.9.0.2 specifically), but don't see any matching build artifacts on the `https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-security/` path that the other versions are under.

Should there also be artifacts for these builds if they're tagged and cut on Github, or should formal GH releases not be done for these if they're some form of intermediate build?

**Comment by cliu123** [comment]
ODFE has been in maintenance mode. Please migrate to/create OpenSearch clusters if you can. The artifacts can be downloaded in the [official website](https://opensearch.org/).
