### ISSUE TITLE
1.12 Multiple authentication domains : Kibana Basic API returns 401 Unauthorized

### ISSUE THREAD

**Issue by pmarjou22** [opensearch-project/security-dashboards-plugin#654]
Hello,

While upgrading from opendistro 1.9 to opendistro 1.12 we face an issue with Multiple authentication domains.

Proxy authentications  + ES API are fine, but Kibana Basic API calls return 401 Unauthorized to our calls.

Step to reproduce : 

- Run docker images amazon/opendistro-for-elasticsearch:1.12.0 and amazon/opendistro-for-elasticsearch-kibana:1.12.0
- change kibana.yml  with a volume on kibana to include proxy authentication configuration (see enclosed)
- change config.yml (see enclosed) + run securityadmin.sh on elasticsearch
- run command from kibana container command line 
-- curl -XGET "http://localhost:5601/api/kibana/settings" -H "kbn-xsrf: true" -H 'Content-Type: application/json' -v -k --user admin:admin

You will get this error in verbose logs of kibana

{"type":"log","@timestamp":"2020-12-18T07:45:14Z","tags":["debug","http","server","Kibana","cookie-session-storage"],"pid":1,"message":"Error: Unauthorized"}
{"type":"response","@timestamp":"2020-12-18T07:45:14Z","tags":[],"pid":1,"method":"get","statusCode":401,"req":{"url":"/kbn/api/v1/restapiinfo","method":"get","headers":{"user-agent":"curl/7.29.0","host":"localhost:5601","accept":"*/*","kbn-xsrf":"true","content-type":"application/json"},"remoteAddress":"127.0.0.1","userAgent":"curl/7.29.0"},"res":{"statusCode":401,"responseTime":7,"contentLength":9},"message":"GET /kbn/api/v1/restapiinfo 401 7ms - 9.0B"}

APII calls to ES are working well : for instance 
curl -XGET "http://localhost:9200/_opendistro/_security/api/internalusers/" -H "kbn-xsrf: true" -H 'Content-Type: application/json' -v -k --user admin:admin

[config.txt](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/files/5715605/config.txt)
[kibana.txt](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/files/5715614/kibana.txt)

**Comment by zengyan-amazon** [comment]
@pmarjou22 Kibana security plugin only support 1 authentication type, in the kibana config you provided, you are using proxy auth, which means Kibana will only honor the user name or roles injected into request header by your proxy, while your username and password (in authorization header) will be ignored. You may want to change to basic auth in your kibana.yml config if you want to use basic auth for Kibana

**Comment by pmarjou22** [comment]
Thanks for the feedback, I 'll make my backend query to Kibana use proxy authentication then

**Comment by mbchris** [comment]
> @pmarjou22 Kibana security plugin only support 1 authentication type

Are there any parameters for the kibana security plugin stored in the .kibana* indices?

An interesting use case for me would be:

* Kibana container instance 1   => using .kibana index  => using oidc authorization
* Kibana container instance 2  => also using .kibana index => using proxy authorization   (to provide a read-only dashboard with predefined ingest proxy-user + role)

Will that be a conflict?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
