### ISSUE TITLE
No more supports for login session based on browsers' session

### ISSUE THREAD

**Issue by kyano** [opensearch-project/security-dashboards-plugin#668]
* Affected version: from 1.10.1.1 (https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/162)

### How to reproduce
```yaml
## kibana.yml
# set 0 to make authentication-related cookies as session cookies
opendistro_security.cookie.ttl: 0
opendistro_security.session.ttl: 0
```
Simply deploying Kibana with this security-kibana-plugin and trying to login with **BasicAuth**

```
## output logs from kibana
  log   [11:06:55.943] [debug][elasticsearch][opendistro_security][query] 200 GET /_opendistro/_security/authinfo
respons [11:06:55.285]  POST /auth/login 200 694ms - 9.0B
  log   [11:06:57.462] [debug][server][Kibana][cookie-session-storage][http] Clearing invalid session cookie
  log   [11:06:57.474] [debug][server][Kibana][cookie-session-storage][http] Error: Unauthorized
respons [11:06:57.459]  GET /app/select_tenant?nextUrl=%2F 302 25ms - 9.0B
```

### Descriptions
I found that `validate()` method in old versions checked `session.expiryTime` only when sessionTTL is set and not zero, but now it returns false(== invalid cookies) when `session.expiryTime` is not set without checking sessionTTL.

* Old implements: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/v1.9.0.0/lib/session/validate.js#L44..L56
* Current: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/v1.10.1.1/server/session/security_cookie.ts#L66..L68

Is this intended change by design, or just a bug? And if we can say it's by design, how can we set the login session based on the browsers' session?
I'm also aware that many people use session-keeping features of the recent web browsers, but I think that "closing browser applications closes the active sessions" is a very natural way to manage sessions.

**Comment by yuxitang-amzn** [comment]
Hi @kyano ,

We migrated to new framework on Kibana 7.9, the new framework provide only session cookie. Means all cookie are cleared after browser closed.

**Comment by kyano** [comment]
Then how can we keep the session cookies while the browser session is alive?
`validate()` always clears the cookies with setting expiry as "0".

**Comment by yuxitang-amzn** [comment]
If you leave it as default, it has ttl to 1 hour and will keep alive (extend time) every request.

https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/5f48f8f6b2acfdb62a00018f8c40a63373a2c545/server/index.ts#L55-L56

**Comment by kyano** [comment]
(The cookie will not be cleared if a user closes the browser but reopens within a TTL period. But anyway) We can get a similar concept with keepalives when we want just only avoiding unexpected session expires, right?

I think it's just by missing cases while migrating features, anyway, it's okay. (I'm aware that it's not a documented feature, but only found in the original documents of Searchguard)

Thanks for your kind responses. 🙇‍♂️
