### ISSUE TITLE
brandimage

### ISSUE THREAD

**Issue by samehif** [opensearch-project/security-dashboards-plugin#671]
i am using opendistro_security plugin version 1.10.1.1 with kibana version 7.9.1. i want to change the login image. The image that has the test "Open Distro for Elasticsearch" and it is above the text "Please login to kibana". 

I can see that in the file server/index.js we have this section where the brandimage is enabled but i can't find the place that define which image to use:

    ui: config_schema_1.schema.object({
        basicauth: config_schema_1.schema.object({
            // the login config here is the same as old config `opendistro_security.basicauth.login`
            // Since we are now rendering login page to browser app, so move these config to browser side.
            login: config_schema_1.schema.object({
                title: config_schema_1.schema.string({ defaultValue: 'Please login to Kibana' }),
                subtitle: config_schema_1.schema.string({
                    defaultValue: 'If you have forgotten your username or password, please ask your system administrator',
                }),
                showbrandimage: config_schema_1.schema.boolean({ defaultValue: true }),
                brandimage: config_schema_1.schema.string({ defaultValue: '' }),
                buttonstyle: config_schema_1.schema.string({ defaultValue: '' }),
            }),
        }),
    }),

Can someone help please?

**Comment by oscarkraemer** [comment]
You want to add the variable `opendistro_security.ui.basicauth.login.brandimage` in kibana.yml . https://discuss.opendistrocommunity.dev/t/customizing-the-kibana-login-page/3697 
Note the variable name changed in some version by adding the `ui.` .

**Comment by samehif** [comment]
I don't have any file with the name kibana.yml

**Comment by yuxitang-amzn** [comment]
@samehif It is in the config folder of kibana.

**Comment by samehif** [comment]
thanks a lot. one last question. where do i save my new image and how do i reference it in the opendistro_security.basicauth.login.brandimage: "your-image-url"

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
