### ISSUE TITLE
tenant name with ‘-’ seems not be properly handled.

### ISSUE THREAD

**Issue by ZeLAxyz** [opensearch-project/security-dashboards-plugin#682]
Hello, I created tenants "app-elk" and "app_elk" and set "Read and Write" to user "app-elk". On the "Read and Write" dialog of user "app-elk"，I could only see "app_elk"。
<img width="1214" alt="img1" src="https://user-images.githubusercontent.com/8666759/105141930-d54dba00-5b34-11eb-86b4-bc442a8e5765.PNG">
<img width="874" alt="img0" src="https://user-images.githubusercontent.com/8666759/105141937-d7b01400-5b34-11eb-9786-0b1bc0c8174e.PNG">

Open Distro for Elasticsearch version 1.12.0

Please help! Thanks a lot.

**Comment by davidlago** [comment]
Thanks for the report, @ZeLAxyz, and apologies for the late response. I am not able to reproduce in more current versions of OpenSearch, closing as resolved. Please let me know if that's not the case and we can definitely look into it!
