### ISSUE TITLE
openid authorization_code flow does not use basic auth header when calling token endpoint

### ISSUE THREAD

**Issue by i300543** [opensearch-project/security-dashboards-plugin#683]
Hello guys,
correct me if i'm wrong, but according to spec https://tools.ietf.org/html/rfc6749#section-4.1.3
when fetching the token in authorization_code  flow client must provide Authorization header:
Authorization:  base64(clientId:clientSecret)

but I see in the code both clientId and clientSecret are provided in request body:
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/main/server/auth/types/openid/routes.ts#L128-L143
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/main/server/auth/types/openid/helper.ts#L48-L58

and when I try to attach our oidc provider to kibana i indeed see response 401 from token endpoint when fetching token after auth redirect.
the exact same request with Authorization header as described above would work.
what am I missing here ?

Thanks in advance
Sergey

**Comment by oscarkraemer** [comment]
Is your 401 like this `"message":"401\nGET /_opendistro/_security/authinfo`, if so then the 401 comes from Elasticsearch. IIRC it is Elasticsearch that does that request and not Kibana.

**Comment by i300543** [comment]
No, the request i am speaking of comes from 
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/main/server/auth/types/openid/helper.ts#L48-L58
post call to token endpoint (defined in the oidc /.well-known metadata) and is coming from security-kibana-plugin

**Comment by oscarkraemer** [comment]
So this is the error you receive:
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/7d0a47e35f1cf7e1da688cb4e42fc99e37e31b45/server/auth/types/openid/helper.ts#L65
`Failed calling token endpoint: ${tokenResponse.res.statusCode} ${tokenResponse.res.statusMessage}``

**Comment by i300543** [comment]
> So this is the error you receive?:
> https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/7d0a47e35f1cf7e1da688cb4e42fc99e37e31b45/server/auth/types/openid/helper.ts#L65

Yes

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
