### ISSUE TITLE
Index Management be system-wide (rather than tenant-specific)

### ISSUE THREAD

**Issue by verbecee** [opensearch-project/security-dashboards-plugin#685]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I need to create an index pattern that should apply to all tenants, but can only create it in tenants individually.
We don't want to eliminate multi-tenancy for our cluster - we have tenants who have specific permissions to see only certain indices/documents. The problem is that MOST of our tenants would be benefit from the 100+ index patterns we have written, but we want them to be able to store their own objects in their own tenants. But recreating and maintaining the same 100+ index patterns across individual tenants (which we have over 10) is not feasible.

**Describe the solution you'd like**
It would be nice to manage index patterns globally rather than in a tenant-specific manner. For example, we have 10 tenants (a team per tenant), and we would like all 100+ index patterns we've created in one tenant to apply to all tenants. Rather than having to take the time to create the patterns across tenants or come up with some back-end hack, would be nice if this was a feature to begin with.

**Describe alternatives you've considered**
We haven't had time to try anything else, but have asked our separate teams to use a common tenant to see all index patterns. This is not a long-term solution as we would like teams to create objects in their tenants - especially if there is sensitive information that shouldn't be shared between tenants.

We brought this up with Kyle Davis and he said that there was a use case for this.

**Comment by trexx** [comment]
If you are open to suggestions, a solution in the meantime maybe to utilise the Kibana API to update your index patterns. Furthermore, if you store your index patterns in something like git, you can have a CICD pipeline apply your indexes to the tenants of your choosing.
You'll have the benefits of them being backed up, versioned too.

**Comment by davidlago** [comment]
Closing in favor of the work happening around the new [Workspaces](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4615) concept that will replace tenants in the future.
