### ISSUE TITLE
OpenDistro 1.12:  Error: failed to get user tenant: Error: Unauthorized  - at login page

### ISSUE THREAD

**Issue by abhijithb92** [opensearch-project/security-dashboards-plugin#703]
A call to `api/ui_metric/report` fails while loading Login page.
This prevents any javsscript from running.

I did not get this error when I ran it on HTTP using tar balls. 
This showed up when I upgraded OpenDistro from 1.11 to 1.12 in our compose file. It runs Kibana on https.

**Comment by vrozov** [comment]
`api/ui_metric/report` is not ODFE security plugin API. Please open against the right plugin.

**Comment by abhijithb92** [comment]
@vrozov  Is this not the right place to open it? Please let me know where I should open it. I shall close it here and open it at the correct place.

**Comment by davidlago** [comment]
This issue refers to a since unsupported version of ODFE. Please let us know if this is still happening with more recent versions of OpenSearch and re-open with details about the confguration files, versions and other relevant setup details. Thanks!
