### ISSUE TITLE
Show the tenant name in the header on all pages

### ISSUE THREAD

**Issue by micha558** [opensearch-project/security-dashboards-plugin#706]
Currently the actual tenant is only visible in the user-submenu.
It would be helpful if the tenant name would be present e.g. somewhere in the header or as a badge in a corner

![image](https://user-images.githubusercontent.com/61203301/107390936-7f977c80-6af8-11eb-9a2d-be9218528a0a.png)

**Comment by mxmorin** [comment]
+1. 
This could be a dropdown list with all authorized tenants, so we could switch easily too

**Comment by davidlago** [comment]
Tenants's new incarnation is being discussed as part of the [Workspaces RFC](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4615). Closing this one to make sure we capture all the feedback in one place.
