### ISSUE TITLE
Kibana Opendistro + AWS Elasticsearch (with access policy)

### ISSUE THREAD

**Issue by dignajar** [opensearch-project/security-dashboards-plugin#713]
Hi,
I'm trying to connect Kibana Opendistro with AWS Elasticsearch service, but my AWS ES has an access policy that allows an IAM Role.

It's possible to use in Kibana the AWS credentials or the token role to get access to ES ?

For example for Logstash there is a plugin https://github.com/awslabs/logstash-output-amazon_es

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
