### ISSUE TITLE
Goto Short URL does not redirect to Login page

### ISSUE THREAD

**Issue by abdalians** [opensearch-project/security-dashboards-plugin#721]
Issue: If the user is logged out of kibana and then clicks on a goto link 'https://kibana:5601/goto/xxxxxxxx' they do not get redirected to the login page. 

Steps to Reproduce: 

- Create a saved search 
- Click on Share > Select Snapshot > Enable Short URL> Copy Link
- Log out of Kibana 
- Try to go to the link copied earlier it looks like this 'https://kibana:5601/goto/xxxxxxxx'

You get 

{"statusCode":401,"error":"Unauthorized","message":"Authentication required"}

Expected Behaviour: 
Kibana  should redirect to the login page when it cant find authorization got a goto url and when user authenticate successfully go on to the originally intended goto url. 

Thanks

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
