### ISSUE TITLE
Show all dashboards across multi tenancy

### ISSUE THREAD

**Issue by mxmorin** [opensearch-project/security-dashboards-plugin#726]
Is it possible to list in the dashboard tab all dashboards the user can access or a minima tenant + global dashboards ?
Actually, i need to swicth to the global, custom or private to select dashboard.

Should be great if we can access dashboard from an single location without having to switch tenant.
Dashboard could be grouped by tenant if desired.

**Comment by davidlago** [comment]
Great idea. Closing and linking to https://github.com/opensearch-project/security/issues/1869 as that RFC addresses the re-vamp of sharing with Dashboards.
