### ISSUE TITLE
1.13 does not respect the remembered tenant 

### ISSUE THREAD

**Issue by oscarkraemer** [opensearch-project/security-dashboards-plugin#727]
**My environment:** 
1. User have two tenants:
- “AAAA” - does not contain any index patterns. (Alphabetical order is important)
- “BBBB” - does have index patterns
2. My user have chosen to remember tenant “BBBB” from the “select your tenant panel”

3. In my kibana.yml
```
opendistro_security.multitenancy.tenants.enable_global: false
opendistro_security.multitenancy.tenants.enable_private: false
server.defaultRoute: /app/dashboards
# opendistro_security.multitenancy.tenants.preferred: undefined in config!
```

**What happens:**
When I log in I get redirected to: `/app/management/kibana/indexPatterns?bannerMessage=To visualize and explore data in Kibana, you must create an index pattern to retrieve data from Elasticsearch.`

To be able to see the index patterns of “BBBB” I need to use “switch tenant” and choose “BBBB” even if it says in the upper right corner that “BBBB” is the current tenant.

**What I expected to happen**
I expected to get redirected at login to /app/dashboards with the "BBBB" tenant selected.

**Workarounds**
Workaround 1: I create an index pattern in “AAAA”.
Workaround 2: I change the `server.defaultRoute:` to `/app/kibana_overview` . ( I have not verify any other routes works as well)

**Difference between 1.12 and 1.13**
In 1.12 one gets always redirected to the select tenant panel when one logs in.

**Comment by davidlago** [comment]
Issue has since been fixed. Please re-open if not the case and we can troubleshoot further. Thanks!
