### ISSUE TITLE
Restricting kibana logout

### ISSUE THREAD

**Issue by skbhardwaj** [opensearch-project/security-dashboards-plugin#732]
Hello Team,

In one of our applications, we are opening up kibanaui **(same domain as main app)** in a new tab, **authenticated using JWT**. The kibana dashboard is loading properly.

However, once we do a kibana logout, it is observed that:

1. it clears all the localStorage, as mentioned in https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/118#issuecomment-614897218
2. and the main application (from where kibanaui is opened from) is also logged out !

Another case is - if we try to do a logout from main app, the kibanaui session is still maintained, and hence the kibana dashboard is still visible even after browser refresh.

Summarizing:
1. If we do a kibana app logout - only kibana should be logged out, not the main app.
2. If we do a main app logout - both (main+kibana) should be logged out.

I'm not sure as what is causing this issue OR how to fix this. It'd be great if you could resolve the issue in order to proceed with this.

Please do let me know, if you need any other information in this regard.

Thanks,

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
