### ISSUE TITLE
Default kibana security alert

### ISSUE THREAD

**Issue by iget-master** [opensearch-project/security-dashboards-plugin#737]
Hi, I'm reporting a bug:

Using latest docker image `amazon/opendistro-for-elasticsearch-kibana:1.13.1`, and security enabled, kibana still popup an alert saying "Your data is not safe. Secure your data for free with Elastic. Learn More/Dismiss" (or something similar).

But this looks like a default alert for Kibana (with xpack), and should be disabled somehow by opendistro security.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
