### ISSUE TITLE
Kibana not throwing an exception when permissions are not specified for tenant

### ISSUE THREAD

**Issue by verbecee** [opensearch-project/security-dashboards-plugin#739]
Hi Security plugin team! I recently updated permissions and am now having trouble with a specific Kibana role having its permissions work. Every user in Kibana have different roles but these roles have the same permissions/action groups, which I'll show below. However, at least one of these roles is getting consistent 403s on things that they should have access to. Other users with different roles - but the same permissions - can use Kibana as expected.

The cluster and index permissions are as follows for every user are:

Name: standard_user_cluster
"cluster:admin/opendistro/reports/definition/create",
"cluster:admin/opendistro/reports/definition/delete",
"cluster:admin/opendistro/reports/definition/get",
"cluster:admin/opendistro/reports/definition/list",
"cluster:admin/opendistro/reports/definition/on_demand",
"cluster:admin/opendistro/reports/definition/update",
"cluster:admin/opendistro/reports/instance/get",
"cluster:admin/opendistro/reports/instance/list",
"cluster:admin/opendistro/reports/menu/download",
"cluster:monitor/state",
"cluster:monitor/health",
"cluster:monitor/remote/info"

Name: standard_user_index_permissions
"crud",
"search",
"indices_monitor",
"create_index"

^ The index permissions apply to all indices (*)

We are using the OpenID standard, and I can confirm that the user has the correct associated backend role created in AzureAD.

In my roles screen, the yellow box represents the role at issue. It matches most of all the other roles we have in Kibana:
![image](https://user-images.githubusercontent.com/43911219/113428042-b45ade00-939b-11eb-933e-bc3c71dbe13b.png)

When User A (with the role with unexplained behaviors) goes to the Discover tab, they get the following error (bottom right):
![image](https://user-images.githubusercontent.com/43911219/113428114-d05e7f80-939b-11eb-982d-7d9f5bcc02e8.png)

They CAN see data in Discover, though. My screenshot was taken too early to show this, but they can see data.

When they attempt to make a saved search, they get:
![image](https://user-images.githubusercontent.com/43911219/113428164-ed934e00-939b-11eb-8e4f-ef9b8fc9a714.png)

When they go to the Reporting tab, and error comes up that no reports can be shown, and they also cannot create a report.

When I search the security audit logs, I can see their user's MISSING_PRIVILEGES logs, but the missing permissions are all permissions they already have.

![image](https://user-images.githubusercontent.com/43911219/113428225-08fe5900-939c-11eb-9571-b76c0dec0ea8.png)

Another example:
![image](https://user-images.githubusercontent.com/43911219/113428247-161b4800-939c-11eb-963b-beb42c77e52f.png)

When troubleshooting with the user, I eventually gave them cluster_all and indices_all permissions. However, they still get the 403s in Discover, reporting, etc with full admin rights.

We also went to our dev cluster, where they have the same permissions. Also, the backend_role assignment from AzureAD/OpenConnect is the same. They do NOT get the 403 in Discover, but they still cannot create reports.

**Comment by verbecee** [comment]
I also tried totally deleting the user's role and recreating, but that did not work.

**Comment by verbecee** [comment]
This problem is found in other users, for other MISSING_PRIVILEGES. If anyone could advise, this is impacting 5+ users now.

**Comment by verbecee** [comment]
<img width="1679" alt="Screen Shot 2021-04-23 at 2 56 21 PM" src="https://user-images.githubusercontent.com/43911219/115924096-e0bac500-a444-11eb-9ab1-2ac9f59aee0d.png">

The problem was that the tenant didn't have a value (neither Read or Write) when added via API calls. I'm opening a bug (planning on a PR too), huge thanks to @skkosuri-amzn for assistance in finding the issue.

**Comment by skkosuri-amzn** [comment]
We might need two fixes:
UI: Tenant permissions needs to default to READ when a tenant is selected. 
API: Throws error when tenant is passed but READ/RW is missing.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
