### ISSUE TITLE
Set default tenant

### ISSUE THREAD

**Issue by singlash26** [opensearch-project/security-dashboards-plugin#74]
I have three tenants and I want them to be displayed in a specific order in tenants tab. Even though I have set up _opendistro_security.multitenancy.tenants.preferred: ["C", "B", "A"]_ in _kibana.yml_ but I still see them alphabetically ordered in tenants tab and A is selected by default. Please assist.

**Comment by mendozakim123** [comment]
Same issue How I can change the default tenant in the user.

**Comment by lancemitchell** [comment]
I too would like to know how to set the default Tenant. 
Currently trying a workaround using ?security_tenant=<tenant-name> in URL, but when using OpenID Connect, the URL redirects causes the URL parameter to not be preserved through the authentication process

**Comment by skuzzer** [comment]
Being able to set a default tenant would be very useful, for our use case we have many shared dashboards and visualisations in the Global tenant, when users first login they're defaulted to Private tenant with no dashboards - a confusing user experience.

**Comment by cvemula1** [comment]
We're also looking at the same solution.
When users log in to Kibana they see default tenant as Private.
When we wanted to share the dashboards they can't see any data

**Comment by olddanmer** [comment]
It is a very helpful feature will be. Without this feature using multi-tenancy is inconvenient now.

**Comment by jbarnett1981** [comment]
Same here, is this still an open issue or was there a resolution for this?

**Comment by aashishmodak** [comment]
+1

**Comment by varyumin** [comment]
+1

**Comment by LukaszWasko** [comment]
+1

**Comment by cichons** [comment]
+1

**Comment by boehmerm** [comment]
+1

**Comment by carloshgaray** [comment]
+1

**Comment by dminovski0** [comment]
@singlash26 Putting only one tenant in `opendistro_security.multitenancy.tenants.preferred: ["tenant_name"]` works, but it seems that the manually created tenant's name should be in lowercase letters. The Global worked as default by just removing Private.

**Comment by oscarkraemer** [comment]
It would be nice if users could defined themselves which tenant they would like to use by default. It is quite annoying that one needs to pick a tenant every time one logs in. It would be cool if there would be a "remember my choice" button/checkmark when choosing the tenant.

**Comment by vo2maxCoding** [comment]
+1

**Comment by D3luxee** [comment]
+1

**Comment by PehDeh** [comment]
I also have this issue and would appreciate a fix, it´s quite anoying

**Comment by oseik09** [comment]
+1

**Comment by nickytd** [comment]
Hi 
Can you please share an example of how a user can create saved objects in a shared tenant space using kibana APIs? 
Let's say user A creates an index pattern in a given tenant space A and user B sharing the same tenant space A sees the same index pattern? 
Thanks

**Comment by lancemitchell** [comment]
> 
> 
> Hi
> Can you please share an example of how a user can create saved objects in a shared tenant space using kibana APIs?
> Let's say user A creates an index pattern in a given tenant space A and user B sharing the same tenant space A sees the same index pattern?
> Thanks

**--- Import Objects (to Tenant)**
```
curl \
  -u ADMIN_USER:ADMIN_PWD \
  -H "securitytenant: TENANT_NAME" \
  -H "kbn-xsrf: true" \
  --form "file=@/path/to/exported/object/file/export-file.ndjson" \
  -X POST 'https://kibana.hostname:5601/api/saved_objects/_import'
```

**--- Export ALL Objects (Except Index Pattern - from Tenant)**
```
curl \
  -u ADMIN_USER:ADMIN_PWD \
  -H "securitytenant: TENANT_NAME" \
  -H 'Content-Type: application/json' \
  -H "kbn-xsrf: true" \
  -X POST 'https://kibana.hostname:5601/api/kibana/management/saved_objects/scroll/export' \
  -d '{
  "typesToInclude": [
    "search",
    "dashboard",
    "visualization"
  ]
}'
```

**Comment by nickytd** [comment]
Thanks

**Comment by davidlago** [comment]
Closing as this feature has already been implemented (config `default_tenant`, see https://opensearch.org/docs/latest/security/multi-tenancy/multi-tenancy-config/)
