### ISSUE TITLE
OpenID plugin not registering endpoints

### ISSUE THREAD

**Issue by joshblease** [opensearch-project/security-dashboards-plugin#744]
In the OpenIdAuthentication.init method, the request to the IDP provider doesn't finish before the plugins have been started up. This results in the routes never being added and therefore the OpenID authentication system does not work and users are presented with an "Unauthorised" message when hitting Kibana.

**Comment by hgoscenski-imanage** [comment]
I also encountered this issue, we resolved by replacing editing this file `/usr/share/kibana/plugins/opendistroSecurityKibana/server/auth/types/openid/openid_auth.js` and removing the call to the `openIdConnectUrl` and hardcoding our values, which immediately allowed correctly logins and correctly adding the routes.

We also noticed that if kibana had to do any migration of an index or create and index it also allowed the openid config to be correctly created. This appears to be a race condition between the kibana startup and the provisioning of the openid protected routes.

**Comment by joshblease** [comment]
I also came up with the same solution @hgoscenski-imanage, if you do need a plugin to install I have forked the repo and created a release with a working solution - https://github.com/OpenSource-THG/security-kibana-plugin/releases/tag/v1.13.0.2

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
