### ISSUE TITLE
Kibana behind HTTPS - “Kibana did not load properly”

### ISSUE THREAD

**Issue by vnil1994** [opensearch-project/security-dashboards-plugin#76]
As first opened in the forums [here](https://discuss.opendistrocommunity.dev/t/kibana-behind-https-kibana-did-not-load-properly/1286), there seems to be an issue when Kibana is placed behind a reverse-proxy providing HTTPS access to the kibana web-ui.

We're greeted with the following text when visiting the UI:

![image](https://user-images.githubusercontent.com/48046901/62848223-e5742f80-bcda-11e9-917a-ae6f9df7cb4d.png)

If we reload the page, the text eventually disappears and we're able to access the login page.

**Comment by vnil1994** [comment]
Anyone looking at this? Anyone else experiencing this?

**Comment by vnil1994** [comment]
I just updated the thread mentioned above, can someone please take a look at this?

**Comment by chuanzgh** [comment]
Anything from the logs?

**Comment by vnil1994** [comment]
We have another instance running opendistro 1.1.0 where we have the same issue.

**Comment by vnil1994** [comment]
![Screenshot 2019-09-11 at 15 42 53](https://user-images.githubusercontent.com/48046901/64702489-f1563b80-d4aa-11e9-9c7c-68616aa64cab.png)

**Comment by ash74268** [comment]
I am running kibana behind HTTPS using opendistro 1.1.0 and kibana 7.1.1 with no issues. can you post your kibana.yml file?
