### ISSUE TITLE
[BUG] Not Able to Access Kibana Console after Version Upgrade to 1.13.x

### ISSUE THREAD

**Issue by luistilingue** [opensearch-project/security-dashboards-plugin#761]
Hi.

I'm facing the same problem as related here https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/3, making impossible to browse Kibana.

**Comment by luistilingue** [comment]
Please make that plugin work with Spaces :)

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
