### ISSUE TITLE
[BUG] Blue color doesn't match new logo blue 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security-dashboards-plugin#767]
**Describe the bug**

Coming from https://github.com/opensearch-project/security-dashboards-plugin/pull/766, the blue in the dashboards color scheme doesn't match the logo blue.

**Expected behavior**
Same belu.

![](https://user-images.githubusercontent.com/79167042/119395501-72a62f80-bc88-11eb-89e4-50e3abb23a0e.png)

**Comment by mihirsoni** [comment]
Hi @dblock  Moved the issue from Dashboard repo, this page is owned under Security plugin.

**Comment by dblock** [comment]
@mihirsoni @hsiang9431-amzn [was saying](https://github.com/opensearch-project/security-dashboards-plugin/pull/766#issuecomment-847275352) that this blue comes from dashboards configuration

**Comment by kgcreative** [comment]
I believe this is an EUI issue - and should be addressed by an updated theme with the correct color scheme.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!

**Comment by kgcreative** [comment]
Thanks, Dave!

@KrooshalUX - let's track this (closed) issue when we do our first pass at an OUI theme

**Comment by peternied** [comment]
@kgcreative Would you like to reopen this issue so it can be tracked?

**Comment by kgcreative** [comment]
@peternied - not yet. We will re-open when we're ready to action on it.
