### ISSUE TITLE
[BUG] The role kibana_read_only is able to edit dashboards

### ISSUE THREAD

**Issue by amitbyahoo** [opensearch-project/security-dashboards-plugin#776]
**Describe the bug**
The role kibana_read_only is able to create/edit/delete dashboards.

**To Reproduce**
1. Go to Kibana as a user who has kibana_user role 
2. Create a visualization for any existing index patterns (if not present, create an index_pattern for data indices)
3. Create a dashboard and add the visualization to this dashboard
4. Click on "Share" to get a link to dashboard 
5. Login to Kibana as another user who has kibana_read_only role or give kibana_read_only role to the above user
6. Launch the link to shared dashboard
7. Notice that in addition to viewing the dashboard the user can also edit it.

**Expected behavior**
According to documentation at https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/users-roles/ the role should only be able to view 
"A special role that prevents users from making changes to visualizations, dashboards, and other Kibana objects. See opendistro_security.readonly_mode.roles in kibana.yml. Pair with the kibana_user role."

**Plugins**
N/A

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version OpenDistro and Kibana 1.13

**Additional context**
None

**Comment by CEHENKLE** [comment]
Transferring issues -- @lukkoor.

**Comment by hsiang9431-amzn** [comment]
The issue can be viewed as the UI control for editing dashboards are not properly hidden.

In this screen shot, the user is granted `kibana_read_only` role however the `edit` button is still visible in UI

<img width="2032" alt="Screen Shot 2021-08-09 at 6 07 55 PM" src="https://user-images.githubusercontent.com/79167042/128793415-b65081ef-2248-406a-8429-193553ca89f5.png">

The button is usable and read only user is capable for removing visualization from dashboards. 

Fixes is needed for hiding `Edit` UI from users with `kibana_read_only` role

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
