### ISSUE TITLE
[BUG] “Remember my selection next time I log in from this device.” doesn’t work

### ISSUE THREAD

**Issue by Mosarvit** [opensearch-project/security-dashboards-plugin#779]
Hello!

“Remember my selection next time I log in from this device.” doesn’t seem to be working as it is intended. We have a multi-tenant ELK setup and when a user set a tenant and click on the remember preference checkbox it still takes back the user to global tenant each time they login or refresh the session(page reload on session expiry).

**To Reproduce:**

1. Create more than one tenant
2. Enable multitenancy on Kibana
3. Login to Kibana (in our case, using SSO)
4. Select any tenant other than Global
5. Select “Remember my selection next time I log in from this device.”
6. Confirm
7. Wait until session expires
8. Reload the page
9. Actual behavior
10. Global tenant is selected

**Expected behavior:**
The previously selected tenant should be still selected

**OpenSearch Version:**
OpenDistro 1.13.2

**Comment by tw-ayush** [comment]
We are also facing the similar issue, Seems like the local storage variable` "opendistro::security::tenant::saved" ` is updating every time we change the tenant and ask it to remember the same, but when we reopen the page (or when the access token is refreshed) it doesn't reads that variable information correctly.

**Comment by shortstack** [comment]
having this issue as well and it's causing a lot of headache :(

**Comment by frankeros** [comment]
Hello, when do you plan to fix it? Will the solution also be applied in the opendistro project?

**Comment by ahopp** [comment]
I'm not actually sure that OpenSearch supports a persistent tenant feature (i.e. default to the last use tenant). @hsiang9431-amzn do you happen to know?

**Comment by davidlago** [comment]
This has been fixed. I just tested this in the latest version of OpenSearch and tenant selection is indeed persisted (when using the same browser).

**Comment by gopalk-iprogrammer** [comment]
The checkbox option to “Remember my selection next time I log in from this device.” is not available in the 2.11.0 version, seems to be missing at the time of tenant selection.
@davidlago any idea how can we get it back?
