### ISSUE TITLE
[BUG] re-login not working after logout

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/security-dashboards-plugin#790]
Link to original issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/526

**Describe the bug**

Re-login not working after logging out successfully. It's looking like `security_authentication` is getting wiped out and can't return even after logging in until you restore the params in the url and refresh the application. Might be from the API side when we log out of Dashboards. 

But it's related to the security plugin, although I believe it is the engine's plugin that is failing I think it's worth creating in the Dashboard's plugin just in case. 

I would transfer this issue but for some reason I don't have access to do so.  I'm really sorry but do you mind closing this issue and creating a new issue [here](https://github.com/opensearch-project/security-dashboards-plugin/issues/new?assignees=&labels=bug%2C+untriaged%2C+Beta&template=bug_template.md&title=%5BBUG%5D) and copying over the content? I can do so for you if you like, just let me know! 

Thanks!

**To Reproduce**
1. login to OpenSearch Dashboards with default credentials admin/admin -> login is successful
2. logout
3. try to relogin with the same credentials
4. nothing happens. Login page appears again. In Dev Console (F12) I can see http 401.

**Expected behavior**
re-login is possible

**OpenSearch Version**
1.0.0-rc.1

**Dashboards Version**
1.0.0-rc.1

**Plugins**
all plugins activated  by default

**Screenshots**
![image](https://user-images.githubusercontent.com/25737721/122926051-c0858480-d367-11eb-814f-7c72d0fdc5ee.png)

**Host/Environment (please complete the following information):**
 - OS: Windows 10
 - Browser and version: Vivaldi 4.0.2312.25 (Stable channel) (64-Bit)

**Additional context**

Reload Login page with just https://<servername>:<port>/ and you can login again with identical credentials.
The urls are looking slightly different:
not working (get this after logout):  https://opendashboards.k8s-dev.local/app/login?nextUrl=
working: https://opendashboards.k8s-dev.local/app/login?nextUrl=%2F

**Comment by hsiang9431-amzn** [comment]
this bug is fixed in PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/778
