### ISSUE TITLE
[BUG] `kibana_read_only` not working as expected

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/security-dashboards-plugin#798]
**Describe the bug**
- `kibana_read_only` does not allow user switching to `global tenant`
- When user is granted `kibana_read_only` role, editing options for dashboards should be hidden

**To Reproduce**
1. create an user
2. grant it the role `kibana_read_only`
3. login as the newly created user
4. the user can not switch to global tenant
5. grant the user `kibana_user`, log out and log in to the user
6. user can access global tenant dashboards but also modify it

**Expected behavior**
When user is granted `kibana_read_only` role, it should be able to see global tenant
and the UI controls for modifying global tenant shall be hidden

**Host/Environment (please complete the following information):**
 - Version 7.10

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
