### ISSUE TITLE
Kibana read only mode?

### ISSUE THREAD

**Issue by havidarou** [opensearch-project/security-dashboards-plugin#80]
Hello, I'm using Opendistro 1.0 (for Kibana 7.0.1).
I've noticed there's a reserved role called `kibana_read_only`, which is empty (it doesn't make any sense).

I tried using `kibana_user` one, but I've noticed that cloning it and assigning an user to it doesn't work (it only works with the original role).
But in doing so, I can't modify it to remove permissions (and obtain a true read_only role).

Can anyone help?

Regards.

**Comment by yoke88** [comment]
the same issue , 

using a copy of kibana_user role and do not change any thing . then add a user to this role, the user see blank dashborad list。

only the original kibana_user role works

es version 7.6.1
od security 1.6.0

**Comment by helmanofer** [comment]
Same
Using es 7.7.0
plugin 1.0.0.8-1

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
