### ISSUE TITLE
Kerberos authentication type not found

### ISSUE THREAD

**Issue by huze169** [opensearch-project/security-dashboards-plugin#802]
Hi,

I tried to run the OpenSearch dashboards with Kerberos as authentication type.
I don't know when, but it seems like Kerberos was removed some time ago.

However, if I have a non-existing authentication type, it shows the following message:

![image](https://user-images.githubusercontent.com/15943350/126141407-a5f63d0e-16ae-43f2-8328-98a8dbf4d312.png)

So I decided to change it to "kerberos", which shows the following message:

![image](https://user-images.githubusercontent.com/15943350/126141505-0d7a5207-86db-482d-8da8-6b99a3897414.png)

So what's the deal with Kerberos? Why is Kerberos not supported anymore? Is there a Changelog where the removal was announced?

Kerberos is still supported in OpenSearch, but not for the OpenSearch Dashboards. Is there a specific reason?

Thanks.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
