### ISSUE TITLE
Disable Private tenant for `kibana_read_only` users

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/security-dashboards-plugin#812]
**Is your feature request related to a problem? Please describe.**
Users assigned `kibana_read_only` role can not modify any kibana index, thus granting them access to private tenant does not make much sense and is causing confusing for users

**Describe the solution you'd like**
Read only users, users assigned `kibana_read_only` role, should not have private tenant
If the current tenant is ever resolved to private tenant, use global tenant instead

**Comment by hsiang9431-amzn** [comment]
If this is implemented, the bug mentioned here can be fixed: https://github.com/opensearch-project/security-dashboards-plugin/issues/820

**Comment by davidlago** [comment]
Closed with #868
