### ISSUE TITLE
Able to reset password which does not meet the given password policy.

### ISSUE THREAD

**Issue by dishabodade** [opensearch-project/security-dashboards-plugin#817]
# User creation and reset password do not validate the message shown below the text box.

## case 1:
1. Login as an admin user in kibana.  
2. Navigate to security -> internal users -> create user.  
3. Enter username and password.  Here password policy is mentioned as "Password should be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one digit, and one special character." But able to enter any password. Password validation is not added here.

## case 2:
1. Login to Kibana UI from any internal user.
2. Click reset password from user options provided in top right corner having user avtar and details.
3. here also same password policy is mentioned as above but able to enter any password. password validation not added as per the message given below

## Expected behavior
Should show a valid error message and should not able to reset until it matches password policy

## OpenDistro Version
1.13.2.0  
docker image : amazon/opendistro-for-elasticsearch-kibana:1.13.2

**OpenDistro-for-elasticsearch-kibana Version**
1.13.2.0
docker image: amazon/opendistro-for-elasticsearch-kibana:1.13.2

**Plugins**
All plugins provided by opendistro

**Screenshots**
![passowd_validation_2](https://user-images.githubusercontent.com/14861624/131088138-e2a009b7-7897-47a8-8db6-c73387a33a0c.JPG)

![password_validation](https://user-images.githubusercontent.com/14861624/131088221-da2f44c9-1020-49ad-ac23-e35c5dceb56a.JPG)

**Host/Environment (please complete the following information):**
 - OS: ubuntu server 18.04.04
 - Browser and version : chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Comment by dishabodade** [comment]
While creating the user in internal users username also validations are missing.

**Comment by davidlago** [comment]
This issue has been addressed by several PRs recently (https://github.com/opensearch-project/security/issues/3055, https://github.com/opensearch-project/security/pull/2557). Please re-open if anything was missed. Thanks!
