### ISSUE TITLE
No warning or error message displays when no tenant is chosen under choose from custom option

### ISSUE THREAD

**Issue by dishabodade** [opensearch-project/security-dashboards-plugin#819]
# When clicked on confirm without selecting tenant, no error message was shown.

**To Reproduce**
1. Login to kibana with some user.
2. Do not select any tenant and click confirm button
3. It won't proceed forward but don't show any error message.

**Expected behavior**
It should show a proper error message.

**Plugins**
all plugin are installed.

## OpenDistro Version
1.13.2.0  
docker image : amazon/opendistro-for-elasticsearch-kibana:1.13.2

**OpenDistro-for-elasticsearch-kibana Version**
1.13.2.0
docker image: amazon/opendistro-for-elasticsearch-kibana:1.13.2

**Screenshots**
![select_tenant](https://user-images.githubusercontent.com/14861624/131675636-7845be2f-471e-4166-8686-22d53f22e6d1.JPG)

**Host/Environment (please complete the following information):**
- OS: ubuntu server 18.04.04
- Browser and version : chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Comment by davidlago** [comment]
Confirmed still present in 2.1.0

**Comment by shanilpa** [comment]
Thanks for raising this issue. 
The UX team suggests the following solution: 

1. When a user selects the custom tenant option without a selection from the dropdown (EUISelect/OUISelect) we disable the "Confirm" CTA preventing the user from proceeding or erroring out
![image](https://user-images.githubusercontent.com/113368824/193111766-64c23089-db04-41d4-843b-99235af17e18.png)

2. Once a selection is made via the dropdown (EUISelect/OUISelect) the "Confirm" CTA is enabled allowing the user to proceed.
![image](https://user-images.githubusercontent.com/113368824/193111795-b9c19eff-6e47-44cb-93a1-90f627704fb9.png)
