### ISSUE TITLE
[BUG] read only user can not access dashboards when it is in private tenant

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/security-dashboards-plugin#820]
**Describe the bug**

**To Reproduce**
1. Create a read only user with 3 roles: `kibana_read_only`, `kibana_user` and `readall`
2. Login as the user in an incognito window (firefox private window)
3. If prompted to select tenant, select `Private`
4. Select `Dashboards` on the side bar
5. See `Application Not Found` error

**Expected behavior**
Show empty dashboards UI

**Plugins**
security plugin: FE/BE

**Screenshots**
<img width="1828" alt="Screen Shot 2021-09-01 at 5 01 53 PM" src="https://user-images.githubusercontent.com/79167042/131925103-5f008d05-33b8-40e4-b4c4-b743e2dbdae2.png">

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by davidlago** [comment]
Fixed with #812 as private tenant is no longer an option
