### ISSUE TITLE
[BUG] Not able to nevigate out of "Application Not Found" page

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/security-dashboards-plugin#821]
**Describe the bug**
`Application Not Found` page does not have any button or hyperlink for user to leave it or reset the URL

**To Reproduce**
1. Login as admin
2. Go to `http://localhost:5601/app/qqqqqq`
3. See `Application Not Found`
4. No way to leave unless manually pasting `http://localhost:5601` to the URL

**Expected behavior**
Some manual option is provided for the user to leave this page

**Plugins**
security - FE and BE

**Screenshots**
<img width="1904" alt="Screen Shot 2021-09-02 at 4 00 08 PM" src="https://user-images.githubusercontent.com/79167042/131926712-ff631cf9-0b7c-4b6b-85e4-b5146efa50d8.png">

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by davidlago** [comment]
Apologies for the very late reply. As several versions (including major ones) have come out and we have not heard of reports like this, I'm going to go ahead and close as potentially resolved, please re-open with more details if that is not the case. Thanks!
