### ISSUE TITLE
[BUG] Security UI not showing for non-default admin user

### ISSUE THREAD

**Issue by nebulon42** [opensearch-project/security-dashboards-plugin#822]
**Describe the bug**
Referencing #578 which is closed but concerns Opendistro and not OpenSearch and #15 which is still open but concerns a very old version of Opendistro I also have problems to get the Security UI to show up. I have an admin user which has both the roles `security_manager` and `security_rest_api_access` as well as `all_access` assigned but I still do not see the Security UI. I'm expecting it within "OpenSearch plugins" but it is also not to be found within "Stack Management" if it could be there.

I'm unsure what role(s) a user needs to get access to the Security UI and if there is a bug or if I'm doing something wrong.
The documentation is not clear on this either. Even in #578 you find both above mentioned roles. I have not set `security_rest_api_roles_enabled` and I'm not sure how to set this within `opensearch.yml`.

**To Reproduce**
1. Login in with non-default admin user that has `security_manager` and/or `security_rest_api_access` roles assigned.
2. Click on the menu icon on the left.
3. Observe in the opened drawer that there is no "Security" menu entry within "OpenSearch plugins".

**Expected behavior**
I'm able to access the Security UI with a non-default admin user which has the right roles assigned (it is unclear which those are).

**Plugins**
OpenSearch Security plugin 1.0.0
and maybe others that come with a default setup

**Host/Environment (please complete the following information):**
unrelated to client config

**Comment by wkruse** [comment]
After upgrade to the newest OpenSearch **1.2.0** the issue is still there. I am using OpenID Connect IdP, the `admin` backend role is mapped to `all_access`, `security_manager` and `security_rest_api_access`. No traces of the Security UI are visible.

**Comment by jacen05** [comment]
I faced the same problem. The minimal configuration that worked for me is:

- in opensearch.yml : plugins.security.restapi.roles_enabled: ["all_access"]
- in roles_mapping: mapping all_access role to your admin user

Of course other combinations also work. My current setting is:

- in opensearch.yml : plugins.security.roles_mapping_resolution: BOTH
- in opensearch.yml : plugins.security.restapi.roles_enabled: ["admin"]
- in internal_users.yml: adding the "admin" backend role to my admin user
- in roles_mapping.yml: mapping the all_access role to "admin" backend role

I agree that documentation is not clear on this topic.

**Comment by wkruse** [comment]
@jacen05 Awesome! Works like a charm, thanks a lot! 🍻
