### ISSUE TITLE
[BUG] Totally disable tenancy

### ISSUE THREAD

**Issue by mvanderlee** [opensearch-project/security-dashboards-plugin#838]
**Describe the bug**

https://discuss.opendistrocommunity.dev/t/totally-disable-tenancy/5833

When multi-tenancy is disabled, it should not prompt the user to 'Select your tenant'
Or at least there should be an option to disable the pop-up.

**To Reproduce**
1. Disable multi-tenancy `opensearch_security.multitenancy.enabled: false`
2. Log in
3. See popup

**Expected behavior**
Should not show pop-up

**OpenSearch Version**
1.0.0 & 1.1.0

**Dashboards Version**
1.0.0 & 1.1.0

**Plugins**
* security
* s3 repository

**Screenshots**

![image](https://user-images.githubusercontent.com/918128/137537125-06fdf805-f763-4d74-b053-bc9dee35e198.png)

**Host/Environment (please complete the following information):**
 - Docker
 - Chrome

**Additional context**

**Comment by frankeros** [comment]
Hi, any updates about it?

**Comment by kavilla** [comment]
Duplicate issue: https://github.com/opensearch-project/security-dashboards-plugin/issues/854

**Comment by aggarwalShivani** [comment]
Hi, any updates on when this fix will be planned?

**Comment by amirkkn** [comment]
Hi @kavilla , is there any plan to fix this bug?

**Comment by kavilla** [comment]
Duplicate issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1174

**Comment by kavilla** [comment]
Hello @amirkkn, I see @hsiang9431-amzn assigned to it. @hsiang9431-amzn would you be able to comment on this issue?

**Comment by dredwilliams** [comment]
@hsiang9431-amzn - it's been a while ... is there any progress on this?

**Comment by amirkkn** [comment]
> Hello @amirkkn, I see @hsiang9431-amzn assigned to it. I believe they will have better insight.

Hi @kavilla . I see, no one anymore was assigned to this issue. Do you see any progress about it in the near future?

**Comment by davidlago** [comment]
Hi there! it is in our radar but haven't had a chance to get to it. This seems self-contained enough to be a first issue/PR for new contributors, so tagged as such in case anyone can jump in before we get to it!

**Comment by peterzhuamazon** [comment]
Is this meant to be only in `main` @cliu123 ?

**Comment by cliu123** [comment]
@peternied I believe that this didn't get backported to 2.0 branch just in order to minimize the risk of breaking 2.0.0-rc1 path to release. It can be a part of 2.0.0 GA if that will be safer.

**Comment by xonvanetta** [comment]
Would it be a hassle to backport to 1.x? As an upgrade to 2.x is a bit far away for us but we working on it

**Comment by davidlago** [comment]
@xonvanetta we no longer have new feature releases coming out for the 1.x line, only bug fixes, sorry.

**Comment by davidlago** [comment]
Sorry... it _is_ a bug! I take it back

**Comment by jimishs** [comment]
Thanks @peternied for getting this in quickly ! This enhances the end user experience.

**Comment by peternied** [comment]
Merge this fix into 1.3 - it will be available on the next patch release

https://github.com/opensearch-project/security-dashboards-plugin/pull/1095

**Comment by ramanavenky22** [comment]
This issue is replicable in Opensearch Version 2.7.0

**Comment by fira** [comment]
Yup. Confirming it's a thing as of 2.7.0
