### ISSUE TITLE
[BUG] Can not logout if logging in as a user with no role

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/security-dashboards-plugin#842]
**Describe the bug**
If logging in as a user who has no role, the web application is trapped in a loop that renders it unusable

**To Reproduce**
1. Create an internal user and don't assign any role to it
2. Login as the user, dashboards will show the following error page
<img width="762" alt="Screen Shot 2021-10-18 at 5 13 34 PM" src="https://user-images.githubusercontent.com/79167042/137823495-64c87b4d-328a-4590-b0f3-64761f4947d1.png">
3. Click on `Back to Kibana home` and get bring back to this page

**Expected behavior**
The user should be logged out and allows logging in as another user

**Plugins**
security

**Comment by cwperks** [comment]
Closing this issue as addressed. See linked PR.
