### ISSUE TITLE
[BUG] Roles table has confusing legend

### ISSUE THREAD

**Issue by hsiang9431-amzn** [opensearch-project/security-dashboards-plugin#843]
**Describe the bug**
The legend for Roles table in security plugin is not accurate

**To Reproduce**
1. Go to `Roles` page as admin

**Expected behavior**
The column header `index permission` is not showing index permission but rather `index pattern`

**Plugins**
security

**Screenshots**
<img width="1664" alt="Screen Shot 2021-10-18 at 2 30 02 PM" src="https://user-images.githubusercontent.com/79167042/137823890-d3a192e8-6436-443a-991c-988284fbc991.png">

**Comment by davidlago** [comment]
That column is consistently named with the overall role edit page, where index patterns are used to assign permissions:
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5722719/79b5a400-db1a-49e1-89ef-b25f610585f0)
![image](https://github.com/opensearch-project/security-dashboards-plugin/assets/5722719/eb22c76f-6c50-40e2-9cfd-cb8e5899e9b9)
