### ISSUE TITLE
Use SNAPSHOT artifacts from maven for dependencies

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security-dashboards-plugin#859]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/45, use SNAPSHOT Maven dependencies from [aws.oss.sonatype.org](https://aws.oss.sonatype.org/content/repositories/snapshots). See https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#building-within-the-opensearch-build-system for details.

https://github.com/opensearch-project/security-dashboards-plugin/blob/main/.github/workflows/integration-test.yml#L36

**Comment by hsiang9431-amzn** [comment]
Integration test updated in this PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/860
