### ISSUE TITLE
Can we use Cognito on a self-hosted OpenSearch Dashboard with an AWS OS Service backend?

### ISSUE THREAD

**Issue by bluepeter** [opensearch-project/security-dashboards-plugin#864]
- We are using AWS OpenSearch Service for OS hosting
- We wish to use a customized OS Dashboard hosted on ECS/Docker (versus the one hosted on AWS OpenSearch Service)
- We have configured the OpenID plugin to Cognito and it is logging in and redirecting back with an auth code, but we get the following:

> opensearch-dashboards2 | {"type":"log","@timestamp":"2021-11-15T20:00:52Z","tags":["error","plugins","securityDashboards"],"pid":1,"message":"OpenId authentication failed: Error: [index_not_found_exception] no such index [_plugins], with { index="_plugins" & resource.id="_plugins" & resource.type="index_expression" & index_uuid="na" }"}

Is it possible to do this? Any pointers? (Or other spots where we can discuss this?)

**Comment by CEHENKLE** [comment]
Moving to Security dashboards plugins.  If you think this is an error, please let me know!

**Comment by bluepeter** [comment]
Thank you. We would love to figure out if we can use Cognito w/ OpenSearch w/ or w/o the plugin!

**Comment by haydengoldstein** [comment]
Hi, Did you guys come right ? I'm getting the same error. Can't login

**Comment by davidlago** [comment]
Please take a look at the multiple datasources feature we recently released: https://opensearch.org/docs/latest/dashboards/discover/multi-data-sources/

Adding your backend as one of those data sources might be the solution here.

**Comment by pawelw1** [comment]
@bluepeter If you still didn't find a solution, please open a new thread in the [OpenSearch Forum](https://forum.opensearch.org/c/security/).
