### ISSUE TITLE
Restore snapshot from backup(different cluster’s snapshot)

### ISSUE THREAD

**Issue by anthony1910** [opensearch-project/security-dashboards-plugin#866]
i am having the issue with permission as the image below, that is going to restore snapshot from different cluster's snapshot in S3.

![image](https://user-images.githubusercontent.com/87245399/125820037-269649f8-9e53-4d77-94b5-480174aaf237.png)

Anyone has any idea ?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
