### ISSUE TITLE
Index permission "indices:admin/resolve/index" missing from Kibana Security UI [Enhancement]

### ISSUE THREAD

**Issue by zibrata** [opensearch-project/security-dashboards-plugin#870]
**Describe the bug**
I figured out that the "indices:admin/resolve/index" index permission can’t be add from the Security UI of Kibana when editing/creating a role.
However, it can be done through API request (PUT _opendistro/_security/api/roles/<role-name>).

**To Reproduce**
1. Go to 'Security' section
2. Select a role and click on 'Edit role'
3. Scroll down to 'Index permissions'
4. Try to add "indices:admin/resolve/index" which doesn't appear

**Expected behavior**
This permission should appear.

**Additional context**
The only way I found to add this permission is from the API:

`PUT _opendistro/_security/api/roles/users
{
  "cluster_permissions": [
    "some_actions"
  ],
  "index_permissions": [
    {
      "index_patterns": [
        "*"
      ],
    "allowed_actions": [
      "indices:admin/resolve/index",
      "some_actions"
    ],
  "tenant_permissions": [
    {
      "tenant_patterns": [
        "global_tenant"
      ],
      "allowed_actions": [
        "kibana_all_read",
        "kibana_all_write"
      ]
    }
  ]
}`

**Comment by davidlago** [comment]
Thanks for the report! Checked in 2.1.0 and the permission is there now.
