### ISSUE TITLE
[BUG] global tenant, default route and tenant while logging in

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/security-dashboards-plugin#873]
**Describe the bug**
This might be expected behavior but I'm not able to see clear information about this.

Is it for sure the experience that you can never log in to the global tenant? Like even if you set the route? I've noticed a visual bug like if you attempt to pass global tenant to the route it might show in the top right corner 'Global' (this might have been address because I was using a cloud hosted OpenSearch 1.0.0). But no matter what you will be in a private tenant.

The global tenant is defined as using the default index for Dashboards (ie, `.kibana`). But while logging the security plugin will use `.kibana_xyztenant` and use the default route defined there. So even if the global tenant has a defined default route it will never be respected?

Can we get some documentation or disabling of settings in the global tenant like the default route?

**To Reproduce**
1. Login into Dashboards
2. Switch tenant to public
3. Create a dashboard with title 'global' copy link to saved object and put as default route
4. Log out
5. Log in, notice not default route change
6. Switch tenant to private
7. Create a dashboard with title 'private' copy link to saved object and put as default route.
8. Log out
9. Notice default route change. 

**Expected behavior**
Not to be able to set default route if it won't be respected or if default route is set for global tenant and default route is not set for private tenant then revert to using global tenant.

**Plugins**
security

**Screenshots**
n/a

**Host/Environment (please complete the following information):**
 - OS: Ubuntu

**Additional context**
n/a

**Comment by kavilla** [comment]
A work around I was able to do was set the default route in the private tenant to be the global tenant and then I was able to be re-routed to global tenant and views.

**Comment by davidlago** [comment]
Thanks for the report! Linking and closing in favor of #74  where we can track the related work.
