### ISSUE TITLE
[BUG] Read only user cannot create Short URL's

### ISSUE THREAD

**Issue by luizportela** [opensearch-project/security-dashboards-plugin#891]
**Describe the bug**

When using a read-only user,  a http`403` error happens when trying to create a Short URL, with the message: `Unable to create short URL. Error:`

**To Reproduce**
1. Duplicate the role `kibana_user` to `kibana_user_global_ro`
2. On the role `kibana_user_global_ro` add an index permission for the index "*" with `get`, `read`, `search`,`suggest` permissions.
3. On the role  `kibana_user_global_ro` add a `global_tenant` read only permission.
4. Associate the user with the roles `kibana_user_global_ro` and `kibana_read_only`
5. Go to OpenSearch Dashboards Discover, Share, and select `Short URL` 

**Expected behavior**

Read-only users should be able to navigate and use the Short URL feature without the need for a tenant **write** permission.

**OpenSearch Version**
1.0

**Dashboards Version**
1.0.0

**Plugins**

alertingDashboards@1.0.0.0
anomalyDetectionDashboards@1.0.0.0
ganttChartDashboards@1.0.0.0
indexManagementDashboards@1.0.0.0-rc1
notebooksDashboards@1.0.0.0
queryWorkbenchDashboards@1.0.0.0
reportsDashboards@1.0.0.0
securityDashboards@1.0.0.0
traceAnalyticsDashboards@1.0.0.0

**Screenshots**
<img width="1436" alt="Screen Shot 2022-01-13 at 4 23 25 PM" src="https://user-images.githubusercontent.com/24320745/149411426-367e55bc-b033-405e-9d00-470d59d158c1.png">

**Comment by DarshitChanpura** [comment]
> Thanks for opening this! Creating the short URL does a write operation to the system index to store the URL. However, the security plugin prevents write operations to the system index for read only users.

This is an expected behavior of security plugin.

**Comment by jimishs** [comment]
I believe this a side effect of how short URLs are generated (by writing to a protected index). I believe we should consider to support this for readonly users by improving the implementation to meet the needs of the user. 

I am also open to hear reasons on why we should not support this for readonly users. 

@elfisher @ahopp would appreciate any insights. Thanks

**Comment by elfisher** [comment]
What should the expectations of the user be here? I would think if the user it was shared with has permissions to the objects loaded in the page, then the URL should be loadable by that user.

**Comment by jimishs** [comment]
@elfisher The URL itself is loadable, but the issue is with current implementation for creating a share saved object short URL link, which seems to check if a user has write permissions to the tenant index, in order to generate a shareable URL. I think the user experience we should strive for is - If a user has permissions to view an object, they should also be able to generate a shareable short URL to the same. Note that when the receiving user clicks on the shareable link, they still need to authenticate to Dashboards, but the shared link acts like a bookmark that will take them straight to this dashboard or whatever other saved object is being shared. 

Happy to hear any different views as well.

**Comment by elfisher** [comment]
> @elfisher The URL itself is loadable, but the issue is with current implementation for creating a share saved object short URL link, which seems to check if a user has write permissions to the tenant index, in order to generate a shareable URL. I think the user experience we should strive for is - If a user has permissions to view an object, they should also be able to generate a shareable short URL to the same. Note that when the receiving user clicks on the shareable link, they still need to authenticate to Dashboards, but the shared link acts like a bookmark that will take them straight to this dashboard or whatever other saved object is being shared.
> 
> Happy to hear any different views as well.

That makes sense and sounds reasonable. @kavilla and @davidlago I'd love to get your thoughts on what the right way forward is to enable this experience.

**Comment by MaciejMierzwa** [comment]
Hi, since I started looking into it, I talked with @kajetan-nobel who is working on the parent task: https://github.com/opensearch-project/security/issues/2701. It seems like this short_url task could be done in the scope of the parent one. Here's the PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4498/files#diff-11afec5e134a00ee3d5860652aa06d2c6cd6b0e2e3c54d0110a1c64eba1dd8d4R41-R45

**Comment by MaciejMierzwa** [comment]
Here's PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5539 
It doesn't fully utilize the solution mentioned in comment https://github.com/opensearch-project/security-dashboards-plugin/issues/891#issuecomment-1691743385 by Peter. Let me know what do you think

**Comment by MaciejMierzwa** [comment]
Closing as issue was resolved in scope of different task: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5539#issuecomment-1832594360

**Comment by weand** [comment]
[Comment above](https://github.com/opensearch-project/security-dashboards-plugin/issues/891#issuecomment-1691743385) states:
> Resolution of the root issue
> ...
> Workspace [2] is a new effort to decouple the access control model of the OpenSearch backend from the Dashboards features

Just tried the workspace feature on 2.18 with an Read Only Collaborator. The user sees the Short Link Button, but it results again in `Unable to create short URL. Error: Forbidden`
![image](https://github.com/user-attachments/assets/16a50242-7f9b-4a49-bbee-980a75e989c8)


Is the "Short Link" feature supposed to work with readonly contributors in workspaces?
