### ISSUE TITLE
[Enhancement] Disable Security Dashboards Plugin with Configurable Parameter

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/security-dashboards-plugin#896]
As of now, Security BE plugin has a param to disable the entire plugin `plugins.security.disabled=true`.
As users of dockers, people tend to mount their drive separately and put configuration file to readonly mode or root user at time.
Therefore, with such param, users can easily disable security plugin with env vars without tweaking the configuration file directly.

There is no similar behavior / parameter present in Security FE (dashboards) plugin.
In order to disable security dashboards plugin, users need to:
1. Remove the plugin with `bin/opensearch-dashboards-plugin` script.
2. Go to config file opensearch_dashboards.yml and remove all `security` related config, and change https to http as well.

Users would need to edit the config file directly, which caused several issues for them, and is not convenient in use.

Thanks,
Peter

**Comment by peterzhuamazon** [comment]
@davidlago @cliu123 @hsiang9431-amzn please take a look at this.
Thanks.

cc: @bbarani

**Comment by peternied** [comment]
@cliu123 could you provide more details on this could be addressed?

**Comment by peternied** [comment]
[Triage] We are not making investments in this space as part of the security plugin.  Security's position in OpenSearch is evolving and as part of that work, how security settings are enabled will be changed, this functionality will be taken into account in the new designs.
