### ISSUE TITLE
API Based Login

### ISSUE THREAD

**Issue by SivaSentienz** [opensearch-project/security-dashboards-plugin#899]
Hi Team,

We have started using OpenSearch Dashboards for our project. Here we have checked the documentation and its really helpful and neatly described the points. We are trying to upgrade it from ES to OpenSearch. 
We want to check is there any api based login for Dashboard UI. 
If it is there, please let us know the link.

Please guide us how we can make the login programatically?

**Comment by cliu123** [comment]
@SivaSentienz Could you please describe your use cases?
