### ISSUE TITLE
Support httpsProxy in OpenSearch Dashboards for OIDC support

### ISSUE THREAD

**Issue by sastorsl** [opensearch-project/security-dashboards-plugin#911]
**Is your feature request related to a problem? Please describe.**
When configuring OIDC OpenSearch Dashboards needs to connect with https to our outside OIDC / OpenID Connect provider.
When / if OpenSearch Dashboards is installed in a **closed environment** all outside / internet connection **has to go through an httpsProxy / SOCKS proxy**.

Pr now I have not found / not found documentation to support setting httpsProxy parameters for OpenSearch Dashboards.

**Describe the solution you'd like**
Add support for setting httpsProxy / httpProxy for OpenSearch Dashboards.
Documentation for the same.

**Describe alternatives you've considered**
The current workaround we are using are local proxying with netcat + host aliases. Not a very nice sollution, but "works".

**Additional context**
N/A

**Comment by sastorsl** [comment]
Sorry for not responding earlier.

We are doing something like this how, only using an `socat` proxy.
However, I consider this a workaround, not a good solution, so in my mind this issue should not be closed.

A good solution would be that OpenSearch Dashboards supported proxy directly.
And the underlying software for dashboards do have support for proxies.

**Comment by kogelc** [comment]
Hello, 

Some news about the support of this setting ?
This is a blocking point in the use of OIDC in some environments

Thanks

**Comment by BornTKill** [comment]
Dear,

Have also issue when configuring alert to slack channel. Opensearch Dashboard is ignoring system proxy.
Pretty annoying.

**Comment by sastorsl** [comment]
> If you are behind a proxy you need to add below configs to your “/etc/opensearch/jvm.options” file

This will apply to OpenSearch proper, but not to OpenSearch Dashboard which the `security-dashboards-plugin` / OpenSearch Dashboards Security Plugin

**Comment by DavidoRotho** [comment]
PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE

**Comment by DavidoRotho** [comment]
I really need this

**Comment by DavidoRotho** [comment]
> @DavidoRotho This PR was merged recently and will be released in 2.12 in January. #1650
> 
> Would this PR solve the issue?

@cwperks, thanks for the reply, I don't think so as it doesn't appear to update anything related to a proxy. 
There seems to be a poor understanding of the issue here, this incorrectly closed issue details the problem well: https://github.com/opensearch-project/security-dashboards-plugin/issues/114

**Comment by sastorsl** [comment]
https://github.com/opensearch-project/security-dashboards-plugin/blob/main/server/auth/types/openid/routes.ts#L90 - `setupRoutes`, or better yet, a common place, needs to support setting an `https_proxy` ++ proxy, such as squid and similar.

Again, this is for when OpenSearch Dashboards is installed with **no direct internet access**, but has to go through a *explicitly defined** proxy server.

```bash
opensearch-dashboards --> https_proxy --> OIDC-provider
```

There are quite a few issues regarding this floating around, such as https://github.com/nodejs/node/issues/8381

Different programming languages have various options for how you configure this as an environment variable

```bash
http_proxy=<proxy-host>
https_proxy=<proxy-host>
HTTP_PROXY=<proxy-host>
HTTPS_PROXY=<proxy-host>

http.proxyHost=<proxy-host>  # java
```

**Comment by smbambling** [comment]
@sastorsl we are hitting this issue as well. The above solution that was posted by @aoguan1990 is unclear to me.  

What is your current work around to allow OIDC to reach out to login.microsoftonline.com when a https_proxy like squid is required ?

**Comment by u72z** [comment]
+1 we have the same problem here

**Comment by sastorsl** [comment]
WORKAROUND:

1. Setup an socat proxy as a separate pod / container that proxies requests to your OIDC providers hostname through the company / internal proxy (i.e. squid)
2. Add an entry to `hostAliases` to OpenSearch Dashboards, see https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/ 

See i.e. https://github.com/fluxcd/source-controller/issues/131#issuecomment-769419918 for a similar discussion.

**Comment by mustafaocak** [comment]
+1 we have the same problem here

**Comment by pintomic** [comment]
> WORKAROUND:
> 
> 1. Setup an socat proxy as a separate pod / container that proxies requests to your OIDC providers hostname through the company / internal proxy (i.e. squid)
> 2. Add an entry to `hostAliases` to OpenSearch Dashboards, see https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
> 
> See i.e. [fluxcd/source-controller#131 (comment)](https://github.com/fluxcd/source-controller/issues/131#issuecomment-769419918) for a similar discussion.

Thanks for the hint, the solution works fine for requests which do not depend on the headers being sent. I'm using something like this:
```yaml
  containers:
  - image: alpine/socat:1.8.0.0
    name: socat-proxy
    args:
      - -v
      - -dddd
      - -lh
      - TCP-LISTEN:8443,fork,reuseaddr,children-shutup=1
      - PROXY:proxy.server.url:<host>:443,proxyport=8080,proxy-authorization=<username>:<password>
    command:
    - socat
    ports:
    - containerPort: 8443
      protocol: TCP
```
As soon as the http request sends an authorization header the request via the proxy fails. Is there anything I'm missing?

**Comment by uladzimir-tryputska** [comment]
To have Proxy support this code https://github.com/opensearch-project/security-dashboards-plugin/blob/2.14.0.0/server/auth/types/openid/openid_auth.ts#L179-L190 should you ProxyAgent instead of HTTP.Agent or HTTPs.Agent
