### ISSUE TITLE
Pending functional tests for security-dashboards-plugin 

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security-dashboards-plugin#913]
Here is the list of functionalities that are yet to be tested page-wise:

###  Roles
- [ ] Edit
- [ ] Duplicate
- [ ] Delete

###  Internal Users
- [ ] Sorting by table headers
- [ ] Edit
- [ ] Duplicate
- [ ] Delete
- [ ] Search

###   Permissions
- [ ] Search with all 3 filter criteria
- [ ] Sorting by table headers
- [ ] Create from selection

###  Tenants

- [ ] Search
- [ ] Edit
- [ ] Duplicate
- [ ] Delete
- [ ] Private tenant
- [ ] View Dashboards link
- [ ] View Visualizations link

###  Audit Log
- [ ] Modify General settings
- [ ] Modify Compliance settings

**Comment by peternied** [comment]
Is there a way to know that this list is correct / isn't missing something?  I am hoping for some kind of code coverage metric that we could interrogate and drive upward

**Comment by peternied** [comment]
[Triage] Lets circle back on these at a case by case basis and see if we should implement them with feature work.
