### ISSUE TITLE
Read Only Dashboard User Role causes Forbidden Errors on visualizations on a doashboard with tenants enabled

### ISSUE THREAD

**Issue by inf17101** [opensearch-project/security-dashboards-plugin#916]
If you create a Read Only Role according to the documentation (https://opensearch.org/docs/latest/security-plugin/access-control/users-roles/#set-up-a-read-only-user-in-opensearch-dashboards) then a "Forbidden" error is thrown of some visualizations.

![image](https://user-images.githubusercontent.com/42932060/156995659-97edc167-1130-41cc-a20f-e4f66b7b5875.png)

If you create a read only user with the documentated role settings some visualizations on a dashoard shows an errror.
If you hit multiple times CTRL + F5, the visualization loads correct but other visualizations show this error instead.

**To Reproduce**
1. Create a Read Only Dashboard User according to the Opensearch documentation
2. Create a Tenant
3. Create some dashboards
4. Log in with the user into the tenant

**Expected behavior**

**OpenSearch Version**
1.2.2

**Dashboards Version**
1.2.0

**Plugins**

Please list all plugins currently enabled.
alertingDashboards@1.2.0.0
anomalyDetectionDashboards@1.2.0.0
ganttChartDashboards@1.2.0.0
indexManagementDashboards@1.2.0.0
observabilityDashboards@1.2.0.0
queryWorkbenchDashboards@1.2.0.0
reportsDashboards@1.2.0.0
securityDashboards@1.2.0.0

**Host/Environment (please complete the following information):**
 - Opensearch and Opensearch Dashboards are running on Linux Ubuntu Server 20.04
 - Win10 / Chrome Version 98.0.4758.102

**Additional Information**
Sometimes you can see the following exception in the log:
{"type":"log","@timestamp":"2022-03-07T10:27:06Z","tags":["error","opensearch","data"],"pid":338569,"message":"[security_exception]: no permissions for [indices:data/read/search] and User [name=eagle_01, backend_roles=[], requestedTenant=null]"}

It is very confusing that "requestedTenant" for such a request is empty, because multi tenancy is enabled. And the user has full read only permissions according to documentation.

**Comment by peternied** [comment]
@jimishs Do you know if we have an update on this issue?

**Comment by jimishs** [comment]
@inf17101 Could you share whether the said user has the right index permissions to the indices that are being visualized? 

From the error above i see that the said user may not have read permissions on the index being visualized.

**Comment by zydyka** [comment]
I join the problem, I also have multitenancy, and several indexes for which only reading and filtering at the document level are configured.  in discover, i can see everything as needed. in the dashboard, some panels are "Forbidden" or "The request for this panel failed", which change if the page is refreshed 
opendistro 7.10.2

**Comment by omar-chaabouni** [comment]
Try this, 
![image](https://user-images.githubusercontent.com/55398565/169515785-e54d0641-fbeb-40c2-a2e0-10ccc941f265.png)

**Comment by jseiser** [comment]
We are dealing with this now on Opensearch 1.2

Using the above setup, the users can login but they get an empty top left menu. The only way users can actually `see` the `discover` section of the Kibana menu is if they are in the `security_manager` group.

**Comment by nibix** [comment]
See https://github.com/opensearch-project/security/issues/2701#issuecomment-1554067472 for a analysis of the dashboards read only functionality. 

Regarding the configuration shown at https://github.com/opensearch-project/security-dashboards-plugin/issues/916#issuecomment-1132775597 : This seems to achieve a read only tenant, but it is wrong on two levels:

- The action group `opensearch_dashboards_all_read` does not exist. It is still called `kibana_all_read`: https://github.com/opensearch-project/security/blob/main/src/main/resources/static_config/static_action_groups.yml
- This action group must be configured as a tenant permission, but not as an index permission. As an index permission, it would not have any effect.

Regarding the randomly appearing Forbidden error: My gut feeling is that there is another issue interfering as well. This would need more thorough information for analysing and reproducing the issue like user and role config and more context from the logs.
