### ISSUE TITLE
Problems creating role mapping through API

### ISSUE THREAD

**Issue by mporracindie** [opensearch-project/security-dashboards-plugin#935]
So I tried creating role mappings for existing roles through API and im getting the following error:

<img width="268" alt="Screen Shot 2019-10-18 at 10 52 40" src="https://user-images.githubusercontent.com/42622776/67100210-a3adac80-f195-11e9-8b02-638b9f5736fe.png">

But, as I mention the role already exists. If I try to click on the warning and create the role I get:

<img width="580" alt="Screen Shot 2019-10-18 at 10 52 47" src="https://user-images.githubusercontent.com/42622776/67100283-bfb14e00-f195-11e9-9514-9f88f05e8fc0.png">

**Comment by peternied** [comment]
[Triage] It looks like this issue has been resolved, closing this tracking issue.
