### ISSUE TITLE
Remove usage of legacy url API `.query` 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security-dashboards-plugin#936]
We should switch to `.search` which is part of the node api, see https://nodejs.org/docs/latest-v14.x/api/url.html which has more details.

Impacted code
https://github.com/opensearch-project/security-dashboards-plugin/blob/fc7b8cc994046c830d950dc57742e6f1ac542b7b/server/auth/types/basic/routes.ts#L173-L174

**Comment by peternied** [comment]
[Triage] We should also look into url.path that is used right above this location in the file.

**Comment by cliu123** [comment]
Removing the label for 2.0.0 as the PR hasn't been ready yet.
