### ISSUE TITLE
Bump the version for 1.3.2 opensearch-dashboards release 

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/security-dashboards-plugin#937]
**Is your feature request related to a problem?**
Post Release activity https://github.com/opensearch-project/opensearch-build/issues/1885 - 

We need to bump the version for 1.3.2 in 1.x and 1.3 branches for 1.3.2 releases wrt to the release issue - https://github.com/opensearch-project/opensearch-build/issues/1882

ETA - 04/14/2022

**Comment by peternied** [comment]
Resolved in https://github.com/opensearch-project/security/commit/f0c4ac1ddc6faf32cff4b8831245da749b3f1ab3

**Comment by peternied** [comment]
Wrong repository, this work still needs to be done

**Comment by zelinh** [comment]
We could close this issue since #978 was merged.
