### ISSUE TITLE
[BUG] Missing `security_authentication` cookie auth fails with 401

### ISSUE THREAD

**Issue by VladutZzZ** [opensearch-project/security-dashboards-plugin#939]
Hello,
I have deployed on opensearch cluster with oidc auth and we get `{"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}` error from time to time.

From what I found, if `security_authentication` cookie is not present, opensearch doesn't use OIDC auth and maybe use internal_auth which will fail because no internal user is used.

The error returned is `{"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}`.
Maybe is related with this part https://github.com/opensearch-project/security-dashboards-plugin/blob/e08dca4eca8906ade344a00ca2b80289037522c3/server/session/security_cookie.ts.

Thank you.

**Comment by peternied** [comment]
@VladutZzZ  Would you mind opening a case in the [OpenSearch forum](https://discuss.opendistrocommunity.dev/c/security/) and sharing the link here for traceability?

**Comment by VladutZzZ** [comment]
@peternied 
Sure,
here is the link https://forum.opensearch.org/t/missing-security-authentication-cookie-kibana-page-will-fail-with-401/9451

**Comment by peternied** [comment]
Thanks @VladutZzZ I am going to close out this issue.
