### ISSUE TITLE
[ No error thrown in kibana while accessing index-pattern with no data]

### ISSUE THREAD

**Issue by archupriya3** [opensearch-project/security-dashboards-plugin#999]
**What is the bug?**
When a user not having the permission to access the index trying to access the index which has no data, permission error message is not displayed.
Prelude to this issue: We are able to create index-pattern through rest calls even without the indices actually present.

**How can one reproduce the bug?**
1. Create a user with permission to access only a particular index pattern
2.  Login to Kibana with user with restricted permissions
3.  Try to access any other index-pattern for which user has no permission

**What is the expected behavior?**
Display of error message that the user does not have permission to access the particular index pattern.
Instead "No results match your search criteria" is displayed.

**What is your host/environment?**
 - Centos
 - Version 7.10.2
 - Plugins
opendistroSecurityKibana-1.13.0.1

**Do you have any screenshots?**
Attached screenshot

**Do you have any additional context?**
Add any other context about the problem.
![image](https://user-images.githubusercontent.com/42887698/170179106-e36be07e-146a-46ac-a053-f5b06f40f5a3.png)

**Comment by peternied** [comment]
@archupriya3 This is to prevent accidently disclosing that some indices exist or don't exist, while this can be a frustrating scenario for users it has been a long standing design.  As tenancy is revisited in the coming release there will be opportunities to reinvent better user experiences and this will be taken into consideration.

**Comment by archupriya3** [comment]
Hi @peternied : This issue was not observed in the earlier versions of opendistro 1.9.0 and observed in in opendistro 1.13.1 hence wanted to understand if there were some changes that led to the change in behaviour of reporting the error messages.

**Comment by peternied** [comment]
Its possible this has to do with the configuration, if you'd like please open a [support issue](https://forum.opensearch.org/c/security/3) to troubleshoot in our forums.  Note; we  support more recent versions of OpenSearch (1.3+), the version of the security plugin you mentioned in this issue report is no longer supported.
